PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;

insert into User values(0, 'Blanca Hall', 154169309, '757, 1st Street East - Des Moines', 'lBsRFLvJdf');
insert into User values(1, 'Todd Heath', 509413823, '418, 3rd Street East - McAllen', 'nESx6J9iVb');
insert into User values(2, 'Chelsea Whitehead', 841324958, '792, Larkspur Lane - Eugene', 'FmoDQsWR6H');
insert into User values(3, 'Jon Rowland', 437845930, '763, Sunset Lane - Havre de Grace', 'b4lQkTzJCP');
insert into User values(4, 'Carl Woods', 793437209, '460, 8th Street East - Sunnyvale', '2gFRRAalK4');
insert into User values(5, 'Kayla Middleton', 233387482, '311, State Street - Marina', 'JXB6Rsv8aS');
insert into User values(6, 'Shawn Camp', 525368938, '184, 16th Street - Lorain', 'fXWO1btdKK');
insert into User values(7, 'Ashley Bowling', 466486120, '563, Woodland Avenue - West Covina', 'qnY3Ki9ydT');
insert into User values(8, 'Vernon Noble', 720619998, '940, Albany Avenue - Tallahassee', '707UMCnnIV');
insert into User values(9, 'Ruben Forrest', 194681351, '47, Route 4 - Santa Maria', 'zBbFf3eRFn');
insert into User values(10, 'Hilary Harrison', 178422144, '374, 8th Street West - Milwaukee', 'SuH4hbZTo7');
insert into User values(11, 'Ricky Wilkinson', 936226687, '504, Glendale Road - Aberdeen', 'uQ5XUrRVtp');
insert into User values(12, 'Christine Harper', 611707892, '846, Hillside Avenue - Pembroke Pines', 'SUJIldgnz2');
insert into User values(13, 'Tiffani Ingram', 791625258, '13, Woodland Drive - Overland Park', 'nsaAXhehn9');
insert into User values(14, 'Heather Ferguson', 806614447, '535, Crestview Drive - Salinas', 'xQ5daOvI1h');
insert into User values(15, 'Betty Beard', 331299433, '429, Jennifer Lane - West Covina', 'ctLX2pEZqO');
insert into User values(16, 'Theresa Bauer', 417443755, '893, Berkshire Drive - New York City', 'BSNX4ECNq1');
insert into User values(17, 'Albert Yang', 337762459, '736, Salem Street - McAllen', '3AZTsUjfrJ');
insert into User values(18, 'Peter Sutherland', 969493897, '932, Clinton Avenue - Huntsville', 'Rs17WcPjeO');
insert into User values(19, 'Zachariah Ryan', 854943148, '82, Birch Drive - Lacey', 'AAJYlEbaAZ');
insert into User values(20, 'Elizabeth Woodruff', 225705530, '770, Amherst Street - Racine', 'SmdK2AtnCX');
insert into User values(21, 'Barbara Hayes', 587363979, '928, Aberdeen Drive - Cambridge', 'gDB8wwYi5e');
insert into User values(22, 'Freddie Hendricks', 823705879, '622, Tanglewood Drive - Lowell', 'rMfJC86eFa');
insert into User values(23, 'Audra Vincent', 953850610, '82, Tyler Court - Chandler', 'OoF4pUrbt6');
insert into User values(24, 'Brett Zhou', 589417879, '375, King Road - Panama City', 'hXaLzIkPmM');
insert into User values(25, 'Briana Barbee', 198987484, '248, Woodland Street - Carrollton', '5uu2r4hd3U');
insert into User values(26, 'Roland Long', 821805867, '288, Buttonwood Drive - Reno', 'HZ8Dvz2fIc');
insert into User values(27, 'Don Bynum', 810480748, '190, Skyline Drive - GreenBay', 'ZQ0EacXvMB');
insert into User values(28, 'Ariana Stevens', 967437997, '378, Virginia Avenue - Murrieta', '1ncc84Tdhu');
insert into User values(29, 'Ashlie Lambert', 229244337, '36, Adams Avenue - Costa Mesa', 'rtBSqV3EMa');

insert into Restaurant values(0, 'Talula’s Garden', 'Sandwiches', '206, Federal Street - McAllen', 'C8yzpZEpIy');
insert into Restaurant values(1, 'Gotham', 'Sandwiches', '572, Cambridge Circle - San Antonio', 'DSducp1Oog');
insert into Restaurant values(2, 'Providence', 'Bagels', '77, Amherst Court - Pueblo', 'b9ncoSI95c');
insert into Restaurant values(3, 'Arethusa al tavolo', 'Hot Dogs', '932, Edgewood Drive - Odessa', 'eEVAcp6djF');
insert into Restaurant values(4, 'Tofino', 'Steaks', '467, Railroad Avenue - Hartford', 'Gne3KBZlDx');
insert into Restaurant values(5, 'Skate And Stay', 'Thai', '157, Windsor Circle - Davidson County', 'xavLPoaZWO');
insert into Restaurant values(6, 'Hurry Curry', 'British', '21, Anderson Avenue - Wilmington', 'AnbRbviPpC');
insert into Restaurant values(7, 'Big Moe’s Diner', 'Bagels', '17, 38th Street East - Newport News', 'UNe119JV3O');
insert into Restaurant values(8, 'Estela', 'German', '996, Route 152 - Elk Grove', 'pnhn6FXnjF');
insert into Restaurant values(9, 'Rock and Roll cafe', 'Burgers', '809, Center Street - Evansville', 'eFRYKk6DlE');
insert into Restaurant values(10, 'FIG', 'Vegetarian', '821, Birchwood Drive - Tucson', 'h3ATiDB9xr');
insert into Restaurant values(11, 'Ocean City', 'Sushi', '5, Belmont Drive - Thousand Oaks', 'xKMqyr2QXY');
insert into Restaurant values(12, 'Cafe Monarch', 'Happy Hour', '844, Academy Street - Montgomery', 'XLh2k5yiml');
insert into Restaurant values(13, 'Fun Circle Retro', 'Doughnuts', '390, Sherman Street - Cape Coral', 'dn77L67iIC');
insert into Restaurant values(14, 'Dine Fine', 'Family Fare', '627, Riverside Drive - Greenville', '9vEapyACRj');
insert into Restaurant values(15, 'Gramercy Tavern', 'Caribbean', '537, 17th Street East - Burbank', '48HbqgoRiK');
insert into Restaurant values(16, 'Coquine', 'Waterfront', '719, Virginia Avenue - Savannah', 'z91ztKask4');
insert into Restaurant values(17, 'Single Shot', 'Sports Bar', '462, Cross Street - Chattanooga', '6QhR6oeK50');
insert into Restaurant values(18, 'Fred’s Tacos Corner', 'Vegan Friendly', '211, Hickory Court - Boise City', 'tulEMLDFzJ');
insert into Restaurant values(19, 'Quick Eats', 'Vegetarian', '129, Yorkshire Drive - Eugene', 'ctLX2pEZqO');
insert into Restaurant values(20, 'Indian tulip', 'Mexican', '297, Pine Valley Drive - Winston', 'cgCf0vmrSs');
insert into Restaurant values(21, 'Arethusa al tavolo', 'Country Food', '296, Central Avenue - Panama City', '34xSsOLy8T');
insert into Restaurant values(22, 'Melisse Restaurant', 'British', '365, Howard Avenue - Saint Louis', 'JWpzR9kQDS');
insert into Restaurant values(23, 'The Modern', 'Greek', '645, Michigan Avenue - Charleston', '8dkHzhbMA8');
insert into Restaurant values(24, 'Le Coucou', 'Soup & Salad', '563, Evergreen Avenue - Lakeland', 'A2BsJFVycC');
insert into Restaurant values(25, 'Sweet Snow', 'Pizza', '573, 8th Street North - Boulder', 'HHjxn6rCt0');
insert into Restaurant values(26, 'Club A Steakhouse', 'Hot Dogs', '795, Front Street - Palm Springs', 'CQY5LVlKxH');
insert into Restaurant values(27, 'Pho Shizzle', 'Happy Hour', '858, Cypress Court - Fort Smith', 'izzR3seFFx');
insert into Restaurant values(28, 'Homemade Bagels', 'Breakfast', '643, Broad Street West - Inglewood', 'cFEK6orZbj');
insert into Restaurant values(29, 'Jockey', 'Mediterranean', '661, North Street - Kissimmee', 'pYLAu0SYXY');

insert into Review values(0, 'Proin vel arcu vitae nibh imperdiet vehicula vel ac turpis. In quis sem odio. Phasellus velit ex, blandit vel enim vitae, aliquam ultricies enim. Aliquam efficitur, magna in maximus tincidunt, enim sapien sollicitudin risus, sit amet tristique turpis mi eget quam. Duis vel rutrum lacus. Morbi porttitor commodo lacus sit amet faucibus. Etiam sodales elit fermentum vehicula bibendum. Nullam laoreet at ipsum id pharetra. Morbi ornare pretium justo, id congue metus dignissim at. Vivamus nisl justo, aliquet ut hendrerit a, scelerisque non eros. Nam ac magna enim. Nullam ultricies posuere tempor. Sed sit amet ex ac turpis fermentum vulputate. Aenean porttitor varius lorem.', 8, 13, 13);
insert into Review values(1, 'Quisque non congue nibh, maximus dictum nisl. Maecenas a aliquam elit, sed semper orci. Phasellus eleifend pulvinar commodo. Cras ut massa risus. Donec vitae augue eu eros malesuada dignissim in nec eros. Praesent ultrices mattis mollis. Cras placerat vulputate scelerisque. Vestibulum sit amet condimentum elit.', 3, 0, 8);
insert into Review values(2, 'Integer gravida ante mauris, a dapibus mauris rhoncus quis. In aliquet enim sit amet egestas egestas. Sed eu felis elit. Etiam suscipit tortor et vestibulum porta. Quisque eu ipsum ipsum. Quisque pharetra orci et lectus luctus sodales quis nec mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse erat libero, faucibus vitae gravida et, finibus non turpis. Curabitur venenatis ornare purus id auctor. Nam eleifend, erat at suscipit rhoncus, lectus justo ornare massa, eget blandit massa massa et ante. Mauris varius ipsum eget efficitur egestas. Nulla ac nunc non dolor lobortis elementum. Maecenas mollis quam vitae nulla sollicitudin lobortis. Proin dignissim pharetra velit, et convallis diam porta vel.', 1, 16, 26);
insert into Review values(3, 'Morbi neque mauris, aliquet vel purus vitae, tincidunt sodales lacus. Vestibulum egestas nisl fringilla dui gravida mollis. Sed sed tempor massa, ac blandit dui. Pellentesque sit amet ultrices mauris. Pellentesque consectetur ultricies volutpat. Nullam malesuada turpis quis ex suscipit tempus. In nec accumsan massa.', 6, 20, 18);
insert into Review values(4, 'Vestibulum faucibus eu velit ut pharetra. Cras porttitor viverra mollis. Duis congue tempor ornare. Suspendisse et dolor nec eros blandit mattis ut quis ligula. Proin scelerisque maximus ex, sed aliquam dolor rhoncus in. In pellentesque ligula justo, vitae congue mauris varius non. Vestibulum bibendum massa maximus ante consectetur, at scelerisque odio sodales. Aenean vitae turpis maximus nibh ullamcorper congue non non lectus. Integer turpis nunc, sagittis vulputate posuere eu, sagittis at purus. Ut cursus augue at ex pharetra fermentum. Etiam justo diam, lacinia eu est consectetur, aliquam maximus augue. Maecenas rutrum magna sit amet fermentum feugiat. Nulla efficitur imperdiet commodo. Etiam faucibus semper nunc, quis tincidunt leo. Maecenas vel lacus non lacus sodales tincidunt eu vel felis. Morbi scelerisque dignissim enim tincidunt ultrices.', 10, 9, 1);
insert into Review values(5, 'In vel nunc non magna tristique vulputate quis vel mi. Fusce posuere egestas orci, at faucibus ex ullamcorper mattis. Donec luctus venenatis magna elementum pharetra. Proin vitae semper eros. Donec sagittis odio eget lectus ultricies, vitae molestie eros vulputate. Sed id tellus sed ante tincidunt faucibus quis nec odio. Sed felis sem, blandit vel molestie nec, tincidunt at dolor. Nullam ut nisi maximus, dictum mi et, porttitor sem. Nunc tristique nec augue ac tempus. Donec ullamcorper diam feugiat semper congue. Aliquam ut enim augue. Vestibulum et consectetur neque. Vivamus sodales id arcu sit amet aliquet.', 9, 10, 0);
insert into Review values(6, 'In pharetra mi eu lacus feugiat, a accumsan justo imperdiet. Nunc posuere et massa tempor fringilla. Praesent sit amet lacus dolor. Vestibulum convallis, eros non condimentum tristique, enim ex lobortis dolor, ut elementum urna orci efficitur ipsum. Quisque tempus ullamcorper nibh sed porta. Donec id pulvinar metus. Ut sed orci imperdiet, vehicula lectus quis, porta erat. Sed scelerisque lacinia urna a scelerisque.', 3, 25, 11);
insert into Review values(7, 'Curabitur accumsan est id dolor cursus tristique. Duis velit purus, congue ac lectus et, varius vestibulum mi. Sed ac quam lacus. In elementum condimentum leo. Fusce in lobortis velit. Nunc rhoncus mauris nec ultricies interdum. In porta est eu orci ornare gravida. Cras condimentum auctor tellus, at varius dui consectetur non. Praesent egestas dignissim metus, a ullamcorper urna gravida in.', 5, 6, 17);
insert into Review values(8, 'Morbi non lorem vehicula quam interdum sollicitudin quis sed nunc. Integer consequat dignissim aliquet. Phasellus et mi augue. Vivamus sed tellus ut tellus consequat porttitor. Sed dignissim felis vitae dui auctor, eget laoreet arcu eleifend. Donec maximus tortor at augue suscipit sodales id a massa. Aliquam at dictum urna, id varius quam.', 5, 6, 23);
insert into Review values(9, 'Aliquam erat volutpat. Nunc laoreet mattis erat, vitae pellentesque nisi fermentum a. Nulla gravida quam eu consequat facilisis. Integer suscipit ex vitae est ullamcorper, quis venenatis turpis maximus. In dictum neque non augue aliquet, sit amet viverra justo feugiat. Morbi at arcu interdum nisl commodo lacinia. Suspendisse vitae convallis dolor. Nunc posuere ornare feugiat. Proin id enim sed ipsum feugiat egestas. Donec purus elit, suscipit et risus vel, ultricies laoreet felis. Nunc gravida purus sit amet libero mattis, in consequat ipsum vulputate.', 1, 6, 23);
insert into Review values(10, 'Nam ac blandit enim. Praesent imperdiet quis lectus at hendrerit. Aenean volutpat at lacus non convallis. Morbi malesuada sagittis fermentum. Donec lacinia rhoncus nunc nec viverra. Ut fermentum at quam ac aliquet. Fusce sit amet nisi in lorem tempus mattis. Fusce sollicitudin mauris nisl. Donec laoreet ut leo in efficitur. Donec laoreet pellentesque ipsum sit amet finibus. Fusce pulvinar lacus quis diam iaculis rutrum. Integer lacus nunc, efficitur at finibus a, rutrum non tortor. Donec in massa tristique ex sodales scelerisque id in dui. Etiam quis ultrices mi. Sed sit amet sapien interdum ex efficitur facilisis in fermentum ante. Sed tristique auctor eros vehicula rutrum.', 6, 24, 2);
insert into Review values(11, 'Nunc eget imperdiet sapien. In eu sem ligula. Donec efficitur vitae lectus et condimentum. Praesent venenatis ex eu leo feugiat ultrices non dapibus nunc. Nulla purus risus, ornare a maximus in, lobortis quis tortor. Mauris in ante id orci tristique consectetur. Fusce cursus, mi a semper dignissim, lacus turpis scelerisque justo, ac ultrices sapien dui posuere eros. Maecenas et tellus mattis, accumsan metus ac, tempor nisi. Mauris ipsum urna, vulputate quis lectus tempus, vehicula efficitur ante. Nam vitae tincidunt est, ac volutpat mauris. Etiam libero lacus, interdum et rhoncus in, gravida id nunc.', 1, 9, 14);
insert into Review values(12, 'Mauris mollis, libero vestibulum accumsan mollis, diam metus porttitor ante, et vestibulum diam purus a dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ullamcorper, neque nec commodo imperdiet, quam nunc posuere nunc, a rutrum felis ex sit amet purus. In ac mauris a elit lacinia iaculis. Praesent hendrerit dictum augue, pulvinar congue ligula. Donec ultricies ultrices mauris, a sagittis mi viverra a. Ut vehicula ultricies suscipit. Proin eu nibh a est vehicula interdum. In lobortis ex sem, porttitor auctor ligula scelerisque eget. Duis maximus nunc nec lorem finibus convallis.', 7, 5, 27);
insert into Review values(13, 'Duis sit amet tristique ligula, et pellentesque sapien. Suspendisse eget rutrum tellus. Integer aliquet volutpat vulputate. Morbi sed augue aliquet, finibus erat fringilla, laoreet sem. Nullam rutrum nisi sed interdum commodo. Nullam ac pellentesque purus. Pellentesque sit amet mauris mauris.', 5, 18, 3);
insert into Review values(14, 'Nullam feugiat, arcu vitae finibus ullamcorper, nulla ligula viverra leo, semper aliquam ante urna in ligula. Aliquam tempor dolor eget nulla imperdiet, vitae interdum dui aliquam. Morbi vel dapibus nibh. Maecenas in congue neque. Pellentesque sollicitudin est libero, quis tempus arcu ultricies sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at nunc diam. Duis at justo pellentesque, posuere purus eget, vestibulum dui. Curabitur eget leo quis tortor iaculis euismod. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at sem sed diam convallis blandit. Aenean eget ipsum sollicitudin, fermentum lectus non, elementum lectus. Mauris lacinia ante ac mauris eleifend, et fermentum neque vestibulum. Ut vehicula lorem sit amet leo pretium, at consequat erat ornare. Integer quis imperdiet velit, commodo vehicula mauris. Donec justo eros, feugiat nec risus in, sagittis tempor sem.', 10, 4, 3);
insert into Review values(15, 'Morbi non venenatis est. Nam ullamcorper dolor nisl, quis sodales magna volutpat a. Nulla non sapien vel libero varius laoreet id id lorem. Donec a iaculis eros. Donec in sem consectetur, molestie purus in, feugiat eros. Maecenas tincidunt, lorem eget ultrices condimentum, leo sem condimentum erat, nec molestie neque orci pulvinar urna. Nam at ex ac est euismod faucibus vitae vitae augue. Praesent fermentum mi in odio porttitor imperdiet. Cras eu vehicula sapien. Donec nulla justo, aliquet sit amet mi sed, suscipit tristique urna.', 1, 0, 28);
insert into Review values(16, 'In hac habitasse platea dictumst. Nam tristique dapibus dolor vel pellentesque. Duis venenatis pharetra dolor et aliquet. Maecenas nec finibus neque, non facilisis orci. Suspendisse malesuada imperdiet condimentum. Aenean nibh velit, aliquet in erat id, dictum luctus erat. Sed hendrerit massa dignissim tortor venenatis dapibus. Praesent pharetra euismod mi a pretium. Donec dignissim id odio vitae volutpat. Nullam finibus, leo a molestie volutpat, ipsum est vulputate urna, et luctus massa diam mattis massa. Aliquam iaculis malesuada dictum. Nullam at congue mi, ac accumsan mauris. Ut venenatis nec felis et maximus. Maecenas mattis libero eget nisi commodo malesuada. Curabitur tincidunt facilisis est ac suscipit. Curabitur dignissim massa a nisi posuere mattis.', 3, 13, 20);
insert into Review values(17, 'Cras ut interdum dolor, eu pretium eros. Cras vitae gravida sem, non varius metus. Suspendisse enim sapien, sagittis eu urna nec, pulvinar eleifend sem. Duis molestie id turpis quis faucibus. Praesent nec varius enim. Mauris sit amet massa efficitur, ultricies mi id, condimentum lorem. Nullam ut risus enim. Nam magna elit, aliquam eget ullamcorper quis, fringilla ac purus. Etiam mauris dui, dictum in nisi eu, suscipit ultricies neque. Aliquam consectetur orci nec tortor fringilla maximus. Phasellus dapibus eros sit amet nibh convallis aliquet. Curabitur consectetur lectus ut turpis ullamcorper, a sodales libero posuere.', 5, 8, 14);
insert into Review values(18, 'Donec at elit ut arcu bibendum placerat. Pellentesque non dui venenatis, mattis augue convallis, luctus dolor. In elementum nisl dolor, ut consequat turpis vulputate id. Vivamus eu arcu nibh. Morbi vitae elit eu lorem iaculis volutpat et et purus. Morbi tempor lacus nunc, a commodo purus venenatis non. Curabitur sed est at dui ultricies tincidunt. Aenean scelerisque est a lobortis semper. Nullam non nunc aliquam enim sagittis pellentesque quis et lacus. Praesent tristique interdum sagittis. Donec vitae urna rutrum, commodo dui a, efficitur odio. Suspendisse nulla leo, fermentum ut diam ut, iaculis accumsan elit. Fusce nec felis diam. Morbi condimentum felis accumsan dolor ornare, vitae dictum purus mollis.', 1, 15, 25);
insert into Review values(19, 'Phasellus quis quam nibh. Integer sit amet leo nulla. Aliquam erat volutpat. Nam nulla tortor, interdum vitae sem eget, eleifend aliquam est. Integer finibus lacus nec velit cursus mollis. Morbi pulvinar velit eros, et molestie est fermentum quis. Nunc quis ligula ut magna sagittis viverra. Etiam nec malesuada felis. Phasellus sed pretium lorem. Sed in dictum odio. Sed tempus porttitor congue.', 6, 13, 2);
insert into Review values(20, 'Pellentesque vehicula sit amet massa vitae lobortis. Aliquam eget sodales ligula, quis ullamcorper orci. Cras lectus lectus, efficitur sit amet sem eget, sodales tempor odio. Nam tincidunt, sapien nec condimentum ultricies, diam libero pellentesque sem, et lacinia diam erat et tellus. Ut tempus rhoncus mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque quis suscipit nisi. Aliquam quis facilisis nulla, sed posuere orci. Sed at facilisis erat. Donec facilisis ullamcorper euismod. Nulla eu maximus nulla. Morbi eget semper ante. Duis hendrerit sit amet felis vel feugiat. Donec sit amet ipsum pellentesque felis dignissim tincidunt commodo ac leo.', 9, 16, 15);
insert into Review values(21, 'In hac habitasse platea dictumst. Nam tristique dapibus dolor vel pellentesque. Duis venenatis pharetra dolor et aliquet. Maecenas nec finibus neque, non facilisis orci. Suspendisse malesuada imperdiet condimentum. Aenean nibh velit, aliquet in erat id, dictum luctus erat. Sed hendrerit massa dignissim tortor venenatis dapibus. Praesent pharetra euismod mi a pretium. Donec dignissim id odio vitae volutpat. Nullam finibus, leo a molestie volutpat, ipsum est vulputate urna, et luctus massa diam mattis massa. Aliquam iaculis malesuada dictum. Nullam at congue mi, ac accumsan mauris. Ut venenatis nec felis et maximus. Maecenas mattis libero eget nisi commodo malesuada. Curabitur tincidunt facilisis est ac suscipit. Curabitur dignissim massa a nisi posuere mattis.', 9, 8, 2);
insert into Review values(22, 'Pellentesque blandit, ipsum ut lobortis malesuada, nunc ante malesuada nisi, sit amet lobortis enim sem vitae dolor. Quisque bibendum consequat porta. Quisque hendrerit lacus sit amet sapien viverra pellentesque. Nunc vitae tempor neque, et fringilla diam. Vivamus viverra porttitor ipsum. Duis ultrices auctor molestie. Donec faucibus nisi ut volutpat placerat. Aenean ultricies dignissim nunc in ultricies. Vestibulum odio ex, eleifend at nisi sit amet, mattis convallis nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;', 2, 19, 25);
insert into Review values(23, 'Suspendisse potenti. Phasellus condimentum massa nunc, eu dapibus lorem sollicitudin a. Curabitur non imperdiet justo. Pellentesque vel lacus vitae erat viverra feugiat. Proin quis velit pulvinar nulla dictum dignissim in quis neque. Integer malesuada magna velit, in sagittis orci scelerisque ut. Fusce ut metus vel elit semper ultrices. Praesent dapibus, arcu vel feugiat venenatis, erat ex commodo eros, semper varius metus eros in libero. Phasellus tincidunt dolor convallis arcu pulvinar tristique rhoncus eget erat. Aliquam erat volutpat. Nam id nibh at nunc pharetra luctus. Sed aliquam, massa tempus sagittis mattis, sem lorem dignissim ligula, ut porta arcu urna sit amet mauris. Duis ultrices semper dui, eu laoreet est consectetur quis. Cras vel laoreet est. Pellentesque id pretium nulla. Donec ac dictum arcu.', 9, 21, 17);
insert into Review values(24, 'Praesent convallis, justo quis volutpat aliquam, ligula risus bibendum lorem, vel convallis lacus ipsum ut purus. Integer lobortis metus eget est porta, sit amet viverra mi lacinia. Suspendisse ac metus porta, mollis velit eget, ultricies lectus. Sed sed pulvinar lorem. In hac habitasse platea dictumst. Nulla a porta nisi. Phasellus consequat, orci pharetra consectetur lobortis, erat dui ultricies quam, sed luctus mauris risus id massa. Donec at nibh vel enim mollis cursus. Sed consequat, augue vitae laoreet condimentum, justo diam finibus augue, sit amet bibendum elit turpis quis ex. Fusce gravida metus venenatis efficitur venenatis. Donec nec mi nibh. Suspendisse lobortis dolor dolor, in pellentesque velit posuere at. Maecenas mauris lacus, tincidunt vitae libero et, dictum dapibus erat. Curabitur elit orci, imperdiet ac turpis in, sodales aliquet sapien.', 4, 8, 6);
insert into Review values(25, 'Pellentesque vehicula sit amet massa vitae lobortis. Aliquam eget sodales ligula, quis ullamcorper orci. Cras lectus lectus, efficitur sit amet sem eget, sodales tempor odio. Nam tincidunt, sapien nec condimentum ultricies, diam libero pellentesque sem, et lacinia diam erat et tellus. Ut tempus rhoncus mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque quis suscipit nisi. Aliquam quis facilisis nulla, sed posuere orci. Sed at facilisis erat. Donec facilisis ullamcorper euismod. Nulla eu maximus nulla. Morbi eget semper ante. Duis hendrerit sit amet felis vel feugiat. Donec sit amet ipsum pellentesque felis dignissim tincidunt commodo ac leo.', 3, 15, 4);
insert into Review values(26, 'In sed nunc varius, condimentum ligula ac, viverra neque. Proin eget tempor mi. Nulla auctor, leo eget mollis ultrices, odio quam pulvinar nibh, eget pellentesque erat quam ut justo. Nulla venenatis ante at arcu dignissim, sed aliquet ex interdum. Sed ornare purus nec lectus tempor, a cursus eros finibus. Praesent sed ornare ligula. Nam ac gravida turpis. Nunc sit amet nisi venenatis sapien rutrum lobortis. Aenean eget nisl euismod risus rhoncus convallis. Nunc nec lacus libero.', 2, 1, 24);
insert into Review values(27, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam faucibus id nisi vitae dapibus. Cras nec turpis libero. Quisque erat lacus, volutpat nec eros sed, euismod tempor nunc. Pellentesque suscipit luctus sagittis. Nunc eget sodales leo, sit amet maximus justo. Sed faucibus dolor eu elementum luctus. Suspendisse potenti. Nunc aliquet egestas nunc, at placerat nunc hendrerit vehicula. Etiam neque orci, laoreet non sodales consequat, aliquet et felis. Nam pulvinar erat at erat dignissim, eget tincidunt nisi venenatis. Mauris eros sapien, finibus sit amet condimentum eu, auctor non arcu.', 7, 20, 21);
insert into Review values(28, 'Suspendisse porta blandit enim, quis lobortis dolor luctus in. Quisque a metus et nulla gravida dapibus in ac mi. Ut maximus sit amet ante ac mollis. In a justo velit. Nulla auctor semper felis, a convallis leo eleifend quis. In hac habitasse platea dictumst. Praesent ullamcorper in metus quis consectetur. Nam eget posuere tellus, eget ultrices velit. Nullam pharetra justo nunc. Mauris risus ex, egestas nec eleifend at, fermentum et mauris. Fusce nunc leo, blandit et felis ut, tempor sagittis lorem. Praesent elementum arcu erat, non vehicula justo tempor vel. Quisque faucibus dui eget molestie dignissim. Nunc finibus sollicitudin diam, nec ullamcorper lorem.', 6, 28, 12);
insert into Review values(29, 'Aenean eget euismod justo. Aliquam nec blandit sem, sed vestibulum arcu. Suspendisse potenti. Curabitur quis ex magna. Nam viverra libero vitae lorem accumsan, ut mattis nisl sagittis. Curabitur vitae neque at lacus condimentum facilisis. Curabitur non lacus interdum, suscipit turpis pretium, rhoncus magna. Donec ut tempor ligula. Integer nec lacus ac velit sagittis commodo. Aenean sed elit mattis, maximus eros vitae, faucibus quam.', 4, 3, 24);

insert into Dish values(0, 13, 'croissant', 40, 'pkck23Fjpt', 'Fine Dining');
insert into Dish values(1, 23, 'stew', 28, 'xSERapKFbW', 'Bakery');
insert into Dish values(2, 18, 'muffin', 27, 'aEUZvKrV0U', 'Italian');
insert into Dish values(3, 6, 'broth', 22, '5Azd7zmMCq', 'Sandwiches');
insert into Dish values(4, 2, 'juice', 3, '1LJTcoPyMS', 'Chinese');
insert into Dish values(5, 13, 'ice', 15, 'CN7eEWH7Bo', 'Steaks');
insert into Dish values(6, 14, 'muffin', 36, '0dBZyGpdgn', 'Seafood');
insert into Dish values(7, 23, 'fish', 31, 'BNd8vLArBV', 'Burgers');
insert into Dish values(8, 2, 'tartar', 29, '9Q6xhx59Np', 'Irish');
insert into Dish values(9, 13, 'skillet', 7, 'oVqB72tAqe', 'Bagels');
insert into Dish values(10, 23, 'salad', 16, 'FfwdcKr7Rt', 'Brunch');
insert into Dish values(11, 14, 'juice', 23, 'Rs17WcPjeO', 'Mediterranean');
insert into Dish values(12, 4, 'filet', 35, 'MgoBfS33Ty', 'Cuban');
insert into Dish values(13, 16, 'wok', 16, 'Qbovl0M31N', 'Latin American');
insert into Dish values(14, 17, 'olive', 30, 'kNDlLHDoIc', 'German');
insert into Dish values(15, 25, 'oil', 3, 'oB88JIYofX', 'French');
insert into Dish values(16, 26, 'caramel', 40, 'pV61yOwtgH', 'Family Fare');
insert into Dish values(17, 2, 'seasoning', 27, 'PY2mfQCvTR', 'Mediterranean');
insert into Dish values(18, 1, 'fish', 32, 'AAJYlEbaAZ', 'Steaks');
insert into Dish values(19, 26, 'cheese', 23, 'BPMUVVYdBJ', 'Asian Fusion');
insert into Dish values(20, 6, 'raclette', 14, 'e7i5kFsk7a', 'Deli');
insert into Dish values(21, 3, 'hamburger', 8, 'EjBxZo6Bmr', 'Gluten-free');
insert into Dish values(22, 7, 'bread', 16, '1WEuVLP8eY', 'Mediterranean');
insert into Dish values(23, 20, 'soy', 27, 'LxUpDAEzxr', 'Mediterranean');
insert into Dish values(24, 3, 'tartar', 23, 'LeIxGywJls', 'French');
insert into Dish values(25, 9, 'skillet', 14, '6QBZXLSJxu', 'American');
insert into Dish values(26, 5, 'taquito', 3, '9uo9qWIXXZ', 'Swedish');
insert into Dish values(27, 2, 'bread', 2, 'TAA4iaBXW3', 'Fast Food');
insert into Dish values(28, 19, 'dish', 4, 'b9ncoSI95c', 'Waterfront');
insert into Dish values(29, 8, 'cobbler', 17, 'kcYjWOtiRM', 'American');

insert into Dish_order values(0, 23, 16, 'waiting to deliver');
insert into Dish_order values(1, 14, 8, 'delivered');
insert into Dish_order values(2, 21, 23, 'delivered');
insert into Dish_order values(3, 15, 22, 'waiting to deliver');
insert into Dish_order values(4, 21, 15, 'processing');
insert into Dish_order values(5, 24, 1, 'waiting to deliver');
insert into Dish_order values(6, 22, 2, 'delivering');
insert into Dish_order values(7, 16, 2, 'preparing');
insert into Dish_order values(8, 1, 2, 'processing');
insert into Dish_order values(9, 25, 18, 'processing');
insert into Dish_order values(10, 10, 21, 'delivered');
insert into Dish_order values(11, 11, 14, 'delivering');
insert into Dish_order values(12, 6, 1, 'waiting to deliver');
insert into Dish_order values(13, 29, 24, 'processing');
insert into Dish_order values(14, 27, 13, 'delivering');
insert into Dish_order values(15, 10, 17, 'delivering');
insert into Dish_order values(16, 14, 4, 'preparing');
insert into Dish_order values(17, 8, 14, 'delivering');
insert into Dish_order values(18, 21, 24, 'delivering');
insert into Dish_order values(19, 15, 4, 'delivering');
insert into Dish_order values(20, 17, 16, 'delivering');
insert into Dish_order values(21, 1, 28, 'preparing');
insert into Dish_order values(22, 18, 24, 'processing');
insert into Dish_order values(23, 22, 12, 'waiting to deliver');
insert into Dish_order values(24, 28, 1, 'waiting to deliver');
insert into Dish_order values(25, 3, 7, 'preparing');
insert into Dish_order values(26, 13, 28, 'preparing');
insert into Dish_order values(27, 13, 2, 'processing');
insert into Dish_order values(28, 19, 20, 'waiting to deliver');
insert into Dish_order values(29, 16, 27, 'delivering');

insert into Restaurant_owner values(0, 9, 19);
insert into Restaurant_owner values(1, 4, 7);
insert into Restaurant_owner values(2, 23, 7);
insert into Restaurant_owner values(3, 27, 3);
insert into Restaurant_owner values(4, 12, 27);
insert into Restaurant_owner values(5, 28, 18);
insert into Restaurant_owner values(6, 6, 12);
insert into Restaurant_owner values(7, 1, 13);
insert into Restaurant_owner values(8, 24, 17);
insert into Restaurant_owner values(9, 22, 17);
insert into Restaurant_owner values(10, 10, 0);
insert into Restaurant_owner values(11, 24, 26);
insert into Restaurant_owner values(12, 20, 8);
insert into Restaurant_owner values(13, 12, 27);
insert into Restaurant_owner values(14, 10, 17);
insert into Restaurant_owner values(15, 4, 3);
insert into Restaurant_owner values(16, 11, 5);
insert into Restaurant_owner values(17, 17, 22);
insert into Restaurant_owner values(18, 27, 10);
insert into Restaurant_owner values(19, 21, 13);
insert into Restaurant_owner values(20, 22, 27);
insert into Restaurant_owner values(21, 25, 22);
insert into Restaurant_owner values(22, 19, 16);
insert into Restaurant_owner values(23, 18, 13);
insert into Restaurant_owner values(24, 9, 4);
insert into Restaurant_owner values(25, 28, 12);
insert into Restaurant_owner values(26, 2, 22);
insert into Restaurant_owner values(27, 18, 15);
insert into Restaurant_owner values(28, 23, 0);
insert into Restaurant_owner values(29, 15, 19);

COMMIT;