PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;

insert into User values(0, 'Felix Xu', 'Markunsightly@mac.com', 889826440, '549, Village Drive - Minneapolis', '8NGxlTq7lZ', NULL);
insert into User values(1, 'Dane Middleton', 'Susanadventurous@bol.com.br', 807633879, '108, Kings Court - Madison', 'tRJ2rcFL9P', NULL);
insert into User values(2, 'Abraham Wilder', 'worrisomeAutumn73@aol.com', 482417546, '70, Chapel Street - Augusta', 'qfzXBklb0y', NULL);
insert into User values(3, 'Lorraine Feldman', 'toughJerry@sky.com', 973573781, '404, Pearl Street North - Durham', 'WBoAr6lZ4C', NULL);
insert into User values(4, 'Karen Norman', 'Jeremynasty@freenet.de', 749916599, '444, Forest Court - Simi Valley', '0NPZGFj9Lk', NULL);
insert into User values(5, 'Adrian Franklin', 'Gloriacute@yahoo.es', 592785467, '176, Wesley Avenue - Deltona', 'GFUTcGxQUv', NULL);
insert into User values(6, 'Genevieve Gibbons', 'openJesus@rediffmail.com', 291762986, '329, Washington Avenue - Richmond County', 'A2BsJFVycC', NULL);
insert into User values(7, 'Audrey Dean', 'Dustinnice@tin.it', 319486259, '7, Wisteria Lane - Orlando', 'cZ4p3w3Wln', NULL);
insert into User values(8, 'Rachel Malone', 'illSuzanne47@yahoo.fr', 565657577, '132, Washington Avenue - Sebastian', '2AicwrSh3t', NULL);
insert into User values(9, 'Jodi Marcus', 'Adamfair@verizon.net', 517828524, '623, Honeysuckle Lane - Burlington', 'UD6AFEOWaS', NULL);
insert into User values(10, 'Adrian Rosen', 'Latashagood@tiscali.it', 702826355, '233, Hamilton Court - New Orleans', 'VWFUQyBDmH', NULL);
insert into User values(11, 'Patricia Lang', 'nastyPeter@planet.nl', 738447366, '703, Elmwood Drive - Leominster', 'dXkaOiBpLy', NULL);
insert into User values(12, 'Frank Harding', 'Evancreepy@shaw.ca', 475109365, '921, Park Drive - Escondido', 'a5FeuyhT2U', NULL);
insert into User values(13, 'Christa Huffman', 'Bonnievast@googlemail.com', 113899883, '307, Stratford Drive - Havre de Grace', 'f8P3FBHf0t', NULL);
insert into User values(14, 'Shelley Jackson', 'thoughtlessPamela80@neuf.fr', 268348324, '641, Perry Street - Toledo', 'EW6GvPCsWB', NULL);
insert into User values(15, 'Andres Rivera', 'Bryceprecious@gmx.net', 793137667, '101, Fairfield Drive - Daytona Beach', '8ccoIaZqzU', NULL);
insert into User values(16, 'Charlene Gillespie', 'uptightChristina29@live.ca', 317893716, '749, Hillside Road - Richmond', 'HHjxn6rCt0', NULL);
insert into User values(17, 'Ashly Schaefer', 'shinyKari25@centurytel.net', 617820409, '708, Cemetery Road - Gilbert', 'rYhTqGwftV', NULL);
insert into User values(18, 'Lauren Hall', 'combativeJoel31@frontiernet.net', 724539218, '463, Franklin Avenue - Bonita Springs', 'abkUolY4Vp', NULL);
insert into User values(19, 'Emma Watkins', 'attractiveAnna42@arcor.de', 895987962, '607, Cobblestone Lane - Naples', 'JQdg3fSEuZ', NULL);
insert into User values(20, 'Micheal Knox', 'cuteBrad@hotmail.co.uk', 745865913, '90, Ivy Lane - St. Petersburg', 'c63r7PRdUg', NULL);
insert into User values(21, 'Neil Schultz', 'puzzledShaun@yahoo.it', 967791565, '954, Danbury Court - Gainesville', '2HFKSNDrOs', NULL);
insert into User values(22, 'Nina Hancock', 'Karenhomely@windstream.net', 124100112, '353, Park Place - Grayslake', 'lylySC8Zuy', NULL);
insert into User values(23, 'Cassidy Manning', 'crazyJerome52@web.de', 725225890, '381, Warwick Road - Birmingham', 'J4Fy81aIAc', NULL);
insert into User values(24, 'Elise Hudson', 'Reneeplain@outlook.com', 532154163, '533, Buttonwood Drive - Monterey', 'DH5CrUtNUa', NULL);
insert into User values(25, 'Shayla Murphy', 'preciousAutumn98@earthlink.net', 651802389, '798, Stratford Drive - Davidson County', 'd7gTs5dsH7', NULL);
insert into User values(26, 'Emmanuel Shea', 'clearMark43@terra.com.br', 744881210, '279, Shady Lane - Sterling Heights', 'z91ztKask4', NULL);
insert into User values(27, 'Tamika Medlin', 'oddSergio37@comcast.net', 709134501, '371, 7th Street South - Jersey City', 'kpUbAGxONy', NULL);
insert into User values(28, 'Mayra Garrison', 'jollyAna74@virgilio.it', 902163899, '636, Harrison Avenue - Augusta', 'GVZGw3hXlI', NULL);
insert into User values(29, 'Terrance Bloom', 'scaryAlexander@me.com', 269695660, '821, Hilltop Drive - Worcester', 'dC3iurKlaC', NULL);
insert into User values(30, 'Jason Miles', 'dangerousPaul@bigpond.net.au', 787531100, '244, Poplar Lane - Waterbury', 'bcRgG4m6fV', NULL);
insert into User values(31, 'Josephine O''Connor', 'fairKristin64@orange.fr', 877726974, '800, Hawthorne Court - Saint Louis', 'ZndrDPVwOE', NULL);
insert into User values(32, 'Russell Dickens', 'putridCynthia59@live.ca', 111961830, '639, Fillmore Street - Torrance', 'FQ8EX5RBwT', NULL);
insert into User values(33, 'Yvonne Rosen', 'Noahfrantic@me.com', 152881795, '0, 4th Avenue - Killeen', 'OFnIn28Ddn', NULL);
insert into User values(34, 'Leroy Peterson', 'Evancreepy@shaw.ca', 870552774, '600, Fairfax Court - Fairfield', 'Z9tFznJ6QF', NULL);
insert into User values(35, 'Jayson Malone', 'awfulBrianna@yahoo.co.jp', 386725127, '294, Wisconsin Avenue - Anaheim', 'GkVz3C4nBV', NULL);
insert into User values(36, 'Elyse Andrews', 'Juliasparkling@sfr.fr', 387995323, '637, Delaware Avenue - Waterbury', 'yLEQFJWtOd', NULL);
insert into User values(37, 'Sheena Gupta', 'Craigexpensive@hetnet.nl', 990203416, '333, Lewis Street - Panama City', 'JARAsHKVga', NULL);
insert into User values(38, 'Russell Berman', 'encouragingErica67@bellsouth.net', 601679569, '189, Broad Street - Shreveport', 'HizcgexA5e', NULL);
insert into User values(39, 'Esmeralda Rose', 'Sandramagnificent@msn.com', 864643641, '266, Grove Street - Cary', 'HA8kI8aJ9F', NULL);
insert into User values(40, 'Jasmine Tate', 'lonelyNeil@live.fr', 223819280, '702, Fieldstone Drive - Fontana', 'I6JFdOCLxj', NULL);
insert into User values(41, 'Dominique Moran', 'angryLatasha@yahoo.ca', 996116880, '431, Pearl Street North - Plano', '9kT8uK95hw', NULL);
insert into User values(42, 'Kari Khan', 'blue-eyedKathleen7@voila.fr', 470933682, '895, Sherman Avenue - Charlotte', 'FHG53dzJIH', NULL);
insert into User values(43, 'Brendan Weaver', 'successfulTyler@me.com', 423171539, '893, Bay Street - Redding', 'YBj7zuom7p', NULL);
insert into User values(44, 'Ashleigh Odom', 'cuteRonald56@planet.nl', 206804157, '554, Stratford Drive - Tuscaloosa', 'FMuXx7QlYG', NULL);
insert into User values(45, 'Salvador Garcia', 'disgustedDeborah0@yahoo.ca', 669749236, '980, Briarwood Drive - Phoenix', 'sH6E8zcneS', NULL);
insert into User values(46, 'Kelli Sharpe', 'wearyJavier@alice.it', 207913328, '996, Cedar Avenue - Salinas', 'O3HaJV48sL', NULL);
insert into User values(47, 'Gloria Richards', 'Oscarmagnificent@sfr.fr', 157930652, '873, Baltimore Avenue - Mobile', 'l9X8NHCKO2', NULL);
insert into User values(48, 'Nina Frye', 'fierceLauren62@bluewin.ch', 283438122, '24, 8th Avenue - St. Paul', 'MOcz2SiZUj', NULL);
insert into User values(49, 'Yesenia Powell', 'charmingKaitlin@yahoo.com.ar', 396870591, '997, Jefferson Court - Apple Valley', '0dBZyGpdgn', NULL);
insert into User values(50, 'Johnny Creech', 'Carauninterested@bigpond.net.au', 496887280, '680, Dogwood Drive - Las Vegas', 'IRD9gC70GG', NULL);
insert into User values(51, 'Elias Lehman', 'Marcdull@sfr.fr', 135606766, '731, Lexington Drive - Rockford', 'aEUZvKrV0U', NULL);
insert into User values(52, 'Stuart Moser', 'darkBryan@tiscali.co.uk', 594246455, '721, Township Line Road - Port Orange', 'O3HaJV48sL', NULL);
insert into User values(53, 'Jolene Powell', 'motionlessPaul41@me.com', 697268445, '224, Jackson Avenue - Atlanta', 'h3ATiDB9xr', NULL);
insert into User values(54, 'Troy Higgins', 'Brittneyweary@mail.com', 122723707, '776, 12th Street North - Davenport', 'BRXsqTf99f', NULL);
insert into User values(55, 'Raul McKee', 'tiredBradley58@hotmail.es', 241424231, '895, Center Road - Lexington', 'aOLZrjcsRZ', NULL);
insert into User values(56, 'Jay Coleman', 'Desireesparkling@voila.fr', 266293148, '38, 6th Street South - Albany', 'X70QnUNQo1', NULL);
insert into User values(57, 'Jodie Cole', 'Wesleyashamed@gmail.com', 822769373, '48, Church Lane - College Station', 'P62smJ6jDO', NULL);
insert into User values(58, 'Hollie Grimes', 'mysteriousMonica@hotmail.de', 600485730, '691, Blue Ridge Drive - Spartanburg', '94HsJ6v5F1', NULL);
insert into User values(59, 'Marlon Farrell', 'attractiveKenneth25@tin.it', 726242794, '953, Surrey Lane - Fayetteville', 'qzCaZ6IKId', NULL);

insert into Restaurant values(0, 'Ya', 'Breakfast', '304, 9th Street North - Clearwater', NULL);
insert into Restaurant values(1, 'Smokey’s Texas Grill', 'Portuguese', '480, Welsh Road - Medford', NULL);
insert into Restaurant values(2, 'Portland', 'Japanese', '415, Windsor Lane - Fontana', NULL);
insert into Restaurant values(3, 'Kurious', 'Brazilian', '923, Oakland Avenue - Melbourne', NULL);
insert into Restaurant values(4, 'Breakfast at any Time [BAAT]', 'Asian Fusion', '566, 2nd Avenue - Hollywood', NULL);
insert into Restaurant values(5, 'Din Tai Fung', 'Cuban', '664, Center Street South - Sebastian', NULL);
insert into Restaurant values(6, 'Quince', 'Ice Cream', '125, Elm Avenue - Atlanta', NULL);
insert into Restaurant values(7, 'Perfect Dish', 'Barbeque', '551, Oakwood Avenue - Bradenton', NULL);
insert into Restaurant values(8, 'The Table', 'Vegan Friendly', '460, Harrison Avenue - Stamford', NULL);
insert into Restaurant values(9, 'Harry Potter', 'Bagels', '376, Ridge Court - Indianapolis', NULL);
insert into Restaurant values(10, 'Finger Floyd', 'Brunch', '928, Andover Court - Little Rock', NULL);
insert into Restaurant values(11, 'Frasca Food and Wine', 'Soul Food', '192, Highland Avenue - Baton Rouge', NULL);
insert into Restaurant values(12, 'Momofuku Ko', 'Brunch', '518, Hickory Court - Roseville', NULL);
insert into Restaurant values(13, 'It`s Vintage', 'Family Fare', '74, Overhill Road - Palm Springs', NULL);
insert into Restaurant values(14, 'Rice House', 'Greek', '473, Essex Court - Bradenton', NULL);
insert into Restaurant values(15, 'Restaurant Gordon Ramsay', 'Seafood', '356, Brighton Road - Henderson', NULL);
insert into Restaurant values(16, 'Mad Desi', 'Deli', '199, Arch Street - Columbus', NULL);
insert into Restaurant values(17, 'Providence', 'Asian Fusion', '796, Oak Avenue - Arvada', NULL);
insert into Restaurant values(18, 'Big Moe’s Diner', 'Burgers', '511, Lakeview Court - Coral Springs', NULL);
insert into Restaurant values(19, 'Mad Desi', 'Vegan Friendly', '316, Walnut Street East - Norman', NULL);
insert into Restaurant values(20, 'Rich Table', 'Fast Food', '493, Route 146 - Greensboro', NULL);
insert into Restaurant values(21, 'Eleven Madison Park', 'Soul Food', '90, Elmwood Avenue - Davenport', NULL);
insert into Restaurant values(22, 'Prevent Fraud', 'Bagels', '870, John Street - Atlantic City', NULL);
insert into Restaurant values(23, 'Tall Oaks Café', 'Japanese', '942, Hawthorne Lane - Newark', NULL);
insert into Restaurant values(24, 'Strip Steak', 'Creole', '372, Hemlock Drive - Pittsburgh', NULL);
insert into Restaurant values(25, 'Project Juice', 'Burgers', '637, Route 35 - San Francisco', NULL);
insert into Restaurant values(26, 'Oriole', 'Greek', '867, Hillside Avenue - Arlington', NULL);
insert into Restaurant values(27, 'Eat Bite', 'Chinese', '812, Morningside Drive - Davidson County', NULL);
insert into Restaurant values(28, 'Station', 'Country Food', '901, Carriage Way - Montgomery', NULL);
insert into Restaurant values(29, 'Hollo Follo', 'Sandwiches', '327, Saint Andrews Drive - Fitchburg', NULL);
insert into Restaurant values(30, 'Happyway', 'Burgers', '512, Nottingham Lane - Boise', NULL);
insert into Restaurant values(31, 'Le Coucou', 'Soul Food', '958, Laurel Court - Bridgeport', NULL);
insert into Restaurant values(32, 'Joystick', 'Cuban', '373, 7th Street - Newport News', NULL);
insert into Restaurant values(33, 'The Old Fashioned', 'Mediterranean', '729, Mockingbird Lane - Tuscaloosa', NULL);
insert into Restaurant values(34, 'Heart Beats food', 'Vegetarian', '877, 12th Street South - Frederick', NULL);
insert into Restaurant values(35, 'Upland', 'Creole', '563, Church Street - Sunnyvale', NULL);
insert into Restaurant values(36, 'Phuc Noodle', 'Sports Bar', '581, Orange Street - Vancouver', NULL);
insert into Restaurant values(37, 'Max & More', 'Cafe', '717, Locust Street - Wilmington', NULL);
insert into Restaurant values(38, 'Magic hands', 'Doughnuts', '649, Homestead Court - South Lyon', NULL);
insert into Restaurant values(39, 'Charleston', 'Indian', '139, Heather Lane - Oklahoma City', NULL);
insert into Restaurant values(40, 'Craft Beer', 'Burgers', '577, Magnolia Drive - Boise', NULL);
insert into Restaurant values(41, 'South', 'Swedish', '456, Highland Court - Grand Prairie', NULL);
insert into Restaurant values(42, 'Service Supplied', 'Tapas', '47, Easy Street - Orem', NULL);
insert into Restaurant values(43, 'Benno Restaurant', 'Thai', '182, Tanglewood Drive - Kalamazoo', NULL);
insert into Restaurant values(44, 'Service Supplied', 'Thai', '278, Lake Drive - Aurora', NULL);
insert into Restaurant values(45, 'Silver River', 'Greek', '446, Hawthorne Drive - Anaheim', NULL);
insert into Restaurant values(46, 'Project Juice', 'Cuban', '366, Thompson Street - Fort Worth', NULL);
insert into Restaurant values(47, 'Ocean City', 'Bar', '490, Sherwood Forest Drive - Murfreesboro', NULL);
insert into Restaurant values(48, 'Skate And Stay', 'Soup & Salad', '773, White Street - Hialeah', NULL);
insert into Restaurant values(49, 'Glass Onion', 'British', '9, Blue Ridge Drive - Hayward', NULL);
insert into Restaurant values(50, 'Harley Food Center', 'Polish', '777, Rose Avenue - Cathedral City', NULL);
insert into Restaurant values(51, 'The French Laundry', 'Swedish', '375, Morrison Drive - Monroe', NULL);
insert into Restaurant values(52, 'Acadia', 'Swedish', '23, Wedgewood Drive - Chesapeake', NULL);
insert into Restaurant values(53, 'Sensory Experience', 'Creole', '556, Oxford Circle - Dallas', NULL);
insert into Restaurant values(54, 'Your Aesthetic', 'Happy Hour', '914, Orchard Lane - Norfolk', NULL);
insert into Restaurant values(55, 'Comfort Food', 'Family Fare', '739, Hunter Lane - Pembroke Pines', NULL);
insert into Restaurant values(56, 'Homemade Bagels', 'Bar', '59, Horseshoe Lane - New York', NULL);
insert into Restaurant values(57, 'Indian tulip', 'Spanish', '952, Woodbine Avenue - Reno', NULL);
insert into Restaurant values(58, 'Marea', 'Mexican', '912, Woodland Drive - Billings', NULL);
insert into Restaurant values(59, 'Fruce', 'Caribbean', '91, Windward Way - Fresno', NULL);
insert into Restaurant values(60, 'Finger Floyd', 'Portuguese', '279, Michigan Avenue - Fort Lauderdale', NULL);
insert into Restaurant values(61, 'Rice House', 'Cuban', '629, Shattuck Road - Philadelphia', NULL);
insert into Restaurant values(62, 'Carmine’s Italian Restaurant', 'Family Fare', '29, 18th Street East - Moreno Valley', NULL);
insert into Restaurant values(63, 'Prevent Fraud', 'Irish', '379, State Street - Reading', NULL);
insert into Restaurant values(64, 'Kokkari Estiatorio', 'Fast Food', '398, Sunset Road - Gainesville', NULL);
insert into Restaurant values(65, 'Jungsik', 'Spanish', '976, 9th Street West - Elizabeth', NULL);
insert into Restaurant values(66, 'Fred’s Tacos Corner', 'Japanese', '874, Pine Avenue - Springdale', NULL);
insert into Restaurant values(67, 'MadWings', 'Fine Dining', '974, Front Street North - Canton', NULL);
insert into Restaurant values(68, 'Spaghetti House', 'Cuban', '851, Abbey Court - Torrance', NULL);
insert into Restaurant values(69, 'Lalista', 'American', '313, 8th Street East - Pueblo', NULL);
insert into Restaurant values(70, 'Bateau', 'Bar', '493, Lawrence Street - Medford', NULL);
insert into Restaurant values(71, 'GW Fins', 'Burgers', '542, Oak Street - Las Vegas', NULL);
insert into Restaurant values(72, 'Goodnest', 'Sports Bar', '606, Jefferson Drive - Irving', NULL);
insert into Restaurant values(73, 'Glass Onion', 'Doughnuts', '358, Center Avenue - Cedar Rapids', NULL);
insert into Restaurant values(74, 'Frasca Food and Wine', 'Japanese', '88, 7th Street West - Honolulu', NULL);
insert into Restaurant values(75, 'Garden Of Eden', 'Hot Dogs', '15, Bank Street - Little Rock', NULL);
insert into Restaurant values(76, 'Service Supplied', 'British', '282, Brown Avenue - Cincinnati', NULL);
insert into Restaurant values(77, 'Dagny’s Delight', 'Family Fare', '413, 14th Street - Santa Barbara', NULL);
insert into Restaurant values(78, 'Joystick', 'Creole', '456, Cedar Drive - San Bernardino', NULL);
insert into Restaurant values(79, 'Pink Door', 'Tapas', '662, 2nd Street East - Naperville', NULL);
insert into Restaurant values(80, 'South', 'Latin American', '505, North Avenue - Las Vegas', NULL);
insert into Restaurant values(81, 'Taco Mayo', 'Ice Cream', '373, Morris Avenue - Elkhart', NULL);
insert into Restaurant values(82, 'Hill Crest', 'British', '154, Winterberry Lane - Salinas', NULL);
insert into Restaurant values(83, 'Fortune', 'Soul Food', '198, Court Street - Bryan', NULL);
insert into Restaurant values(84, 'Homemade Bagels', 'Irish', '313, Fox Run Drive - Worcester', NULL);
insert into Restaurant values(85, 'Crossroad Hotel', 'Ice Cream', '491, Moore Street - Erie', NULL);
insert into Restaurant values(86, 'Tall Oaks Café', 'Gluten-free', '130, Hanover Court - Waterbury', NULL);
insert into Restaurant values(87, 'Geronimo', 'Irish', '213, Bayberry Lane - Paterson', NULL);
insert into Restaurant values(88, 'Gather', 'Chinese', '399, Route 100 - Pensacola', NULL);
insert into Restaurant values(89, 'Eat Bite', 'Gluten-free', '795, Ocean Avenue - San Antonio', NULL);
insert into Restaurant values(90, 'It`s Vintage', 'Fine Dining', '904, Hawthorne Drive - Bethlehem', NULL);
insert into Restaurant values(91, 'Smokey’s Texas Grill', 'Fast Food', '662, 8th Avenue - Miami', NULL);
insert into Restaurant values(92, 'sketch', 'Vegan Friendly', '661, Woodland Road - Corpus Christi', NULL);
insert into Restaurant values(93, 'Chef Parade', 'Spanish', '211, Houston Street - Oklahoma City', NULL);
insert into Restaurant values(94, 'Ya', 'Soul Food', '97, College Avenue - Westminster', NULL);
insert into Restaurant values(95, 'Sugar Blast', 'Mexican', '303, 2nd Street North - Hampton', NULL);
insert into Restaurant values(96, 'Steelers', 'Live Entertainment', '771, Belmont Avenue - Hialeah', NULL);
insert into Restaurant values(97, 'Santa', 'Mediterranean', '603, Highland Drive - Columbia', NULL);
insert into Restaurant values(98, 'The Table', 'Brunch', '661, Union Street - Arlington', NULL);
insert into Restaurant values(99, 'Lalista', 'Spanish', '397, Park Street West - Fitchburg', NULL);
insert into Restaurant values(100, 'Service First', 'Sushi', '982, Queen Street - Denton', NULL);
insert into Restaurant values(101, 'Single Shot', 'Chinese', '122, Heather Road - Augusta', NULL);
insert into Restaurant values(102, 'Taco Mayo', 'Ice Cream', '210, Meadowbrook Road - Miramar', NULL);
insert into Restaurant values(103, 'Le Pigeon', 'Soul Food', '862, Palomino Drive - Santa Rosa', NULL);
insert into Restaurant values(104, 'Phuc Noodle', 'Sushi', '886, Garfield Avenue - Saint Petersburg', NULL);
insert into Restaurant values(105, 'The Lakhani', 'Vegetarian', '819, Canterbury Lane - Independence', NULL);
insert into Restaurant values(106, 'The Lazy Lemur', 'Country Food', '283, Canterbury Road - Newburgh', NULL);
insert into Restaurant values(107, 'ATOMIX', 'Deli', '969, Laura Lane - Hialeah', NULL);
insert into Restaurant values(108, 'Single Shot', 'Happy Hour', '522, Hudson Street - Havre de Grace', NULL);
insert into Restaurant values(109, 'Project Juice', 'Soup & Salad', '894, Lake Drive - Roanoke', NULL);
insert into Restaurant values(110, 'Glam Chilly', 'Waterfront', '555, Meadow Street - Tampa', NULL);
insert into Restaurant values(111, 'Pinch Kitchen', 'Deli', '307, River Road - Minneapolis', NULL);
insert into Restaurant values(112, 'Skydeck', 'Sushi', '442, 8th Street West - Deltona', NULL);
insert into Restaurant values(113, 'Sensory Experience', 'Barbeque', '322, Race Street - Hampton', NULL);
insert into Restaurant values(114, 'GW Fins', 'French', '359, Walnut Street North - Kenosha', NULL);
insert into Restaurant values(115, 'sketch', 'Mediterranean', '375, Constitution Drive - Sebastian', NULL);
insert into Restaurant values(116, 'Frasca Food and Wine', 'Thai', '987, Windsor Drive - College Station', NULL);
insert into Restaurant values(117, 'Club A Steakhouse', 'Brazilian', '830, Oak Lane - El Paso', NULL);
insert into Restaurant values(118, 'Punjabi', 'Doughnuts', '70, Regency Court - Springfield', NULL);
insert into Restaurant values(119, 'Skate And Stay', 'American', '171, New Jersey Avenue - Oxnard', NULL);
insert into Restaurant values(120, 'Mad Munch', 'Greek', '68, Village Drive - Des Moines', NULL);
insert into Restaurant values(121, 'Crossroad Hotel', 'Seafood', '534, Parkside Drive - Huntington Beach', NULL);
insert into Restaurant values(122, 'Mexx Restro', 'Brazilian', '518, 6th Street North - Nashville', NULL);
insert into Restaurant values(123, 'Sea Breeze', 'Barbeque', '378, Lafayette Avenue - Simi Valley', NULL);
insert into Restaurant values(124, 'Soul Food', 'Soup & Salad', '460, Lake Avenue - Thousand Oaks', NULL);
insert into Restaurant values(125, 'Niles', 'Greek', '338, Lakeview Court - Saint Petersburg', NULL);
insert into Restaurant values(126, 'Eleven Madison Park', 'Vegan Friendly', '341, Bank Street - New Orleans', NULL);
insert into Restaurant values(127, 'Sonic Drive-In', 'Vegetarian', '914, Euclid Avenue - Madison', NULL);
insert into Restaurant values(128, 'Revelry Bistro', 'Tapas', '531, Heather Court - Wilmington', NULL);
insert into Restaurant values(129, 'Portland', 'Thai', '471, Forest Lane - Huntington Beach', NULL);
insert into Restaurant values(130, 'Mad Munch', 'Portuguese', '761, Laura Lane - Mesquite', NULL);
insert into Restaurant values(131, 'Lalista', 'Country Food', '308, 8th Street - Grand Prairie', NULL);
insert into Restaurant values(132, 'Single Shot', 'Sandwiches', '907, Route 146 - Layton', NULL);
insert into Restaurant values(133, 'Mad Desi', 'Country Food', '964, Summit Avenue - Hialeah', NULL);
insert into Restaurant values(134, 'Mad Desi', 'Pizza', '464, Winterberry Lane - Norwalk', NULL);
insert into Restaurant values(135, 'Fish and Chips', 'Greek', '594, Jefferson Avenue - Bethlehem', NULL);
insert into Restaurant values(136, 'The Grey', 'Caribbean', '364, Village Drive - Fontana', NULL);
insert into Restaurant values(137, 'Double Knot', 'Soup & Salad', '461, Elizabeth Court - Medford', NULL);
insert into Restaurant values(138, 'Desi Addict', 'Sports Bar', '90, Forest Street - Lafayette', NULL);
insert into Restaurant values(139, 'Loving Monte', 'Tapas', '625, Briarwood Drive - Henderson', NULL);
insert into Restaurant values(140, 'Skillet Counter', 'Burgers', '428, Mechanic Street - Baltimore', NULL);
insert into Restaurant values(141, 'Sensory Experience', 'Food Trucks', '688, Douglas Avenue - Saginaw', NULL);
insert into Restaurant values(142, 'Spicy', 'Brazilian', '587, North Street East - South Lyon', NULL);
insert into Restaurant values(143, 'It`s Vintage', 'Pizza', '936, River Street - Port Orange', NULL);
insert into Restaurant values(144, 'Gather', 'Asian Fusion', '872, 9th Street West - Barnstable', NULL);
insert into Restaurant values(145, 'Upland', 'Bakery', '642, Lancaster Avenue - Leominster', NULL);
insert into Restaurant values(146, 'Maldives', 'German', '523, Forest Drive - Vancouver', NULL);
insert into Restaurant values(147, 'Double Knot', 'Spanish', '245, Driftwood Drive - Des Moines', NULL);
insert into Restaurant values(148, 'Spicy', 'American', '108, Wedgewood Drive - New York', NULL);
insert into Restaurant values(149, 'American Chinese', 'German', '167, Allen Lane - Vero Beach', NULL);
insert into Restaurant values(150, 'Pasta Beach', 'Happy Hour', '320, King Street - Elizabeth', NULL);
insert into Restaurant values(151, 'Clifton', 'Mexican', '996, Oak Street East - York', NULL);
insert into Restaurant values(152, 'Animal Restaurant', 'Cuban', '322, Smith Street - Tallahassee', NULL);
insert into Restaurant values(153, 'Geronimo', 'Polish', '465, Sunset Lane - Fresno', NULL);
insert into Restaurant values(154, 'Highlands Bar & Grill', 'Sushi', '882, Virginia Street - Elk Grove', NULL);
insert into Restaurant values(155, 'Oasis Cafe', 'Pancakes', '28, 2nd Street West - Clearwater', NULL);
insert into Restaurant values(156, 'Sotto', 'Japanese', '318, Cambridge Road - Worcester', NULL);
insert into Restaurant values(157, 'Morgan', 'Pizza', '807, Lewis Street - Abilene', NULL);
insert into Restaurant values(158, 'Portland', 'Vegan Friendly', '703, Western Avenue - Little Rock', NULL);
insert into Restaurant values(159, 'Jean-Georges', 'Live Entertainment', '558, Lee Street - Asheville', NULL);
insert into Restaurant values(160, 'Din Tai Fung', 'Family Fare', '344, Route 22 - North Las Vegas', NULL);
insert into Restaurant values(161, 'Six Seven Restaurant', 'Food Trucks', '88, Springhouse Lane - San Buenaventura', NULL);
insert into Restaurant values(162, 'Oasis Cafe', 'Ice Cream', '842, 5th Avenue - Pembroke Pines', NULL);
insert into Restaurant values(163, 'Parachute', 'Vegan Friendly', '194, Hamilton Street - Newport News', NULL);
insert into Restaurant values(164, 'Momofuku Ko', 'Cafe', '674, Sunset Avenue - Killeen', NULL);
insert into Restaurant values(165, 'GW Fins', 'Family Fare', '778, Prospect Street - Carrollton', NULL);
insert into Restaurant values(166, 'Jungle Drum', 'Pancakes', '631, Locust Lane - Des Moines', NULL);
insert into Restaurant values(167, 'Pink Door', 'German', '527, 10th Street West - San Francisco', NULL);
insert into Restaurant values(168, 'Tofino', 'Italian', '288, Route 30 - Stockton', NULL);
insert into Restaurant values(169, 'Frasca Food and Wine', 'Latin American', '733, Upland Road - Asheville', NULL);
insert into Restaurant values(170, 'Bateau', 'Ice Cream', '530, Meadow Lane - Glendale', NULL);
insert into Restaurant values(171, 'Quince', 'Pizza', '442, Skyline Drive - Garland', NULL);
insert into Restaurant values(172, 'The Grey', 'Cafe', '380, Hillside Avenue - Bethlehem', NULL);
insert into Restaurant values(173, 'Upland', 'Ice Cream', '831, Hastings Drive - McAllen', NULL);
insert into Restaurant values(174, 'Burger King', 'Japanese', '432, Dove Court - Grand Rapids', NULL);
insert into Restaurant values(175, 'Spaghetti House', 'Greek', '621, Central Avenue - Lake Charles', NULL);
insert into Restaurant values(176, 'Nacho', 'Bagels', '31, Heather Court - Fremont', NULL);
insert into Restaurant values(177, 'Pinch Kitchen', 'Barbeque', '443, Fieldstone Court - Worcester', NULL);
insert into Restaurant values(178, 'Desi Eatery', 'Seafood', '883, Maple Lane - Davidson County', NULL);
insert into Restaurant values(179, 'Elegance', 'Ice Cream', '897, Sherman Street - Saint Petersburg', NULL);
insert into Restaurant values(180, 'Steele', 'Greek', '39, Nottingham Lane - San Bernardino', NULL);
insert into Restaurant values(181, 'Eleven Madison Park', 'Soup & Salad', '234, 19th Street East - San Buenaventura', NULL);
insert into Restaurant values(182, 'Performance Dining', 'Portuguese', '583, Round Hill Road - Jersey City', NULL);
insert into Restaurant values(183, 'Loafers Hits', 'Soup & Salad', '636, 10th Street South - Thousand Oaks', NULL);
insert into Restaurant values(184, 'Desi Eatery', 'Pizza', '938, Welsh Road - Provo', NULL);
insert into Restaurant values(185, 'Max & More', 'Breakfast', '573, Route 16 - Lincoln', NULL);
insert into Restaurant values(186, 'Ya', 'Polish', '926, Railroad Street - Amarillo', NULL);
insert into Restaurant values(187, 'August', 'Brunch', '233, Hillside Lane - Moreno Valley', NULL);
insert into Restaurant values(188, 'Karachi Silver Spoon', 'Mediterranean', '463, Village Lane - Richmond', NULL);
insert into Restaurant values(189, 'Husk', 'Doughnuts', '660, Howard Street - Tuscaloosa', NULL);
insert into Restaurant values(190, 'Papa John’s', 'Swedish', '397, Bridle Lane - Riverside', NULL);
insert into Restaurant values(191, 'The Table', 'Swedish', '318, Turnberry Court - Killeen', NULL);
insert into Restaurant values(192, 'Nacho', 'Chinese', '43, Autumn Drive - San Bernardino', NULL);
insert into Restaurant values(193, 'Hurry Curry', 'Soup & Salad', '81, Buck Road - Fresno', NULL);
insert into Restaurant values(194, 'Steele', 'American', '802, Elm Avenue - Daytona Beach', NULL);
insert into Restaurant values(195, 'Sugar Blast', 'Sports Bar', '845, State Street East - Norwalk', NULL);
insert into Restaurant values(196, 'Steak House', 'Breakfast', '814, 9th Street - Manchester', NULL);
insert into Restaurant values(197, 'Service Supplied', 'Pizza', '948, 2nd Street West - Portland', NULL);
insert into Restaurant values(198, 'Coquine', 'Burgers', '279, Johnson Street - Wichita', NULL);
insert into Restaurant values(199, 'Sweet Escape', 'Chinese', '102, Spruce Lane - Denver', NULL);


insert into Dish values(0, 15, 'plate', 9, 'Polish', NULL);
insert into Dish values(1, 11, 'taste', 2, 'Deli', NULL);
insert into Dish values(2, 81, 'omelette', 5, 'Vegetarian', NULL);
insert into Dish values(3, 184, 'margarine', 34, 'Creole', NULL);
insert into Dish values(4, 163, 'sopapillas', 36, 'Sushi', NULL);
insert into Dish values(5, 85, 'queso', 35, 'Tapas', NULL);
insert into Dish values(6, 60, 'water', 18, 'Fast Food', NULL);
insert into Dish values(7, 73, 'paste', 25, 'Brunch', NULL);
insert into Dish values(8, 181, 'coffee', 34, 'Brazilian', NULL);
insert into Dish values(9, 157, 'bread', 33, 'Ice Cream', NULL);
insert into Dish values(10, 124, 'tea', 36, 'Gluten-free', NULL);
insert into Dish values(11, 56, 'soup', 16, 'Doughnuts', NULL);
insert into Dish values(12, 109, 'nut', 28, 'Doughnuts', NULL);
insert into Dish values(13, 16, 'broth', 4, 'French', NULL);
insert into Dish values(14, 9, 'mayo', 16, 'Japanese', NULL);
insert into Dish values(15, 33, 'soda', 32, 'Soul Food', NULL);
insert into Dish values(16, 137, 'glaze', 18, 'Brazilian', NULL);
insert into Dish values(17, 123, 'hamburger', 22, 'Bar', NULL);
insert into Dish values(18, 118, 'foie gras', 5, 'Family Fare', NULL);
insert into Dish values(19, 2, 'ice', 3, 'French', NULL);
insert into Dish values(20, 80, 'burrito', 28, 'Irish', NULL);
insert into Dish values(21, 147, 'cocoa', 17, 'Portuguese', NULL);
insert into Dish values(22, 142, 'queso', 22, 'Bakery', NULL);
insert into Dish values(23, 69, 'paste', 16, 'Pizza', NULL);
insert into Dish values(24, 176, 'raclette', 20, 'Seafood', NULL);
insert into Dish values(25, 142, 'filet', 19, 'Sushi', NULL);
insert into Dish values(26, 11, 'dish', 14, 'Soup & Salad', NULL);
insert into Dish values(27, 182, 'candy', 39, 'Steaks', NULL);
insert into Dish values(28, 107, 'queso', 27, 'Portuguese', NULL);
insert into Dish values(29, 33, 'sandwich', 15, 'Creole', NULL);
insert into Dish values(30, 47, 'syrup', 4, 'Country Food', NULL);
insert into Dish values(31, 60, 'recipe', 37, 'Doughnuts', NULL);
insert into Dish values(32, 11, 'taco', 30, 'Steaks', NULL);
insert into Dish values(33, 181, 'mayonnaise', 1, 'Barbeque', NULL);
insert into Dish values(34, 146, 'empanada', 2, 'Pizza', NULL);
insert into Dish values(35, 62, 'muffin', 34, 'Swedish', NULL);
insert into Dish values(36, 131, 'filet', 18, 'Indian', NULL);
insert into Dish values(37, 36, 'pasta', 18, 'Fine Dining', NULL);
insert into Dish values(38, 93, 'milk', 29, 'French', NULL);
insert into Dish values(39, 161, 'raclette', 38, 'Thai', NULL);
insert into Dish values(40, 56, 'pie', 31, 'Fast Food', NULL);
insert into Dish values(41, 142, 'foie gras', 20, 'Japanese', NULL);
insert into Dish values(42, 93, 'cider', 30, 'Cafe', NULL);
insert into Dish values(43, 70, 'candy', 3, 'Creole', NULL);
insert into Dish values(44, 111, 'chocolate', 33, 'Asian Fusion', NULL);
insert into Dish values(45, 130, 'croissant', 27, 'Cuban', NULL);
insert into Dish values(46, 125, 'marinade', 28, 'Live Entertainment', NULL);
insert into Dish values(47, 44, 'cream', 29, 'Barbeque', NULL);
insert into Dish values(48, 189, 'cake', 7, 'Bakery', NULL);
insert into Dish values(49, 87, 'dessert', 1, 'Portuguese', NULL);
insert into Dish values(50, 98, 'mayonnaise', 12, 'Sports Bar', NULL);
insert into Dish values(51, 150, 'cuisine', 12, 'Fast Food', NULL);
insert into Dish values(52, 27, 'cream', 4, 'Food Trucks', NULL);
insert into Dish values(53, 126, 'queso', 1, 'Portuguese', NULL);
insert into Dish values(54, 16, 'flour', 34, 'Seafood', NULL);
insert into Dish values(55, 151, 'chocolate', 1, 'Ice Cream', NULL);
insert into Dish values(56, 141, 'paste', 2, 'British', NULL);
insert into Dish values(57, 73, 'wheat', 1, 'Country Food', NULL);
insert into Dish values(58, 151, 'salad', 8, 'Fine Dining', NULL);
insert into Dish values(59, 45, 'oil', 18, 'Ice Cream', NULL);
insert into Dish values(60, 72, 'vinegar', 17, 'Cafe', NULL);
insert into Dish values(61, 186, 'seasoning', 39, 'Food Trucks', NULL);
insert into Dish values(62, 32, 'pastry', 12, 'Italian', NULL);
insert into Dish values(63, 3, 'sandwich', 7, 'Spanish', NULL);
insert into Dish values(64, 150, 'tea', 7, 'Cuban', NULL);
insert into Dish values(65, 122, 'pan', 7, 'Seafood', NULL);
insert into Dish values(66, 159, 'omelette', 39, 'Cafe', NULL);
insert into Dish values(67, 2, 'ice', 34, 'Bagels', NULL);
insert into Dish values(68, 1, 'chili', 23, 'British', NULL);
insert into Dish values(69, 117, 'pudding', 9, 'Brazilian', NULL);
insert into Dish values(70, 6, 'ice', 6, 'Brazilian', NULL);
insert into Dish values(71, 18, 'food', 14, 'Waterfront', NULL);
insert into Dish values(72, 102, 'cake', 13, 'Bar', NULL);
insert into Dish values(73, 115, 'taste', 33, 'Burgers', NULL);
insert into Dish values(74, 70, 'toast', 40, 'Bagels', NULL);
insert into Dish values(75, 150, 'omelette', 39, 'Sandwiches', NULL);
insert into Dish values(76, 49, 'milk', 4, 'Chinese', NULL);
insert into Dish values(77, 107, 'cheese', 32, 'Swedish', NULL);
insert into Dish values(78, 195, 'entree', 21, 'Deli', NULL);
insert into Dish values(79, 129, 'biscuit', 25, 'Brunch', NULL);
insert into Dish values(80, 31, 'caviar', 18, 'Happy Hour', NULL);
insert into Dish values(81, 57, 'pastry', 15, 'German', NULL);
insert into Dish values(82, 177, 'wine', 29, 'Pizza', NULL);
insert into Dish values(83, 84, 'salad', 27, 'Japanese', NULL);
insert into Dish values(84, 177, 'skillet', 24, 'Creole', NULL);
insert into Dish values(85, 100, 'sopapillas', 13, 'Family Fare', NULL);
insert into Dish values(86, 50, 'toast', 20, 'Bar', NULL);
insert into Dish values(87, 91, 'marinade', 39, 'Soup & Salad', NULL);
insert into Dish values(88, 188, 'lard', 2, 'Deli', NULL);
insert into Dish values(89, 147, 'cookie', 33, 'Vegan Friendly', NULL);
insert into Dish values(90, 104, 'entree', 36, 'Country Food', NULL);
insert into Dish values(91, 92, 'recipe', 6, 'British', NULL);
insert into Dish values(92, 86, 'foie gras', 14, 'Tapas', NULL);
insert into Dish values(93, 152, 'beer', 30, 'French', NULL);
insert into Dish values(94, 84, 'taste', 20, 'Greek', NULL);
insert into Dish values(95, 173, 'filet', 24, 'Family Fare', NULL);
insert into Dish values(96, 121, 'bagel', 38, 'Food Trucks', NULL);
insert into Dish values(97, 56, 'beer', 15, 'German', NULL);
insert into Dish values(98, 109, 'omelette', 29, 'Polish', NULL);
insert into Dish values(99, 33, 'cake', 13, 'Fast Food', NULL);
insert into Dish values(100, 191, 'recipe', 26, 'Ice Cream', NULL);
insert into Dish values(101, 4, 'caramel', 17, 'Sports Bar', NULL);
insert into Dish values(102, 188, 'cider', 11, 'Irish', NULL);
insert into Dish values(103, 196, 'poutine', 39, 'Fine Dining', NULL);
insert into Dish values(104, 143, 'seasoning', 26, 'Happy Hour', NULL);
insert into Dish values(105, 47, 'muffin', 33, 'Happy Hour', NULL);
insert into Dish values(106, 147, 'coffee', 26, 'Chinese', NULL);
insert into Dish values(107, 183, 'entree', 13, 'Fast Food', NULL);
insert into Dish values(108, 95, 'pie', 11, 'Family Fare', NULL);
insert into Dish values(109, 124, 'seasoning', 6, 'Bagels', NULL);
insert into Dish values(110, 50, 'salsa', 23, 'German', NULL);
insert into Dish values(111, 101, 'pudding', 24, 'Brazilian', NULL);
insert into Dish values(112, 62, 'mushroom', 8, 'Indian', NULL);
insert into Dish values(113, 34, 'pan', 26, 'Soup & Salad', NULL);
insert into Dish values(114, 159, 'syrup', 21, 'Cafe', NULL);
insert into Dish values(115, 6, 'taco', 33, 'Sports Bar', NULL);
insert into Dish values(116, 44, 'beer', 10, 'Seafood', NULL);
insert into Dish values(117, 124, 'steak', 24, 'Polish', NULL);
insert into Dish values(118, 51, 'chili', 38, 'Chinese', NULL);
insert into Dish values(119, 184, 'broth', 19, 'Polish', NULL);
insert into Dish values(120, 36, 'tostada', 7, 'Bagels', NULL);
insert into Dish values(121, 38, 'soup', 3, 'Swedish', NULL);
insert into Dish values(122, 29, 'dessert', 22, 'Sushi', NULL);
insert into Dish values(123, 105, 'nut', 32, 'Live Entertainment', NULL);
insert into Dish values(124, 15, 'wine', 28, 'Greek', NULL);
insert into Dish values(125, 139, 'burger', 12, 'Fine Dining', NULL);
insert into Dish values(126, 40, 'cider', 39, 'Bakery', NULL);
insert into Dish values(127, 105, 'food', 23, 'Brunch', NULL);
insert into Dish values(128, 152, 'queso', 27, 'Cafe', NULL);
insert into Dish values(129, 187, 'cream', 34, 'Cuban', NULL);
insert into Dish values(130, 181, 'caramel', 4, 'Bagels', NULL);
insert into Dish values(131, 197, 'cider', 3, 'Happy Hour', NULL);
insert into Dish values(132, 1, 'eggs', 36, 'Sushi', NULL);
insert into Dish values(133, 37, 'biscuit', 25, 'Steaks', NULL);
insert into Dish values(134, 32, 'glaze', 39, 'Barbeque', NULL);
insert into Dish values(135, 192, 'bread', 9, 'Creole', NULL);
insert into Dish values(136, 138, 'empanada', 36, 'Tapas', NULL);
insert into Dish values(137, 3, 'sauce', 16, 'Mediterranean', NULL);
insert into Dish values(138, 176, 'juice', 28, 'American', NULL);
insert into Dish values(139, 110, 'candy', 8, 'Steaks', NULL);
insert into Dish values(140, 174, 'burrito', 20, 'Sandwiches', NULL);
insert into Dish values(141, 84, 'fish', 16, 'Barbeque', NULL);
insert into Dish values(142, 23, 'noodle', 36, 'Vegetarian', NULL);
insert into Dish values(143, 3, 'curd', 21, 'Pancakes', NULL);
insert into Dish values(144, 191, 'meat', 34, 'Indian', NULL);
insert into Dish values(145, 128, 'foie gras', 34, 'Sports Bar', NULL);
insert into Dish values(146, 173, 'tartar', 8, 'Cuban', NULL);
insert into Dish values(147, 5, 'pan', 28, 'Waterfront', NULL);
insert into Dish values(148, 54, 'oil', 7, 'Ice Cream', NULL);
insert into Dish values(149, 54, 'entree', 30, 'Creole', NULL);
insert into Dish values(150, 71, 'skillet', 27, 'Happy Hour', NULL);
insert into Dish values(151, 130, 'syrup', 38, 'Soul Food', NULL);
insert into Dish values(152, 86, 'bread', 28, 'Italian', NULL);
insert into Dish values(153, 74, 'yeast', 7, 'Burgers', NULL);
insert into Dish values(154, 127, 'eggs', 12, 'Steaks', NULL);
insert into Dish values(155, 193, 'pudding', 6, 'Thai', NULL);
insert into Dish values(156, 186, 'batter', 29, 'Sports Bar', NULL);
insert into Dish values(157, 102, 'poutine', 3, 'Caribbean', NULL);
insert into Dish values(158, 51, 'tea', 9, 'Brunch', NULL);
insert into Dish values(159, 3, 'empanada', 26, 'Sandwiches', NULL);
insert into Dish values(160, 23, 'pot', 12, 'Spanish', NULL);
insert into Dish values(161, 22, 'cocoa', 22, 'Mediterranean', NULL);
insert into Dish values(162, 45, 'poutine', 5, 'Asian Fusion', NULL);
insert into Dish values(163, 19, 'cream', 9, 'Brunch', NULL);
insert into Dish values(164, 98, 'stew', 35, 'Waterfront', NULL);
insert into Dish values(165, 159, 'dish', 40, 'Asian Fusion', NULL);
insert into Dish values(166, 17, 'omelette', 19, 'Mexican', NULL);
insert into Dish values(167, 103, 'aroma', 30, 'Soup & Salad', NULL);
insert into Dish values(168, 46, 'juice', 33, 'Japanese', NULL);
insert into Dish values(169, 134, 'ketchup', 33, 'Country Food', NULL);
insert into Dish values(170, 179, 'filet', 7, 'Japanese', NULL);
insert into Dish values(171, 110, 'toast', 24, 'Country Food', NULL);
insert into Dish values(172, 153, 'chimichanga', 3, 'Brazilian', NULL);
insert into Dish values(173, 193, 'sandwich', 21, 'Pizza', NULL);
insert into Dish values(174, 61, 'soup', 39, 'Sushi', NULL);
insert into Dish values(175, 81, 'syrup', 9, 'American', NULL);
insert into Dish values(176, 75, 'poutine', 25, 'Bar', NULL);
insert into Dish values(177, 119, 'batter', 28, 'Gluten-free', NULL);
insert into Dish values(178, 182, 'tartar', 27, 'Swedish', NULL);
insert into Dish values(179, 32, 'juice', 37, 'Indian', NULL);
insert into Dish values(180, 137, 'cider', 33, 'Vegetarian', NULL);
insert into Dish values(181, 72, 'syrup', 26, 'Portuguese', NULL);
insert into Dish values(182, 122, 'seasoning', 25, 'British', NULL);
insert into Dish values(183, 164, 'foie gras', 12, 'Bagels', NULL);
insert into Dish values(184, 2, 'mushroom', 23, 'Barbeque', NULL);
insert into Dish values(185, 161, 'aroma', 31, 'Thai', NULL);
insert into Dish values(186, 3, 'soda', 19, 'Deli', NULL);
insert into Dish values(187, 79, 'food', 24, 'Vegetarian', NULL);
insert into Dish values(188, 32, 'pan', 35, 'British', NULL);
insert into Dish values(189, 5, 'food', 35, 'Gluten-free', NULL);
insert into Dish values(190, 134, 'caviar', 33, 'Steaks', NULL);
insert into Dish values(191, 54, 'yeast', 33, 'Bakery', NULL);
insert into Dish values(192, 52, 'cake', 25, 'Tapas', NULL);
insert into Dish values(193, 139, 'sopapillas', 31, 'Fast Food', NULL);
insert into Dish values(194, 143, 'soda', 35, 'Brazilian', NULL);
insert into Dish values(195, 163, 'tostada', 19, 'Vegan Friendly', NULL);
insert into Dish values(196, 111, 'yogurt', 21, 'Vegan Friendly', NULL);
insert into Dish values(197, 188, 'butter', 17, 'French', NULL);
insert into Dish values(198, 79, 'vinegar', 11, 'Brazilian', NULL);
insert into Dish values(199, 43, 'tostada', 13, 'Thai', NULL);
insert into Dish values(200, 176, 'cobbler', 14, 'Brazilian', NULL);
insert into Dish values(201, 196, 'hamburger', 11, 'Family Fare', NULL);
insert into Dish values(202, 145, 'dish', 7, 'Pancakes', NULL);
insert into Dish values(203, 145, 'omelette', 29, 'Vegan Friendly', NULL);
insert into Dish values(204, 143, 'taco', 10, 'Portuguese', NULL);
insert into Dish values(205, 24, 'nut', 4, 'Sandwiches', NULL);
insert into Dish values(206, 127, 'caviar', 26, 'Sports Bar', NULL);
insert into Dish values(207, 37, 'burrito', 12, 'Steaks', NULL);
insert into Dish values(208, 191, 'oil', 15, 'Polish', NULL);
insert into Dish values(209, 185, 'aroma', 14, 'Sports Bar', NULL);
insert into Dish values(210, 139, 'soda', 31, 'Portuguese', NULL);
insert into Dish values(211, 188, 'bread', 19, 'Creole', NULL);
insert into Dish values(212, 147, 'milk', 12, 'Sandwiches', NULL);
insert into Dish values(213, 106, 'mousse', 22, 'Bar', NULL);
insert into Dish values(214, 112, 'yogurt', 35, 'Mediterranean', NULL);
insert into Dish values(215, 166, 'glaze', 7, 'Breakfast', NULL);
insert into Dish values(216, 40, 'recipe', 17, 'Doughnuts', NULL);
insert into Dish values(217, 77, 'taco', 20, 'French', NULL);
insert into Dish values(218, 49, 'mayonnaise', 11, 'Doughnuts', NULL);
insert into Dish values(219, 166, 'grill', 15, 'Ice Cream', NULL);
insert into Dish values(220, 192, 'enchilada', 20, 'Cafe', NULL);
insert into Dish values(221, 21, 'recipe', 16, 'Soup & Salad', NULL);
insert into Dish values(222, 95, 'butter', 36, 'Latin American', NULL);
insert into Dish values(223, 121, 'steak', 22, 'French', NULL);
insert into Dish values(224, 132, 'bagel', 29, 'Tapas', NULL);
insert into Dish values(225, 115, 'cuisine', 23, 'Waterfront', NULL);
insert into Dish values(226, 38, 'syrup', 13, 'Bakery', NULL);
insert into Dish values(227, 45, 'stew', 26, 'Gluten-free', NULL);
insert into Dish values(228, 7, 'tartar', 32, 'Portuguese', NULL);
insert into Dish values(229, 118, 'chili', 16, 'French', NULL);
insert into Dish values(230, 145, 'toast', 20, 'Breakfast', NULL);
insert into Dish values(231, 187, 'beer', 12, 'Burgers', NULL);
insert into Dish values(232, 157, 'chimichanga', 20, 'Deli', NULL);
insert into Dish values(233, 127, 'recipe', 8, 'Japanese', NULL);
insert into Dish values(234, 129, 'marinade', 30, 'Vegan Friendly', NULL);
insert into Dish values(235, 158, 'dessert', 39, 'Latin American', NULL);
insert into Dish values(236, 198, 'mushroom', 1, 'Sushi', NULL);
insert into Dish values(237, 6, 'chili', 10, 'Soup & Salad', NULL);
insert into Dish values(238, 36, 'queso', 40, 'German', NULL);
insert into Dish values(239, 151, 'mushroom', 37, 'Sports Bar', NULL);
insert into Dish values(240, 9, 'meat', 23, 'Vegetarian', NULL);
insert into Dish values(241, 12, 'oil', 14, 'Fine Dining', NULL);
insert into Dish values(242, 19, 'ketchup', 10, 'Fast Food', NULL);
insert into Dish values(243, 122, 'nut', 26, 'Latin American', NULL);
insert into Dish values(244, 31, 'bagel', 27, 'Gluten-free', NULL);
insert into Dish values(245, 29, 'syrup', 5, 'Live Entertainment', NULL);
insert into Dish values(246, 98, 'soda', 35, 'Deli', NULL);
insert into Dish values(247, 126, 'sauce', 32, 'Sandwiches', NULL);
insert into Dish values(248, 156, 'chimichanga', 17, 'Cafe', NULL);
insert into Dish values(249, 142, 'empanada', 36, 'Seafood', NULL);
insert into Dish values(250, 2, 'empanada', 35, 'Seafood', NULL);
insert into Dish values(251, 85, 'muffin', 18, 'Food Trucks', NULL);
insert into Dish values(252, 17, 'food', 36, 'American', NULL);
insert into Dish values(253, 116, 'caviar', 20, 'Soul Food', NULL);
insert into Dish values(254, 192, 'recipe', 17, 'Japanese', NULL);
insert into Dish values(255, 80, 'oil', 22, 'Fine Dining', NULL);
insert into Dish values(256, 99, 'pastry', 17, 'Sandwiches', NULL);
insert into Dish values(257, 6, 'lard', 30, 'Pancakes', NULL);
insert into Dish values(258, 23, 'bread', 20, 'Family Fare', NULL);
insert into Dish values(259, 48, 'muffin', 38, 'Pizza', NULL);
insert into Dish values(260, 149, 'fish', 1, 'Creole', NULL);
insert into Dish values(261, 115, 'cookie', 28, 'Happy Hour', NULL);
insert into Dish values(262, 73, 'vinegar', 37, 'Soul Food', NULL);
insert into Dish values(263, 185, 'cookie', 36, 'Latin American', NULL);
insert into Dish values(264, 41, 'queso', 25, 'Steaks', NULL);
insert into Dish values(265, 133, 'pizza', 30, 'Cuban', NULL);
insert into Dish values(266, 143, 'beans', 25, 'Chinese', NULL);
insert into Dish values(267, 105, 'crumble', 18, 'Thai', NULL);
insert into Dish values(268, 61, 'cookie', 35, 'British', NULL);
insert into Dish values(269, 26, 'sauce', 19, 'Bakery', NULL);
insert into Dish values(270, 84, 'drink', 7, 'Chinese', NULL);
insert into Dish values(271, 125, 'muffin', 33, 'Gluten-free', NULL);
insert into Dish values(272, 88, 'poutine', 30, 'Bar', NULL);
insert into Dish values(273, 109, 'cookie', 20, 'Italian', NULL);
insert into Dish values(274, 149, 'waffle', 16, 'Pizza', NULL);
insert into Dish values(275, 177, 'chocolate', 39, 'Hot Dogs', NULL);
insert into Dish values(276, 53, 'ketchup', 27, 'Family Fare', NULL);
insert into Dish values(277, 142, 'kitchen', 2, 'Greek', NULL);
insert into Dish values(278, 115, 'batter', 6, 'Caribbean', NULL);
insert into Dish values(279, 182, 'wok', 6, 'Mexican', NULL);
insert into Dish values(280, 82, 'grill', 32, 'Brazilian', NULL);
insert into Dish values(281, 180, 'stew', 37, 'Soup & Salad', NULL);
insert into Dish values(282, 84, 'plate', 34, 'Steaks', NULL);
insert into Dish values(283, 29, 'biscuit', 1, 'Food Trucks', NULL);
insert into Dish values(284, 2, 'pie', 16, 'German', NULL);
insert into Dish values(285, 176, 'ketchup', 30, 'Hot Dogs', NULL);
insert into Dish values(286, 117, 'pasta', 7, 'Caribbean', NULL);
insert into Dish values(287, 179, 'beer', 5, 'Mexican', NULL);
insert into Dish values(288, 132, 'mayo', 8, 'Pancakes', NULL);
insert into Dish values(289, 20, 'soup', 27, 'Sushi', NULL);
insert into Dish values(290, 195, 'cuisine', 21, 'Cafe', NULL);
insert into Dish values(291, 10, 'dish', 13, 'Bar', NULL);
insert into Dish values(292, 8, 'soy', 9, 'Bagels', NULL);
insert into Dish values(293, 183, 'croissant', 2, 'Creole', NULL);
insert into Dish values(294, 67, 'yeast', 40, 'Bar', NULL);
insert into Dish values(295, 141, 'yeast', 37, 'Hot Dogs', NULL);
insert into Dish values(296, 3, 'pastry', 35, 'Live Entertainment', NULL);
insert into Dish values(297, 112, 'cheese', 25, 'Hot Dogs', NULL);
insert into Dish values(298, 68, 'pudding', 16, 'American', NULL);
insert into Dish values(299, 39, 'chimichanga', 14, 'Hot Dogs', NULL);
insert into Dish values(300, 44, 'plate', 16, 'Tapas', NULL);
insert into Dish values(301, 144, 'taco', 7, 'Creole', NULL);
insert into Dish values(302, 192, 'flour', 39, 'Food Trucks', NULL);
insert into Dish values(303, 14, 'entree', 12, 'German', NULL);
insert into Dish values(304, 66, 'grill', 31, 'Barbeque', NULL);
insert into Dish values(305, 175, 'water', 9, 'Caribbean', NULL);
insert into Dish values(306, 33, 'cake', 30, 'Happy Hour', NULL);
insert into Dish values(307, 197, 'entree', 22, 'Fast Food', NULL);
insert into Dish values(308, 112, 'poutine', 19, 'Barbeque', NULL);
insert into Dish values(309, 169, 'pasta', 30, 'Mexican', NULL);
insert into Dish values(310, 97, 'broth', 17, 'Burgers', NULL);
insert into Dish values(311, 130, 'croissant', 39, 'Mexican', NULL);
insert into Dish values(312, 158, 'skillet', 22, 'Asian Fusion', NULL);
insert into Dish values(313, 82, 'chocolate', 21, 'Polish', NULL);
insert into Dish values(314, 107, 'wine', 4, 'Vegan Friendly', NULL);
insert into Dish values(315, 123, 'kitchen', 27, 'American', NULL);
insert into Dish values(316, 79, 'olive', 37, 'Asian Fusion', NULL);
insert into Dish values(317, 182, 'drink', 9, 'Caribbean', NULL);
insert into Dish values(318, 130, 'burrito', 18, 'Breakfast', NULL);
insert into Dish values(319, 114, 'chimichanga', 4, 'Mediterranean', NULL);
insert into Dish values(320, 29, 'beans', 20, 'German', NULL);
insert into Dish values(321, 74, 'grill', 12, 'Bakery', NULL);
insert into Dish values(322, 58, 'kitchen', 23, 'Breakfast', NULL);
insert into Dish values(323, 199, 'curd', 22, 'Hot Dogs', NULL);
insert into Dish values(324, 20, 'ketchup', 5, 'Japanese', NULL);
insert into Dish values(325, 83, 'coffee', 18, 'Thai', NULL);
insert into Dish values(326, 105, 'liquor', 19, 'Tapas', NULL);
insert into Dish values(327, 24, 'raclette', 13, 'Asian Fusion', NULL);
insert into Dish values(328, 195, 'pudding', 29, 'Japanese', NULL);
insert into Dish values(329, 41, 'pizza', 16, 'Irish', NULL);
insert into Dish values(330, 101, 'pastry', 7, 'Indian', NULL);
insert into Dish values(331, 19, 'skillet', 11, 'Gluten-free', NULL);
insert into Dish values(332, 52, 'spice', 5, 'Seafood', NULL);
insert into Dish values(333, 122, 'cuisine', 11, 'Mexican', NULL);
insert into Dish values(334, 113, 'empanada', 6, 'Hot Dogs', NULL);
insert into Dish values(335, 181, 'caviar', 31, 'Sports Bar', NULL);
insert into Dish values(336, 163, 'tartar', 23, 'Greek', NULL);
insert into Dish values(337, 87, 'drink', 10, 'Italian', NULL);
insert into Dish values(338, 101, 'chimichanga', 22, 'Bar', NULL);
insert into Dish values(339, 146, 'coffee', 30, 'Seafood', NULL);
insert into Dish values(340, 78, 'candy', 14, 'Italian', NULL);
insert into Dish values(341, 67, 'plate', 20, 'Hot Dogs', NULL);
insert into Dish values(342, 19, 'nut', 6, 'Greek', NULL);
insert into Dish values(343, 179, 'bread', 24, 'Pancakes', NULL);
insert into Dish values(344, 53, 'wine', 17, 'Sandwiches', NULL);
insert into Dish values(345, 154, 'marinade', 15, 'Fast Food', NULL);
insert into Dish values(346, 181, 'rice', 11, 'Swedish', NULL);
insert into Dish values(347, 2, 'milk', 14, 'Swedish', NULL);
insert into Dish values(348, 126, 'foie gras', 14, 'Happy Hour', NULL);
insert into Dish values(349, 11, 'mousse', 38, 'Bakery', NULL);
insert into Dish values(350, 146, 'soup', 18, 'Sushi', NULL);
insert into Dish values(351, 25, 'queso', 24, 'Cafe', NULL);
insert into Dish values(352, 37, 'water', 7, 'Sandwiches', NULL);
insert into Dish values(353, 89, 'burrito', 28, 'Soul Food', NULL);
insert into Dish values(354, 63, 'yeast', 39, 'Indian', NULL);
insert into Dish values(355, 105, 'salad', 20, 'Polish', NULL);
insert into Dish values(356, 148, 'rice', 4, 'Fast Food', NULL);
insert into Dish values(357, 97, 'soup', 27, 'Indian', NULL);
insert into Dish values(358, 161, 'ketchup', 39, 'Barbeque', NULL);
insert into Dish values(359, 102, 'beer', 34, 'Cafe', NULL);
insert into Dish values(360, 36, 'plate', 26, 'Pizza', NULL);
insert into Dish values(361, 27, 'eggs', 36, 'American', NULL);
insert into Dish values(362, 42, 'muffin', 19, 'Thai', NULL);
insert into Dish values(363, 47, 'coffee', 4, 'Brazilian', NULL);
insert into Dish values(364, 174, 'taste', 11, 'Latin American', NULL);
insert into Dish values(365, 28, 'yeast', 10, 'Bar', NULL);
insert into Dish values(366, 89, 'wheat', 28, 'Spanish', NULL);
insert into Dish values(367, 184, 'cake', 25, 'Irish', NULL);
insert into Dish values(368, 164, 'cider', 14, 'Cafe', NULL);
insert into Dish values(369, 35, 'croissant', 20, 'Tapas', NULL);
insert into Dish values(370, 152, 'taco', 31, 'Brunch', NULL);
insert into Dish values(371, 13, 'taquito', 14, 'Polish', NULL);
insert into Dish values(372, 64, 'soy', 11, 'Chinese', NULL);
insert into Dish values(373, 82, 'caramel', 11, 'Mediterranean', NULL);
insert into Dish values(374, 58, 'salsa', 30, 'Irish', NULL);
insert into Dish values(375, 49, 'yogurt', 11, 'French', NULL);
insert into Dish values(376, 189, 'pot', 1, 'Family Fare', NULL);
insert into Dish values(377, 173, 'recipe', 24, 'German', NULL);
insert into Dish values(378, 110, 'taquito', 18, 'Barbeque', NULL);
insert into Dish values(379, 5, 'soda', 16, 'Latin American', NULL);
insert into Dish values(380, 90, 'tartar', 10, 'Fast Food', NULL);
insert into Dish values(381, 154, 'taste', 2, 'Fine Dining', NULL);
insert into Dish values(382, 150, 'lard', 4, 'Doughnuts', NULL);
insert into Dish values(383, 137, 'water', 27, 'Bar', NULL);
insert into Dish values(384, 95, 'entree', 25, 'Country Food', NULL);
insert into Dish values(385, 162, 'stew', 28, 'American', NULL);
insert into Dish values(386, 28, 'bagel', 27, 'Family Fare', NULL);
insert into Dish values(387, 31, 'dessert', 3, 'Vegan Friendly', NULL);
insert into Dish values(388, 116, 'tostada', 34, 'Spanish', NULL);
insert into Dish values(389, 102, 'dessert', 6, 'Irish', NULL);
insert into Dish values(390, 85, 'dish', 27, 'Bagels', NULL);
insert into Dish values(391, 186, 'cobbler', 26, 'Polish', NULL);
insert into Dish values(392, 179, 'water', 34, 'Gluten-free', NULL);
insert into Dish values(393, 190, 'croissant', 20, 'Sandwiches', NULL);
insert into Dish values(394, 53, 'olive', 5, 'Portuguese', NULL);
insert into Dish values(395, 140, 'stew', 7, 'Deli', NULL);
insert into Dish values(396, 32, 'mushroom', 21, 'Doughnuts', NULL);
insert into Dish values(397, 175, 'meat', 22, 'Pancakes', NULL);
insert into Dish values(398, 98, 'fish', 5, 'Doughnuts', NULL);
insert into Dish values(399, 112, 'cake', 10, 'Country Food', NULL);
insert into Dish values(400, 49, 'ketchup', 29, 'Sandwiches', NULL);
insert into Dish values(401, 143, 'queso', 21, 'Ice Cream', NULL);
insert into Dish values(402, 66, 'pizza', 24, 'Asian Fusion', NULL);
insert into Dish values(403, 71, 'sopapillas', 14, 'Brunch', NULL);
insert into Dish values(404, 33, 'bagel', 31, 'Burgers', NULL);
insert into Dish values(405, 186, 'margarine', 21, 'Spanish', NULL);
insert into Dish values(406, 135, 'vinegar', 11, 'Barbeque', NULL);
insert into Dish values(407, 188, 'chili', 25, 'Thai', NULL);
insert into Dish values(408, 101, 'salsa', 38, 'Swedish', NULL);
insert into Dish values(409, 123, 'cobbler', 22, 'Bagels', NULL);
insert into Dish values(410, 75, 'bread', 38, 'Live Entertainment', NULL);
insert into Dish values(411, 160, 'cake', 22, 'Pancakes', NULL);
insert into Dish values(412, 20, 'meat', 8, 'Bakery', NULL);
insert into Dish values(413, 91, 'entree', 24, 'Brazilian', NULL);
insert into Dish values(414, 181, 'cider', 11, 'Bar', NULL);
insert into Dish values(415, 177, 'ice', 40, 'Gluten-free', NULL);
insert into Dish values(416, 86, 'chimichanga', 15, 'Japanese', NULL);
insert into Dish values(417, 101, 'liquor', 19, 'Family Fare', NULL);
insert into Dish values(418, 4, 'pizza', 9, 'Brunch', NULL);
insert into Dish values(419, 112, 'curd', 7, 'Polish', NULL);
insert into Dish values(420, 62, 'salad', 35, 'Swedish', NULL);
insert into Dish values(421, 26, 'glaze', 7, 'Pizza', NULL);
insert into Dish values(422, 118, 'pan', 37, 'Live Entertainment', NULL);
insert into Dish values(423, 96, 'raclette', 14, 'Mexican', NULL);
insert into Dish values(424, 67, 'cream', 17, 'French', NULL);
insert into Dish values(425, 46, 'salsa', 32, 'Spanish', NULL);
insert into Dish values(426, 149, 'soy', 29, 'Irish', NULL);
insert into Dish values(427, 179, 'dish', 23, 'Gluten-free', NULL);
insert into Dish values(428, 107, 'broth', 33, 'Vegetarian', NULL);
insert into Dish values(429, 192, 'water', 21, 'Country Food', NULL);
insert into Dish values(430, 112, 'dessert', 32, 'Mexican', NULL);
insert into Dish values(431, 161, 'oil', 3, 'Creole', NULL);
insert into Dish values(432, 185, 'plate', 8, 'Steaks', NULL);
insert into Dish values(433, 183, 'pastry', 35, 'Bagels', NULL);
insert into Dish values(434, 59, 'soup', 23, 'Burgers', NULL);
insert into Dish values(435, 192, 'cobbler', 8, 'Indian', NULL);
insert into Dish values(436, 144, 'muffin', 28, 'Asian Fusion', NULL);
insert into Dish values(437, 23, 'spice', 15, 'Tapas', NULL);
insert into Dish values(438, 134, 'fish', 27, 'Fast Food', NULL);
insert into Dish values(439, 29, 'ketchup', 34, 'Pizza', NULL);
insert into Dish values(440, 103, 'butter', 11, 'Bakery', NULL);
insert into Dish values(441, 70, 'rice', 10, 'Brazilian', NULL);
insert into Dish values(442, 150, 'raclette', 40, 'Soup & Salad', NULL);
insert into Dish values(443, 152, 'broth', 13, 'Asian Fusion', NULL);
insert into Dish values(444, 69, 'soda', 14, 'Vegan Friendly', NULL);
insert into Dish values(445, 87, 'cream', 18, 'Family Fare', NULL);
insert into Dish values(446, 178, 'tartar', 31, 'Fast Food', NULL);
insert into Dish values(447, 8, 'caramel', 10, 'Waterfront', NULL);
insert into Dish values(448, 10, 'broth', 24, 'Polish', NULL);
insert into Dish values(449, 107, 'caramel', 19, 'Vegetarian', NULL);
insert into Dish values(450, 90, 'mushroom', 20, 'British', NULL);
insert into Dish values(451, 49, 'queso', 22, 'Brazilian', NULL);
insert into Dish values(452, 44, 'taco', 24, 'Live Entertainment', NULL);
insert into Dish values(453, 152, 'broth', 6, 'Sushi', NULL);
insert into Dish values(454, 8, 'wok', 29, 'Fast Food', NULL);
insert into Dish values(455, 169, 'marinade', 1, 'Italian', NULL);
insert into Dish values(456, 131, 'syrup', 34, 'Sushi', NULL);
insert into Dish values(457, 126, 'burrito', 39, 'Country Food', NULL);
insert into Dish values(458, 152, 'croissant', 39, 'Fast Food', NULL);
insert into Dish values(459, 37, 'tea', 36, 'Sports Bar', NULL);
insert into Dish values(460, 165, 'grill', 18, 'Fast Food', NULL);
insert into Dish values(461, 40, 'taquito', 16, 'Sports Bar', NULL);
insert into Dish values(462, 58, 'cider', 38, 'German', NULL);
insert into Dish values(463, 190, 'pot', 7, 'Sandwiches', NULL);
insert into Dish values(464, 83, 'bread', 17, 'Creole', NULL);
insert into Dish values(465, 18, 'pasta', 24, 'Tapas', NULL);
insert into Dish values(466, 139, 'beer', 23, 'Ice Cream', NULL);
insert into Dish values(467, 77, 'cookie', 3, 'Latin American', NULL);
insert into Dish values(468, 178, 'entree', 12, 'Vegetarian', NULL);
insert into Dish values(469, 117, 'sopapillas', 13, 'Vegan Friendly', NULL);
insert into Dish values(470, 173, 'kitchen', 12, 'Barbeque', NULL);
insert into Dish values(471, 27, 'yogurt', 11, 'Ice Cream', NULL);
insert into Dish values(472, 177, 'wine', 11, 'Waterfront', NULL);
insert into Dish values(473, 126, 'cream', 9, 'Cuban', NULL);
insert into Dish values(474, 93, 'drink', 9, 'Deli', NULL);
insert into Dish values(475, 23, 'entree', 5, 'Polish', NULL);
insert into Dish values(476, 14, 'sopapillas', 34, 'British', NULL);
insert into Dish values(477, 8, 'flour', 33, 'Italian', NULL);
insert into Dish values(478, 45, 'mousse', 31, 'Happy Hour', NULL);
insert into Dish values(479, 146, 'tostada', 5, 'Sushi', NULL);
insert into Dish values(480, 73, 'chili', 4, 'Polish', NULL);
insert into Dish values(481, 14, 'wok', 22, 'Caribbean', NULL);
insert into Dish values(482, 188, 'caviar', 25, 'Burgers', NULL);
insert into Dish values(483, 190, 'ice', 27, 'Indian', NULL);
insert into Dish values(484, 44, 'margarine', 23, 'Portuguese', NULL);
insert into Dish values(485, 176, 'pie', 18, 'Gluten-free', NULL);
insert into Dish values(486, 100, 'toast', 6, 'Sandwiches', NULL);
insert into Dish values(487, 126, 'crumble', 39, 'Creole', NULL);
insert into Dish values(488, 159, 'soda', 14, 'French', NULL);
insert into Dish values(489, 120, 'tostada', 12, 'Caribbean', NULL);
insert into Dish values(490, 16, 'steak', 32, 'Creole', NULL);
insert into Dish values(491, 188, 'caramel', 30, 'Tapas', NULL);
insert into Dish values(492, 199, 'nut', 23, 'Fine Dining', NULL);
insert into Dish values(493, 108, 'noodle', 16, 'Mexican', NULL);
insert into Dish values(494, 10, 'soup', 28, 'Barbeque', NULL);
insert into Dish values(495, 35, 'seasoning', 19, 'Greek', NULL);
insert into Dish values(496, 164, 'taco', 8, 'Mediterranean', NULL);
insert into Dish values(497, 51, 'empanada', 36, 'Bakery', NULL);
insert into Dish values(498, 62, 'eggs', 24, 'Caribbean', NULL);
insert into Dish values(499, 135, 'empanada', 27, 'Tapas', NULL);


insert into Restaurant_owner values(0, 197, 14);
insert into Restaurant_owner values(1, 37, 57);
insert into Restaurant_owner values(2, 144, 2);
insert into Restaurant_owner values(3, 73, 25);
insert into Restaurant_owner values(4, 155, 42);
insert into Restaurant_owner values(5, 8, 53);
insert into Restaurant_owner values(6, 76, 1);
insert into Restaurant_owner values(7, 198, 34);
insert into Restaurant_owner values(8, 180, 25);
insert into Restaurant_owner values(9, 6, 46);
insert into Restaurant_owner values(10, 34, 39);
insert into Restaurant_owner values(11, 2, 24);
insert into Restaurant_owner values(12, 125, 53);
insert into Restaurant_owner values(13, 12, 10);
insert into Restaurant_owner values(14, 157, 23);
insert into Restaurant_owner values(15, 39, 50);
insert into Restaurant_owner values(16, 117, 18);
insert into Restaurant_owner values(17, 133, 34);
insert into Restaurant_owner values(18, 89, 44);
insert into Restaurant_owner values(19, 121, 51);
insert into Restaurant_owner values(20, 181, 13);
insert into Restaurant_owner values(21, 97, 1);
insert into Restaurant_owner values(22, 40, 54);
insert into Restaurant_owner values(23, 168, 2);
insert into Restaurant_owner values(24, 100, 56);
insert into Restaurant_owner values(25, 6, 55);
insert into Restaurant_owner values(26, 173, 6);
insert into Restaurant_owner values(27, 53, 37);
insert into Restaurant_owner values(28, 130, 13);
insert into Restaurant_owner values(29, 144, 57);
insert into Restaurant_owner values(30, 199, 32);
insert into Restaurant_owner values(31, 64, 31);
insert into Restaurant_owner values(32, 118, 6);
insert into Restaurant_owner values(33, 54, 30);
insert into Restaurant_owner values(34, 168, 6);
insert into Restaurant_owner values(35, 149, 44);
insert into Restaurant_owner values(36, 181, 29);
insert into Restaurant_owner values(37, 34, 50);
insert into Restaurant_owner values(38, 58, 44);
insert into Restaurant_owner values(39, 153, 37);
insert into Restaurant_owner values(40, 49, 28);
insert into Restaurant_owner values(41, 176, 4);
insert into Restaurant_owner values(42, 197, 54);
insert into Restaurant_owner values(43, 48, 36);
insert into Restaurant_owner values(44, 40, 1);
insert into Restaurant_owner values(45, 150, 52);
insert into Restaurant_owner values(46, 52, 46);
insert into Restaurant_owner values(47, 104, 29);
insert into Restaurant_owner values(48, 131, 0);
insert into Restaurant_owner values(49, 104, 55);
insert into Restaurant_owner values(50, 150, 1);
insert into Restaurant_owner values(51, 87, 5);
insert into Restaurant_owner values(52, 132, 17);
insert into Restaurant_owner values(53, 56, 5);
insert into Restaurant_owner values(54, 126, 54);
insert into Restaurant_owner values(55, 149, 10);
insert into Restaurant_owner values(56, 2, 6);
insert into Restaurant_owner values(57, 140, 7);
insert into Restaurant_owner values(58, 112, 56);
insert into Restaurant_owner values(59, 111, 16);

COMMIT;