PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;

insert into User values(0, 'Nolan Hu', 'averageAimee99@chello.nl', 234666715, '765, Howard Avenue - Charleston', 'q3xawmtxDX', NULL);
insert into User values(1, 'Omar Craig', 'gorgeousMayra74@tin.it', 581776434, '156, Elm Avenue - Toledo', 'FmoDQsWR6H', NULL);
insert into User values(2, 'Shana Crabtree', 'inexpensiveDouglas66@neuf.fr', 421106974, '83, Clinton Avenue - Salt Lake City', 'GK4PCz9tKl', NULL);
insert into User values(3, 'Lara Baldwin', 'Theodorealive@sfr.fr', 243152562, '13, Roosevelt Avenue - San Jose', 'NodShllCDz', NULL);
insert into User values(4, 'Dane Miles', 'braveLevi@ymail.com', 562362261, '227, Devon Road - York', 'pdAql0QmX7', NULL);
insert into User values(5, 'Erick Joseph', 'Hollyhilarious@ntlworld.com', 121623672, '153, Willow Avenue - Long Beach', 'M5c1OOdoCa', NULL);
insert into User values(6, 'Rickey Fernandez', 'Stevenzealous@sfr.fr', 850623949, '454, Park Avenue - Hemet', 'KcWIKrmoDG', NULL);
insert into User values(7, 'Brittani Terry', 'puzzledDale58@wanadoo.fr', 215358792, '514, Aberdeen Drive - Cleveland', 'CYxwvXBdwT', NULL);
insert into User values(8, 'Jeremy Kane', 'mistyMelinda68@shaw.ca', 242117160, '878, Carolina Avenue - Lexington', 'sPIZqUnUhF', NULL);
insert into User values(9, 'Staci Freeman', 'determinedAlan@libero.it', 870844228, '220, Hawthorne Drive - Lewisville', 'AbShqVJSsv', NULL);
insert into User values(10, 'Sheila O''Neal', 'Claudiafamous@alice.it', 394601316, '225, Mercer Street - Salinas', 'BM13Y0QZVF', NULL);
insert into User values(11, 'Audrey Pugh', 'expensiveDarrell52@ymail.com', 763969582, '972, 13th Street West - Eugene', 'K52TDeprhz', NULL);
insert into User values(12, 'Maurice McCarthy', 'Hilarymotionless@juno.com', 785183431, '550, 6th Street South - Visalia', 'IXtPEU4mRa', NULL);
insert into User values(13, 'Antoinette Corbett', 'friendlyCourtney@shaw.ca', 892345439, '339, Washington Street West - Santa Ana', 'tulEMLDFzJ', NULL);
insert into User values(14, 'Tessa Vaughn', 'bloodyTerry@yahoo.com.mx', 812355800, '723, Chelsea Court - Hollywood', 'SHSv6IVTLi', NULL);
insert into User values(15, 'Rochelle Smith', 'cuteMeagan9@planet.nl', 715211663, '151, Colonial Court - Nashville', '58XdgeaLwc', NULL);
insert into User values(16, 'Thomas Levy', 'outrageousJaclyn@blueyonder.co.uk', 329379976, '170, Aberdeen Drive - Hayward', 'PMlia7V64j', NULL);
insert into User values(17, 'Tammy Field', 'Ianjoyous@orange.fr', 426197658, '197, Ferry Street - Austin', 'RySlhPRikF', NULL);
insert into User values(18, 'Alissa Franklin', 'Christyenchanting@msn.com', 840533241, '154, 6th Avenue - Arvada', 'l8Og94wx3q', NULL);
insert into User values(19, 'Deandre Kaplan', 'lazyHaley@mail.ru', 450920897, '801, Oak Road - Bloomington', 'QdpnrAXyxU', NULL);
insert into User values(20, 'Edgar Dalton', 'uptightSusan@telenet.be', 115770161, '210, Madison Court - Carrollton', 'VztssMv5md', NULL);
insert into User values(21, 'Shante Payne', 'Grantdoubtful@mac.com', 311396966, '868, Hamilton Road - Richmond', 'doUUlFBbMi', NULL);
insert into User values(22, 'Amelia Barry', 'arrogantEugene29@yahoo.com', 218958750, '73, Broadway - Chattanooga', 'Chta2QTEra', NULL);
insert into User values(23, 'Antoinette Hwang', 'zanyJulian@libero.it', 548193998, '575, Highland Court - Harlingen', 'eWcZfPLKLI', NULL);
insert into User values(24, 'Lynn Nicholson', 'motionlessNina35@arcor.de', 932285332, '189, Church Lane - Tacoma', '4oXAMPx8q5', NULL);
insert into User values(25, 'Latrice Woods', 'energeticJesus@hotmail.de', 399347488, '428, Cypress Drive - Santa Clarita', 'hu1h7RuFMu', NULL);
insert into User values(26, 'Michele Montgomery', 'jollyJeffery35@wanadoo.fr', 382919869, '651, McCarty Road - Fort Worth', 'YfTTWdy0oY', NULL);
insert into User values(27, 'Natalia Terrell', 'bewilderedJose@planet.nl', 420292261, '197, Andover Drive - Columbus', 'ZL6LjxZFEf', NULL);
insert into User values(28, 'Cedric Weeks', 'kindJanelle@virgilio.it', 696425658, '170, Northridge Drive - Wilmington', '2HFKSNDrOs', NULL);
insert into User values(29, 'Brittany Hester', 'filthyBruce@freenet.de', 149326211, '447, Church Road - Fairfield', 'gl8NQm9RrQ', NULL);
insert into User values(30, 'Daryl Bruce', 'Virginiareal@msn.com', 919367766, '385, Central Avenue - Marina', 'RQljzKXMLi', NULL);
insert into User values(31, 'Larissa Walsh', 'zanyJillian@chello.nl', 647549747, '135, Cambridge Road - Daytona Beach', '1aAoqF9mzq', NULL);
insert into User values(32, 'Guillermo Day', 'cuteHannah54@web.de', 538873197, '551, Hillcrest Road - Indianapolis', '2Zaj94cNFJ', NULL);
insert into User values(33, 'Ross Chu', 'charmingTracy@cox.net', 536458988, '655, Virginia Avenue - St. Petersburg', 'RQljzKXMLi', NULL);
insert into User values(34, 'Ruben Frost', 'fancyDevin55@bigpond.com', 920223916, '916, Applewood Drive - Billings', '2xbwHAHugC', NULL);
insert into User values(35, 'Hillary Orr', 'fancyDarrell@windstream.net', 493459816, '347, Heather Court - Washington', 'eeKqSkIM33', NULL);
insert into User values(36, 'Caitlin Byrne', 'motionlessSuzanne23@mac.com', 868827180, '66, Rose Street - Lakewood', 'MDtCdv8biG', NULL);
insert into User values(37, 'Ronnie Nolan', 'Stevenzealous@sfr.fr', 907582544, '355, Route 113 - Huntington Beach', '6sI9AX3ZV4', NULL);
insert into User values(38, 'Billy Hardy', 'Kristinealive@sbcglobal.net', 787919701, '701, Ash Street - Evansville', 'uMk6Sfp8Fk', NULL);
insert into User values(39, 'Gilberto Albright', 'alertAutumn9@blueyonder.co.uk', 308845542, '899, Vernon Avenue - Newburgh', 'kBvkNQtUBR', NULL);
insert into User values(40, 'Derek Massey', 'tameAlbert@juno.com', 602240318, '23, Cedar Drive - Poughkeepsie', '8A2kkdNptU', NULL);
insert into User values(41, 'Catherine Conner', 'realHector@charter.net', 337871846, '613, School Street - Abilene', 'eefSuYiiAE', NULL);
insert into User values(42, 'Shelby Goldstein', 'Gloriacute@yahoo.es', 378481815, '737, Buttonwood Lane - Appleton', 'VEENR78C0m', NULL);
insert into User values(43, 'Jerrod Young', 'Drewmotionless@msn.com', 624593213, '465, Morris Road - Danbury', 'wsIEHEBoCx', NULL);
insert into User values(44, 'Courtney Buckley', 'Erichelpful@rediffmail.com', 256383287, '100, Evergreen Drive - Vancouver', '7pLzbbBYbA', NULL);
insert into User values(45, 'Kate Weiss', 'smilingMelissa88@voila.fr', 935369396, '101, Westview Drive - Boise City', 'mcQjygq0XO', NULL);
insert into User values(46, 'Taylor Strauss', 'energeticCarlos43@hetnet.nl', 834733484, '819, George Street - Sarasota', 'rMfJC86eFa', NULL);
insert into User values(47, 'Alfred Choi', 'Caitlincruel@live.ca', 706425338, '60, 15th Street - Austin', 'elbaoXqF6F', NULL);
insert into User values(48, 'Clarence Sloan', 'longClinton@freenet.de', 911878293, '600, Pine Valley Drive - Toledo', 'sSTplrhzC0', NULL);
insert into User values(49, 'Preston Hancock', 'stormyMark@optusnet.com.au', 189699441, '328, Boxwood Drive - Daytona Beach', 'IhHdL2tUCW', NULL);
insert into User values(50, 'Britney Rich', 'thoughtfulCarolyn@terra.com.br', 546403750, '840, Winterberry Lane - Marysville', 'DSyIkBC12V', NULL);
insert into User values(51, 'Blair McKee', 'Tamarawicked@att.net', 515331565, '759, Brown Street - Rancho Cucamonga', 'sbWtb494jW', NULL);
insert into User values(52, 'Nickolas O''Neill', 'dangerousTina51@free.fr', 379980317, '251, Azalea Drive - Santa Clarita', 'Un8iXmUQAm', NULL);
insert into User values(53, 'Abel Phelps', 'Colinopen@windstream.net', 924407966, '764, Lakeshore Drive - Murfreesboro', 'zDdhsQ5rTC', NULL);
insert into User values(54, 'Marshall McLaughlin', 'Stevenbreakable@ig.com.br', 631621980, '972, Sycamore Drive - Yonkers', '2D5ITtrzJh', NULL);
insert into User values(55, 'Lori Young', 'aggressiveMiranda78@uol.com.br', 290946709, '630, Atlantic Avenue - Billings', 'YFMAGVkxa8', NULL);
insert into User values(56, 'Marshall Rollins', 'lazyHaley@mail.ru', 862528176, '243, Church Lane - Davidson County', 'd7gTs5dsH7', NULL);
insert into User values(57, 'Nelson Randall', 'Fernandocurious@aliceadsl.fr', 589792601, '919, 7th Avenue - Hayward', '8dkHzhbMA8', NULL);
insert into User values(58, 'Gregory McAllister', 'mushyValerie44@googlemail.com', 733682383, '365, Windsor Road - Abilene', '3CxBnZPvBd', NULL);
insert into User values(59, 'Tanisha Daniel', 'tenderBrittany@mail.com', 491333391, '203, 10th Street West - Abilene', 'lqM6Tdmcfb', NULL);

insert into Restaurant values(0, 'Miami', 'Bagels', '323, Woodbine Avenue - Norman', NULL);
insert into Restaurant values(1, 'The Spice', 'Fast Food', '78, Columbus Avenue - Dayton', NULL);
insert into Restaurant values(2, 'Indian Cuisine', 'Fine Dining', '849, Shattuck Road - Orlando', NULL);
insert into Restaurant values(3, 'Alabama', 'Latin American', '378, High Street - Irvine', NULL);
insert into Restaurant values(4, 'Sloppy Eats', 'Pancakes', '601, Market Street West - Kalamazoo', NULL);
insert into Restaurant values(5, 'Foreign Word', 'Cafe', '274, South Street - Barnstable', NULL);
insert into Restaurant values(6, 'Cafe Monarch', 'Swedish', '256, Route 15 - Newport News', NULL);
insert into Restaurant values(7, 'Max & More', 'Breakfast', '731, Hill Street - Kailua', NULL);
insert into Restaurant values(8, 'Benu', 'Italian', '926, Wisconsin Avenue - Long Beach', NULL);
insert into Restaurant values(9, 'Estela', 'Live Entertainment', '162, Lakeview Drive - Antioch', NULL);
insert into Restaurant values(10, 'Sea Spice', 'Seafood', '526, Sunset Lane - Athens', NULL);
insert into Restaurant values(11, 'Upland', 'American', '204, New Jersey Avenue - Redding', NULL);
insert into Restaurant values(12, 'Girl & The Goat', 'Swedish', '116, Glendale Road - Arlington', NULL);
insert into Restaurant values(13, 'Dagny’s Delight', 'Pizza', '168, Wayne Avenue - Richland', NULL);
insert into Restaurant values(14, 'Fred’s Tacos Corner', 'Hot Dogs', '728, Washington Lane - Howell', NULL);
insert into Restaurant values(15, 'Jungsik', 'Seafood', '346, Morningside Drive - High Point', NULL);
insert into Restaurant values(16, 'Rock and Roll cafe', 'Bagels', '261, Azalea Court - Toledo', NULL);
insert into Restaurant values(17, 'Acadia', 'Deli', '60, Juniper Drive - Lincoln', NULL);
insert into Restaurant values(18, 'Mad Munch', 'Polish', '280, Hastings Drive - Austin', NULL);
insert into Restaurant values(19, 'Niles', 'Spanish', '651, Route 4 - Garden Grove', NULL);
insert into Restaurant values(20, 'Rose’s Luxury', 'Swedish', '739, Union Street South - Chesapeake', NULL);
insert into Restaurant values(21, 'Agent Jack', 'Creole', '649, Route 25 - Coral Springs', NULL);
insert into Restaurant values(22, 'Spoon and Stable', 'Greek', '38, Laura Lane - Harlingen', NULL);
insert into Restaurant values(23, 'Clifton', 'Japanese', '733, Anderson Avenue - South Lyon', NULL);
insert into Restaurant values(24, 'Via Carota', 'Pancakes', '762, Chatham Court - Moreno Valley', NULL);
insert into Restaurant values(25, 'Pho Shizzle', 'Italian', '575, Court Street East - El Monte', NULL);
insert into Restaurant values(26, 'Fusion', 'Creole', '384, Cobblestone Court - Sioux Falls', NULL);
insert into Restaurant values(27, 'Joystick', 'Deli', '561, Buttonwood Drive - Newport News', NULL);
insert into Restaurant values(28, 'Evening Eve', 'Cuban', '917, Woodbine Avenue - San Bernardino', NULL);
insert into Restaurant values(29, 'Double Knot', 'Portuguese', '473, Laurel Court - Kissimmee', NULL);
insert into Restaurant values(30, 'Pink Door', 'Breakfast', '306, Olive Street - Milwaukee', NULL);
insert into Restaurant values(31, 'Benu', 'Irish', '403, Dale Road - Norwich', NULL);
insert into Restaurant values(32, 'Joystick', 'Happy Hour', '879, Oak Avenue - Colorado Springs', NULL);
insert into Restaurant values(33, 'Hollywood', 'Seafood', '92, Huntington Street - Des Moines', NULL);
insert into Restaurant values(34, 'Fun Circle Retro', 'Creole', '137, Route 10 - Boise', NULL);
insert into Restaurant values(35, 'Manresa', 'Sandwiches', '58, Wall Street - Grayslake', NULL);
insert into Restaurant values(36, 'Acadia', 'Pizza', '869, Fairway Drive - Des Moines', NULL);
insert into Restaurant values(37, 'Salted Grill', 'Ice Cream', '422, Church Street West - Baton Rouge', NULL);
insert into Restaurant values(38, 'Plumed Horse', 'Fast Food', '600, School Lane - Buffalo', NULL);
insert into Restaurant values(39, 'Spicy Dragon', 'Brazilian', '135, Northridge Drive - Birmingham', NULL);
insert into Restaurant values(40, 'Tanta', 'Mediterranean', '336, Willow Avenue - Thornton', NULL);
insert into Restaurant values(41, 'Maryland', 'Sushi', '8, Monroe Drive - Sterling Heights', NULL);
insert into Restaurant values(42, 'Rose’s Luxury', 'Asian Fusion', '81, 1st Street - Gastonia', NULL);
insert into Restaurant values(43, 'Cheesy Love', 'Ice Cream', '975, Morrison Drive - Thousand Oaks', NULL);
insert into Restaurant values(44, 'Alinea', 'Brazilian', '687, Route 16 - Pembroke Pines', NULL);
insert into Restaurant values(45, 'Veganic Corner', 'Soup & Salad', '211, Apple Street - Eugene', NULL);
insert into Restaurant values(46, 'South', 'American', '722, Washington Street East - Lacey', NULL);
insert into Restaurant values(47, 'Marine Room', 'German', '404, Argyle Road - Wilmington', NULL);
insert into Restaurant values(48, 'Pot Au Feu', 'Bakery', '119, Buttonwood Drive - Naples', NULL);
insert into Restaurant values(49, 'Jungle Drum', 'Fine Dining', '326, Smith Street - Scottsdale', NULL);
insert into Restaurant values(50, 'The Lazy Lemur', 'Hot Dogs', '540, Canterbury Road - Birmingham', NULL);
insert into Restaurant values(51, 'New Orleans', 'Pizza', '985, Locust Street - Santa Rosa', NULL);
insert into Restaurant values(52, 'Bateau', 'Chinese', '25, Overlook Circle - Gilbert', NULL);
insert into Restaurant values(53, 'Seven Hills', 'Doughnuts', '459, Juniper Drive - Fort Wayne', NULL);
insert into Restaurant values(54, 'Providence', 'Asian Fusion', '358, Arch Street - Indianapolis', NULL);
insert into Restaurant values(55, 'Montana', 'Soul Food', '329, Lakeside Drive - Odessa', NULL);
insert into Restaurant values(56, 'Los Angeles', 'Chinese', '418, Windsor Place - GreenBay', NULL);
insert into Restaurant values(57, 'Bliss mind', 'Seafood', '626, Bradley Street - Little Rock', NULL);
insert into Restaurant values(58, 'Rocco’s Cafe', 'Cafe', '149, Woodstream Drive - Jackson', NULL);
insert into Restaurant values(59, 'Tanta', 'Bar', '844, Fairview Drive - Yakima', NULL);
insert into Restaurant values(60, 'Rose’s Luxury', 'Bagels', '440, Wildflower Court - Visalia', NULL);
insert into Restaurant values(61, 'Spicy', 'Portuguese', '953, Pheasant Run - Round Lake Beach', NULL);
insert into Restaurant values(62, 'Quince', 'Vegetarian', '477, Evergreen Avenue - Eugene', NULL);
insert into Restaurant values(63, 'Tanta', 'Mediterranean', '21, Pine Lane - Las Cruces', NULL);
insert into Restaurant values(64, 'Masala', 'Fast Food', '940, Main Avenue - Chicago', NULL);
insert into Restaurant values(65, 'Upland', 'Deli', '143, Cottage Lane - Ontario', NULL);
insert into Restaurant values(66, 'Rebar', 'Soup & Salad', '215, Oak Street - Little Rock', NULL);
insert into Restaurant values(67, 'Faith Dining', 'Bagels', '486, Cherry Street - Yonkers', NULL);
insert into Restaurant values(68, 'Punjabi', 'Gluten-free', '523, Overlook Circle - Hialeah', NULL);
insert into Restaurant values(69, 'Comfort Food', 'Cuban', '65, Jones Street - San Antonio', NULL);
insert into Restaurant values(70, 'Seven Hills', 'Mediterranean', '904, Poplar Street - Santa Cruz', NULL);
insert into Restaurant values(71, 'Big Moe’s Diner', 'Brunch', '279, Seneca Street - Yakima', NULL);
insert into Restaurant values(72, 'ATOMIX', 'Bakery', '256, Windsor Place - Lorain', NULL);
insert into Restaurant values(73, 'Saison', 'Family Fare', '383, Wisteria Drive - Phoenix', NULL);
insert into Restaurant values(74, 'The Lazy Lemur', 'Soul Food', '183, Marshall Drive - Albany', NULL);
insert into Restaurant values(75, 'Clifton', 'Bakery', '15, Willow Way - Salinas', NULL);
insert into Restaurant values(76, 'Gluttony!', 'Bakery', '983, Circle Drive - Brownsville', NULL);
insert into Restaurant values(77, 'Serious Service', 'Ice Cream', '109, Chestnut Avenue - St. Louis', NULL);
insert into Restaurant values(78, 'Rocco’s Cafe', 'Swedish', '966, Durham Court - Dallas', NULL);
insert into Restaurant values(79, 'Elite Joy', 'Asian Fusion', '23, South Avenue - Mesa', NULL);
insert into Restaurant values(80, 'Mad Munch', 'Thai', '800, Rosewood Avenue - Mesa', NULL);
insert into Restaurant values(81, 'Addison Restaurant', 'Brunch', '129, Cross Street - Pomona', NULL);
insert into Restaurant values(82, 'FIG', 'Chinese', '964, Main Avenue - Tallahassee', NULL);
insert into Restaurant values(83, 'Le Coucou', 'Creole', '142, Bristol Road - Fremont', NULL);
insert into Restaurant values(84, 'Talula’s Garden', 'Greek', '0, 8th Street West - Des Moines', NULL);
insert into Restaurant values(85, 'Mad Desi', 'Pancakes', '608, River Road - Grayslake', NULL);
insert into Restaurant values(86, 'Performance Dining', 'Soul Food', '829, Colonial Court - Stockton', NULL);
insert into Restaurant values(87, 'Spicy Dragon', 'Fine Dining', '549, Roosevelt Avenue - Racine', NULL);
insert into Restaurant values(88, 'GW Fins', 'Sports Bar', '910, Hunters Run - Chattanooga', NULL);
insert into Restaurant values(89, 'Rusty Pelican', 'Seafood', '428, Route 27 - Burbank', NULL);
insert into Restaurant values(90, 'Alta', 'Mexican', '444, Ponderosa Drive - Hayward', NULL);
insert into Restaurant values(91, 'Awakening Coffeehouse', 'Cafe', '579, Robin Road - Cathedral City', NULL);
insert into Restaurant values(92, 'Pasta Beach', 'Soup & Salad', '266, Route 8 - Richland', NULL);
insert into Restaurant values(93, 'Perfect Setting', 'Sandwiches', '986, Lilac Lane - Oxnard', NULL);
insert into Restaurant values(94, 'Harry Potter', 'Cafe', '52, Cedar Lane - Plano', NULL);
insert into Restaurant values(95, 'Sea Spice', 'Spanish', '688, Meadow Street - Baton Rouge', NULL);
insert into Restaurant values(96, 'Restaurant Guy Savoy', 'French', '387, Heather Lane - Oceanside', NULL);
insert into Restaurant values(97, 'Dine Fine', 'Pizza', '595, Walnut Lane - Irvine', NULL);
insert into Restaurant values(98, 'Chef First', 'Bakery', '542, South Street - Downey', NULL);
insert into Restaurant values(99, 'Rose’s Luxury', 'Happy Hour', '637, Western Avenue - Hagerstown', NULL);
insert into Restaurant values(100, 'Rice House', 'Soup & Salad', '310, Lafayette Drive - Marina', NULL);
insert into Restaurant values(101, 'Fun Circle Retro', 'Sushi', '912, Coventry Court - Indianapolis', NULL);
insert into Restaurant values(102, 'Rhode Island', 'Mexican', '760, South Avenue - Denver', NULL);
insert into Restaurant values(103, 'Addison Restaurant', 'Polish', '194, North Avenue - Manchester', NULL);
insert into Restaurant values(104, 'Tavern', 'Steaks', '785, Woodland Street - Minneapolis', NULL);
insert into Restaurant values(105, 'Spicy Dragon', 'Spanish', '465, 2nd Street West - Denton', NULL);
insert into Restaurant values(106, 'Montana', 'Cafe', '150, Nottingham Drive - Marysville', NULL);
insert into Restaurant values(107, 'Sloppy Eats', 'Hot Dogs', '917, Adams Street - Ocala', NULL);
insert into Restaurant values(108, 'Melbourne', 'Barbeque', '143, Washington Lane - Knoxville', NULL);
insert into Restaurant values(109, 'Poke Life', 'British', '476, Victoria Court - Lake Charles', NULL);
insert into Restaurant values(110, 'Le Coucou', 'Soup & Salad', '651, Girard Avenue - Harrisburg', NULL);
insert into Restaurant values(111, 'Veganic Corner', 'German', '616, Carolina Avenue - El Monte', NULL);
insert into Restaurant values(112, 'Revelry Bistro', 'Bar', '295, Maiden Lane - Milwaukee', NULL);
insert into Restaurant values(113, 'Agent Jack', 'Latin American', '230, Park Avenue - West Covina', NULL);
insert into Restaurant values(114, 'Cafe Monarch', 'Sandwiches', '264, Arlington Avenue - Rockford', NULL);
insert into Restaurant values(115, 'Gather', 'Fine Dining', '811, Normandy Drive - Seaside', NULL);
insert into Restaurant values(116, 'Seven Hills', 'Indian', '513, Paddock Drive - Erie', NULL);
insert into Restaurant values(117, 'Dagny’s Delight', 'Caribbean', '856, Coventry Court - Grand Prairie', NULL);
insert into Restaurant values(118, 'Dagny’s Delight', 'Hot Dogs', '422, Elm Court - North Port', NULL);
insert into Restaurant values(119, 'Craft', 'Barbeque', '822, White Oak Road - Olympia', NULL);
insert into Restaurant values(120, 'Pho Shizzle', 'German', '893, 12th Street North - Odessa', NULL);
insert into Restaurant values(121, 'Queenstown Public House', 'Ice Cream', '251, Myrtle Street - Hialeah', NULL);
insert into Restaurant values(122, 'Sonic Drive-In', 'Thai', '700, Forest Street - Irving', NULL);
insert into Restaurant values(123, 'Miami', 'Swedish', '615, Oakwood Drive - Layton', NULL);
insert into Restaurant values(124, 'Quince', 'Thai', '840, Washington Street - Omaha', NULL);
insert into Restaurant values(125, 'Alta', 'Swedish', '244, Colonial Court - GreenBay', NULL);
insert into Restaurant values(126, 'Homemade Bagels', 'Food Trucks', '929, 12th Street North - Santa Barbara', NULL);
insert into Restaurant values(127, 'Ready Restaurants', 'Burgers', '955, Eastwood Drive - Gainesville', NULL);
insert into Restaurant values(128, 'Let’s Ambush', 'Chinese', '205, Hamilton Drive - Des Moines', NULL);
insert into Restaurant values(129, 'Alta', 'Hot Dogs', '385, Boxwood Drive - Salinas', NULL);
insert into Restaurant values(130, 'Finest Dining', 'Mediterranean', '502, Edgewood Drive - McHenry', NULL);
insert into Restaurant values(131, 'Homemade Bagels', 'Tapas', '743, David Drive - Waco', NULL);
insert into Restaurant values(132, 'Steakhouse', 'Burgers', '873, Tanglewood Lane - Bridgeport', NULL);
insert into Restaurant values(133, 'Ottawa', 'Cafe', '978, Vine Street - San Jose', NULL);
insert into Restaurant values(134, 'Ocean City', 'Burgers', '528, Chelsea Court - San Francisco', NULL);
insert into Restaurant values(135, 'Dagny’s Delight', 'German', '823, Brookside Drive - Monterey', NULL);
insert into Restaurant values(136, 'Pizzeria Cafe', 'Mexican', '880, Hamilton Avenue - Danbury', NULL);
insert into Restaurant values(137, 'Rose’s Luxury', 'Bar', '556, Sycamore Avenue - New London', NULL);
insert into Restaurant values(138, 'Godot', 'Happy Hour', '906, Clay Street - Cathedral City', NULL);
insert into Restaurant values(139, 'Pot Au Feu', 'Barbeque', '873, Kelly Drive - Montgomery', NULL);
insert into Restaurant values(140, 'Service Supplied', 'Bakery', '278, Oakwood Drive - Springdale', NULL);
insert into Restaurant values(141, 'French Gourmet', 'Indian', '994, Providence Road - Aberdeen', NULL);
insert into Restaurant values(142, 'Spoon and Stable', 'Brazilian', '348, Hidden Lake Drive - Hemet', NULL);
insert into Restaurant values(143, 'Oyster', 'Ice Cream', '455, Hunters Run - Richmond', NULL);
insert into Restaurant values(144, 'The Hungrella', 'Spanish', '735, Abbey Lane - Jackson', NULL);
insert into Restaurant values(145, 'Cheesy Love', 'Irish', '415, Wilson Drive - New Haven', NULL);
insert into Restaurant values(146, 'Finger Floyd', 'Tapas', '343, Willow Avenue - Oklahoma City', NULL);
insert into Restaurant values(147, 'Point', 'Food Trucks', '453, Route 25 - Stamford', NULL);
insert into Restaurant values(148, 'Faith Dining', 'Family Fare', '983, Victoria Court - Evansville', NULL);
insert into Restaurant values(149, 'Sotto', 'Mediterranean', '752, Sherwood Forest Drive - Carrollton', NULL);
insert into Restaurant values(150, 'Pho Shizzle', 'Caribbean', '73, Taylor Street - Fitchburg', NULL);
insert into Restaurant values(151, 'Tavern', 'Cafe', '748, Ohio Street - Anaheim', NULL);
insert into Restaurant values(152, 'Station', 'Family Fare', '183, Clinton Street - Knoxville', NULL);
insert into Restaurant values(153, 'Restaurant Guy Savoy', 'Cuban', '433, Horseshoe Lane - Lancaster', NULL);
insert into Restaurant values(154, 'Queenstown Public House', 'Cuban', '808, Grace Street - Long Beach', NULL);
insert into Restaurant values(155, 'Melbourne', 'Family Fare', '198, Holly Avenue - Macon', NULL);
insert into Restaurant values(156, 'Sloppy Eats', 'Mediterranean', '439, Lancaster Avenue - Lake Charles', NULL);
insert into Restaurant values(157, 'Addison Restaurant', 'Portuguese', '704, Chelsea Court - Norman', NULL);
insert into Restaurant values(158, 'Chili Flora', 'Gluten-free', '44, Andover Drive - Topeka', NULL);
insert into Restaurant values(159, 'Zahav', 'Italian', '979, May Street - Fort Collins', NULL);
insert into Restaurant values(160, 'Pink Door', 'British', '525, Woodland Road - Rockford', NULL);
insert into Restaurant values(161, 'Cheesy Love', 'Pizza', '775, William Street - Vancouver', NULL);
insert into Restaurant values(162, 'Faith Dining', 'Hot Dogs', '319, Seneca Street - Hialeah', NULL);
insert into Restaurant values(163, 'Momofuku Ko', 'Steaks', '105, Aspen Court - Portsmouth', NULL);
insert into Restaurant values(164, 'Cast Diners', 'French', '568, Sycamore Circle - Mesa', NULL);
insert into Restaurant values(165, 'Sweet Dreams', 'Bakery', '780, Cherry Street - Marina', NULL);
insert into Restaurant values(166, 'Goodnest', 'American', '621, Summit Drive - Allentown', NULL);
insert into Restaurant values(167, 'Charleston Grill', 'German', '131, Washington Street West - Lancaster', NULL);
insert into Restaurant values(168, 'Melisse Restaurant', 'Irish', '573, Mockingbird Lane - Hickory', NULL);
insert into Restaurant values(169, 'Royal', 'Soup & Salad', '660, Oakland Avenue - Las Vegas', NULL);
insert into Restaurant values(170, 'Mad Desi', 'Greek', '894, Arch Street - High Point', NULL);
insert into Restaurant values(171, 'French Gourmet', 'Mexican', '40, Park Place - Layton', NULL);
insert into Restaurant values(172, 'Recommended Restaurant', 'Fine Dining', '331, Ridgeview Drive - North Port', NULL);
insert into Restaurant values(173, 'Crossroad Hotel', 'Family Fare', '249, Rose Avenue - New Bedford', NULL);
insert into Restaurant values(174, 'Morgan', 'German', '196, Jackson Avenue - Bridgeport', NULL);
insert into Restaurant values(175, 'Sea Miracle', 'Japanese', '892, Central Avenue - Albuquerque', NULL);
insert into Restaurant values(176, 'Blue Valley', 'French', '517, 15th Street - Colorado Springs', NULL);
insert into Restaurant values(177, 'Happy evolve', 'Vegetarian', '121, Creek Road - Waterloo', NULL);
insert into Restaurant values(178, 'Blue Smoke', 'Japanese', '437, River Road - Des Moines', NULL);
insert into Restaurant values(179, 'Gabriel Kreuther', 'Pizza', '512, Windsor Way - Richland', NULL);
insert into Restaurant values(180, 'The Elephant and the Mouse', 'British', '328, Parkway Drive - St. Louis', NULL);
insert into Restaurant values(181, 'Street', 'Soul Food', '385, Constitution Drive - Akron', NULL);
insert into Restaurant values(182, 'Dorrance', 'Seafood', '406, College Avenue - Chattanooga', NULL);
insert into Restaurant values(183, 'Addison Restaurant', 'Indian', '770, Route 41 - West Covina', NULL);
insert into Restaurant values(184, 'Magic hands', 'Chinese', '370, Laurel Street - Hollywood', NULL);
insert into Restaurant values(185, 'French Gourmet', 'Country Food', '248, Cambridge Court - Santa Barbara', NULL);
insert into Restaurant values(186, 'Niles', 'Latin American', '487, Cottage Lane - San Buenaventura', NULL);
insert into Restaurant values(187, 'Gary Danko', 'Country Food', '689, Ridge Street - Vallejo', NULL);
insert into Restaurant values(188, 'Red Dragon', 'Bar', '36, Adams Avenue - Pensacola', NULL);
insert into Restaurant values(189, 'Perfect Setting', 'Ice Cream', '129, Lakeside Drive - Burlington', NULL);
insert into Restaurant values(190, 'Opera', 'Thai', '211, Sherwood Avenue - Palm Springs', NULL);
insert into Restaurant values(191, 'Spice Villa', 'Swedish', '302, Georgia Avenue - Riverside', NULL);
insert into Restaurant values(192, 'Rose’s Luxury', 'Seafood', '535, Oak Court - Tucson', NULL);
insert into Restaurant values(193, 'Libby', 'Italian', '460, Edgewood Avenue - Allentown', NULL);
insert into Restaurant values(194, '80’s Belt Burger', 'Burgers', '688, Park Avenue - Macon', NULL);
insert into Restaurant values(195, 'Pink Door', 'Soul Food', '65, Lafayette Drive - Syracuse', NULL);
insert into Restaurant values(196, 'Punjabi', 'Irish', '257, Augusta Drive - Modesto', NULL);
insert into Restaurant values(197, 'Tall Oaks Café', 'German', '245, Elm Street West - El Paso', NULL);
insert into Restaurant values(198, 'Single Shot', 'Vegetarian', '227, Elm Avenue - Brownsville', NULL);
insert into Restaurant values(199, 'Maldives', 'Cuban', '933, Route 22 - Las Cruces', NULL);

insert into Review values(0, 'In hac habitasse platea dictumst. Nam tristique dapibus dolor vel pellentesque. Duis venenatis pharetra dolor et aliquet. Maecenas nec finibus neque, non facilisis orci. Suspendisse malesuada imperdiet condimentum. Aenean nibh velit, aliquet in erat id, dictum luctus erat. Sed hendrerit massa dignissim tortor venenatis dapibus. Praesent pharetra euismod mi a pretium. Donec dignissim id odio vitae volutpat. Nullam finibus, leo a molestie volutpat, ipsum est vulputate urna, et luctus massa diam mattis massa. Aliquam iaculis malesuada dictum. Nullam at congue mi, ac accumsan mauris. Ut venenatis nec felis et maximus. Maecenas mattis libero eget nisi commodo malesuada. Curabitur tincidunt facilisis est ac suscipit. Curabitur dignissim massa a nisi posuere mattis.', 7, 99, 50);
insert into Review values(1, 'Fusce vel ultricies lacus. Nunc luctus ex ut nisl congue posuere. Integer placerat tincidunt mattis. Etiam non mi et purus iaculis varius et at elit. Fusce mollis dapibus fringilla. In ultrices vel odio ac posuere. Phasellus elementum arcu quis tortor dictum, et ultrices quam sagittis. Morbi diam dui, tristique in fermentum quis, porta a tortor. Aenean sed tincidunt dolor.', 9, 11, 11);
insert into Review values(2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce elementum neque justo, efficitur elementum nisl lobortis et. Etiam imperdiet mauris vel mauris sodales, sed aliquet sapien pulvinar. Pellentesque porttitor volutpat ex, in consequat ligula auctor non. Proin eu suscipit felis, eu cursus neque. Nullam bibendum sollicitudin quam, sed tempor ligula aliquam quis. Nullam in dolor ac nunc consectetur ornare. Vivamus quis sem neque.', 9, 27, 18);
insert into Review values(3, 'Pellentesque blandit, ipsum ut lobortis malesuada, nunc ante malesuada nisi, sit amet lobortis enim sem vitae dolor. Quisque bibendum consequat porta. Quisque hendrerit lacus sit amet sapien viverra pellentesque. Nunc vitae tempor neque, et fringilla diam. Vivamus viverra porttitor ipsum. Duis ultrices auctor molestie. Donec faucibus nisi ut volutpat placerat. Aenean ultricies dignissim nunc in ultricies. Vestibulum odio ex, eleifend at nisi sit amet, mattis convallis nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;', 4, 61, 22);
insert into Review values(4, 'Duis ut pretium justo. Suspendisse eget ante in risus aliquet finibus non et nisi. Etiam lobortis neque vel risus faucibus condimentum. Cras sem mi, sodales nec mauris quis, bibendum lacinia magna. Quisque pellentesque elit ut mollis maximus. Vivamus molestie facilisis enim vel congue. Proin nulla quam, aliquet vitae leo ac, interdum sollicitudin nisl. Cras imperdiet sagittis euismod.', 6, 172, 11);
insert into Review values(5, 'Ut a erat varius, ultricies leo a, sodales metus. Nulla mauris tellus, laoreet vitae elit ut, egestas condimentum eros. Quisque imperdiet sagittis tempor. Suspendisse id nulla enim. Duis vel elementum dolor. Pellentesque in hendrerit mi. Pellentesque aliquam elit et tellus dictum luctus. Donec scelerisque aliquam ligula vitae tincidunt. Fusce sit amet turpis vitae eros ultricies aliquet id vel est. Nullam risus tellus, posuere ullamcorper purus eget, porta elementum purus. In hac habitasse platea dictumst. In hac habitasse platea dictumst. In euismod purus condimentum lectus tincidunt blandit.', 8, 144, 28);
insert into Review values(6, 'Morbi non lorem vehicula quam interdum sollicitudin quis sed nunc. Integer consequat dignissim aliquet. Phasellus et mi augue. Vivamus sed tellus ut tellus consequat porttitor. Sed dignissim felis vitae dui auctor, eget laoreet arcu eleifend. Donec maximus tortor at augue suscipit sodales id a massa. Aliquam at dictum urna, id varius quam.', 8, 184, 45);
insert into Review values(7, 'Morbi neque mauris, aliquet vel purus vitae, tincidunt sodales lacus. Vestibulum egestas nisl fringilla dui gravida mollis. Sed sed tempor massa, ac blandit dui. Pellentesque sit amet ultrices mauris. Pellentesque consectetur ultricies volutpat. Nullam malesuada turpis quis ex suscipit tempus. In nec accumsan massa.', 4, 65, 26);
insert into Review values(8, 'Pellentesque iaculis leo et diam pharetra suscipit. Vivamus sollicitudin justo id elit bibendum suscipit id id velit. In congue vehicula ante, eu hendrerit turpis blandit non. Integer eu augue hendrerit, auctor quam eu, fringilla tellus. Nam scelerisque metus ipsum, ac dapibus ligula ultricies vel. Curabitur in vulputate arcu. Vivamus eu urna at mi molestie tincidunt non a neque. Sed accumsan pellentesque diam. Aenean pellentesque nisi eros, sed suscipit velit elementum et. Praesent convallis, nisl nec semper ultricies, erat odio porttitor purus, eget accumsan felis mi ut nibh. Nulla eleifend varius ipsum, eget venenatis lacus dignissim nec. Aenean efficitur nec enim in vulputate. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin risus sapien, aliquet sed malesuada non, molestie vulputate quam.', 4, 4, 7);
insert into Review values(9, 'Quisque pharetra non ex et tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla sit amet tortor varius metus cursus bibendum nec nec mi. In hac habitasse platea dictumst. Suspendisse potenti. Phasellus aliquet quam a felis facilisis, ut tempus magna sodales. Duis mollis dignissim augue, nec efficitur dolor pellentesque a. Phasellus viverra lectus lacus, vitae facilisis lectus auctor in. Quisque eget urna eu lacus eleifend convallis sit amet eu metus. Etiam nec dui enim. Vivamus justo metus, efficitur eget lorem vitae, auctor scelerisque neque.', 3, 178, 14);
insert into Review values(10, 'Nullam feugiat, arcu vitae finibus ullamcorper, nulla ligula viverra leo, semper aliquam ante urna in ligula. Aliquam tempor dolor eget nulla imperdiet, vitae interdum dui aliquam. Morbi vel dapibus nibh. Maecenas in congue neque. Pellentesque sollicitudin est libero, quis tempus arcu ultricies sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at nunc diam. Duis at justo pellentesque, posuere purus eget, vestibulum dui. Curabitur eget leo quis tortor iaculis euismod. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at sem sed diam convallis blandit. Aenean eget ipsum sollicitudin, fermentum lectus non, elementum lectus. Mauris lacinia ante ac mauris eleifend, et fermentum neque vestibulum. Ut vehicula lorem sit amet leo pretium, at consequat erat ornare. Integer quis imperdiet velit, commodo vehicula mauris. Donec justo eros, feugiat nec risus in, sagittis tempor sem.', 8, 114, 12);
insert into Review values(11, 'Pellentesque iaculis leo et diam pharetra suscipit. Vivamus sollicitudin justo id elit bibendum suscipit id id velit. In congue vehicula ante, eu hendrerit turpis blandit non. Integer eu augue hendrerit, auctor quam eu, fringilla tellus. Nam scelerisque metus ipsum, ac dapibus ligula ultricies vel. Curabitur in vulputate arcu. Vivamus eu urna at mi molestie tincidunt non a neque. Sed accumsan pellentesque diam. Aenean pellentesque nisi eros, sed suscipit velit elementum et. Praesent convallis, nisl nec semper ultricies, erat odio porttitor purus, eget accumsan felis mi ut nibh. Nulla eleifend varius ipsum, eget venenatis lacus dignissim nec. Aenean efficitur nec enim in vulputate. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin risus sapien, aliquet sed malesuada non, molestie vulputate quam.', 10, 34, 52);
insert into Review values(12, 'Nunc tempor a velit vitae commodo. Nulla ut risus arcu. Pellentesque efficitur imperdiet eros, nec volutpat justo blandit non. Donec vel lectus mollis justo tristique ornare. Nam mattis rhoncus elit, eget pharetra risus. Vivamus volutpat sodales purus, quis dictum lectus suscipit eget. Duis commodo urna metus, placerat pharetra sem gravida at.', 3, 81, 20);
insert into Review values(13, 'Donec sodales ex et eros lobortis elementum. Aliquam dui ante, sollicitudin a neque ut, fringilla cursus augue. Integer eu accumsan massa, at hendrerit arcu. Sed suscipit turpis eu sagittis consectetur. Curabitur non malesuada urna, nec porttitor augue. Sed venenatis lorem dolor, in faucibus lectus hendrerit ut. Vestibulum rutrum dolor urna, eget iaculis ante gravida sed.', 1, 57, 19);
insert into Review values(14, 'Morbi suscipit, dolor sit amet gravida sagittis, ex ante posuere diam, eget sollicitudin libero felis ut leo. Nunc euismod tincidunt vestibulum. Proin malesuada felis ut magna finibus, et posuere odio interdum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur lectus eros, maximus ut mauris imperdiet, consectetur semper metus. Sed suscipit venenatis mauris ac mollis. Suspendisse eget urna nec leo porta bibendum. Aliquam erat volutpat. In at pharetra nibh.', 6, 193, 23);
insert into Review values(15, 'Duis ut pretium justo. Suspendisse eget ante in risus aliquet finibus non et nisi. Etiam lobortis neque vel risus faucibus condimentum. Cras sem mi, sodales nec mauris quis, bibendum lacinia magna. Quisque pellentesque elit ut mollis maximus. Vivamus molestie facilisis enim vel congue. Proin nulla quam, aliquet vitae leo ac, interdum sollicitudin nisl. Cras imperdiet sagittis euismod.', 4, 156, 13);
insert into Review values(16, 'In convallis odio a lacus aliquam semper. Nullam faucibus id velit ut cursus. Aliquam tortor dolor, vulputate eget eros id, lacinia maximus dui. Maecenas luctus iaculis risus, sit amet sagittis velit fringilla ullamcorper. Cras efficitur congue odio. Duis id orci risus. Maecenas sem magna, ullamcorper et maximus in, rutrum eu augue. Praesent vitae tempor elit, ut accumsan augue. Praesent massa sapien, placerat quis pulvinar at, mattis sit amet lorem.', 7, 60, 20);
insert into Review values(17, 'Donec pellentesque lacinia dolor hendrerit varius. Pellentesque rutrum semper lacus, in dictum tortor lobortis id. Proin orci nibh, lobortis sed rutrum ac, ultricies ut risus. Fusce in lectus eget mi mattis ornare eu eget velit. Sed pulvinar tortor at ultricies posuere. Maecenas ornare, nunc vel elementum blandit, risus dolor convallis enim, ac molestie urna justo facilisis nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut tellus vitae lorem tempor suscipit.', 9, 3, 8);
insert into Review values(18, 'Donec et mi in velit auctor ornare pharetra ut tellus. In fermentum mauris vitae tempor pharetra. Pellentesque tincidunt tellus sit amet enim luctus pellentesque. Proin ut est elit. Duis at ligula faucibus nunc laoreet convallis. Proin blandit massa eu enim malesuada, a viverra velit dignissim. Etiam risus justo, dignissim vel rhoncus at, vulputate quis ligula. Mauris ante quam, luctus quis purus ac, porta semper nunc. Sed erat ligula, euismod sed auctor vel, vestibulum a nisi. Aenean bibendum, dolor eget efficitur tristique, eros purus mollis nulla, eget euismod nisi lectus ut libero. Fusce dapibus nibh ut risus consequat, id imperdiet orci lobortis. Duis sed iaculis sapien. Nulla vel neque nec lectus auctor commodo vel sit amet sem. Nam luctus diam augue, quis cursus est scelerisque id. Ut et urna maximus, efficitur est at, pharetra purus.', 1, 25, 1);
insert into Review values(19, 'Pellentesque dignissim, velit semper venenatis rutrum, ligula justo commodo dolor, vitae convallis elit ante eu sapien. Aliquam eget augue convallis, consectetur ligula ac, maximus felis. Aenean rhoncus ac tellus eu condimentum. Curabitur eleifend velit ex, at mollis dolor eleifend ut. Duis molestie dapibus orci, sed blandit tortor. Nam nec rhoncus lectus. Nullam porttitor diam id finibus lobortis. Donec at euismod odio. In ac porta orci. Nunc ut metus a purus mattis facilisis eget ac nibh. Morbi erat odio, sodales in libero eu, mollis scelerisque nisi. Fusce sed finibus magna. Sed hendrerit mollis mollis. Integer congue risus posuere, fermentum augue et, elementum urna.', 5, 27, 44);
insert into Review values(20, 'Vestibulum a tincidunt risus, at tempor lectus. Nulla finibus id ante quis ornare. Etiam mollis, libero et tristique interdum, sapien nisi venenatis metus, non varius ante nisi ac ante. In ligula dui, pulvinar quis justo ac, rutrum euismod est. Nullam facilisis pharetra ipsum, eget consequat risus dignissim sit amet. Suspendisse id ipsum a dolor facilisis tempus sollicitudin id neque. In fringilla libero dui, vitae dapibus enim sodales eget.', 7, 148, 35);
insert into Review values(21, 'Ut dignissim mauris ut ligula elementum condimentum. Pellentesque in sapien nec magna vehicula varius non at dui. Cras lacus dolor, malesuada quis sagittis nec, scelerisque sed urna. Fusce suscipit aliquam tortor, quis ornare odio bibendum quis. Mauris nisi diam, imperdiet non mattis et, ultrices lobortis libero. Quisque non nulla eu tortor finibus vestibulum sed semper dui. Vestibulum placerat erat et ante placerat aliquet.', 7, 3, 43);
insert into Review values(22, 'Ut quis viverra leo, et laoreet odio. Maecenas euismod leo at elit feugiat, vitae porta ante tempor. Integer egestas est id ligula luctus, ut egestas sapien finibus. Quisque dictum ex vitae ligula ornare, a bibendum orci semper. Proin ultrices mollis est id gravida. Nullam scelerisque volutpat felis. Integer congue mattis dolor vitae iaculis. Quisque ut ex at magna rhoncus ullamcorper nec in tortor.', 8, 63, 11);
insert into Review values(23, 'Sed sodales ex et urna scelerisque condimentum. Donec maximus ante eget magna sollicitudin sodales. Curabitur vitae ultricies lorem, ut fermentum mauris. Proin ut faucibus nunc. Maecenas tempor felis non tempus malesuada. In bibendum dolor id odio sodales gravida. Quisque id elit odio. Vivamus non orci lectus. Mauris ornare ipsum ac pulvinar tempor. Donec odio ipsum, vehicula ut semper ut, hendrerit in ligula. Aenean lobortis tristique libero, id congue justo. Ut gravida velit et ex imperdiet efficitur.', 10, 72, 5);
insert into Review values(24, 'Duis sit amet tristique ligula, et pellentesque sapien. Suspendisse eget rutrum tellus. Integer aliquet volutpat vulputate. Morbi sed augue aliquet, finibus erat fringilla, laoreet sem. Nullam rutrum nisi sed interdum commodo. Nullam ac pellentesque purus. Pellentesque sit amet mauris mauris.', 10, 136, 51);
insert into Review values(25, 'Nunc tempor a velit vitae commodo. Nulla ut risus arcu. Pellentesque efficitur imperdiet eros, nec volutpat justo blandit non. Donec vel lectus mollis justo tristique ornare. Nam mattis rhoncus elit, eget pharetra risus. Vivamus volutpat sodales purus, quis dictum lectus suscipit eget. Duis commodo urna metus, placerat pharetra sem gravida at.', 3, 64, 53);
insert into Review values(26, 'Morbi eleifend sapien luctus lorem malesuada ullamcorper. Sed sed fermentum dolor, in venenatis nibh. Pellentesque faucibus purus purus, quis sagittis augue tincidunt non. Suspendisse vel vulputate nibh, eget imperdiet massa. Sed a pellentesque urna, quis vestibulum metus. Nunc eget neque aliquam, luctus magna eget, accumsan mauris. Suspendisse pellentesque dignissim facilisis.', 9, 144, 39);
insert into Review values(27, 'Cras sed volutpat ligula. Morbi bibendum at risus non molestie. Morbi faucibus, nunc sagittis rutrum consectetur, purus neque accumsan magna, sed posuere purus nulla sit amet eros. Pellentesque non arcu rutrum, faucibus risus in, suscipit purus. Donec dolor lectus, volutpat eget sodales eget, vestibulum id elit. Sed hendrerit efficitur magna, ut tempus dui cursus ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed fermentum sagittis ipsum ac bibendum.', 5, 96, 34);
insert into Review values(28, 'Phasellus consequat suscipit diam, ac pretium turpis malesuada nec. Maecenas auctor varius dapibus. Donec laoreet felis sed venenatis dignissim. Curabitur tristique nibh est, ut cursus odio blandit ac. Praesent bibendum odio diam, nec pretium velit rutrum ut. In vel finibus sem. Praesent sit amet faucibus ante. Maecenas iaculis tristique egestas. Suspendisse ultricies malesuada dolor. In rhoncus quis augue ut luctus. Morbi consequat enim eu nisi imperdiet, non dignissim nunc sollicitudin. Morbi purus purus, malesuada vehicula euismod sed, efficitur eget velit. Nullam et fermentum purus, vitae facilisis purus. Curabitur vel tempus quam, id eleifend odio. Aliquam vel auctor sem, varius consectetur ex.', 6, 3, 53);
insert into Review values(29, 'Nulla facilisi. Sed tincidunt ipsum purus. Aliquam erat volutpat. Duis ut arcu in sapien eleifend gravida. Nunc imperdiet magna et lectus condimentum tincidunt. Quisque volutpat ligula vel lacus rhoncus, ac sagittis purus vehicula. Sed ultricies, libero eu pharetra egestas, libero orci dignissim velit, eget rhoncus nibh risus ac mauris. In nec metus non libero feugiat porttitor. Sed maximus erat non semper lobortis.', 7, 66, 32);

insert into Dish values(0, 172, 'cake', 20, 'Breakfast', NULL);
insert into Dish values(1, 186, 'pie', 27, 'Steaks', NULL);
insert into Dish values(2, 72, 'sandwich', 22, 'Barbeque', NULL);
insert into Dish values(3, 42, 'liquor', 10, 'Vegan Friendly', NULL);
insert into Dish values(4, 31, 'marinade', 7, 'Italian', NULL);
insert into Dish values(5, 29, 'syrup', 32, 'British', NULL);
insert into Dish values(6, 11, 'rice', 29, 'Sports Bar', NULL);
insert into Dish values(7, 0, 'butter', 12, 'Swedish', NULL);
insert into Dish values(8, 44, 'syrup', 19, 'Polish', NULL);
insert into Dish values(9, 105, 'taste', 20, 'British', NULL);
insert into Dish values(10, 60, 'enchilada', 27, 'Tapas', NULL);
insert into Dish values(11, 151, 'stew', 27, 'Breakfast', NULL);
insert into Dish values(12, 83, 'crumble', 21, 'Family Fare', NULL);
insert into Dish values(13, 18, 'rice', 14, 'Fine Dining', NULL);
insert into Dish values(14, 157, 'cobbler', 26, 'Caribbean', NULL);
insert into Dish values(15, 118, 'enchilada', 14, 'Seafood', NULL);
insert into Dish values(16, 25, 'pot', 17, 'Irish', NULL);
insert into Dish values(17, 105, 'oil', 10, 'American', NULL);
insert into Dish values(18, 118, 'croissant', 39, 'British', NULL);
insert into Dish values(19, 145, 'nut', 40, 'Deli', NULL);
insert into Dish values(20, 196, 'ice', 13, 'Tapas', NULL);
insert into Dish values(21, 134, 'chili', 23, 'Bagels', NULL);
insert into Dish values(22, 66, 'chimichanga', 28, 'Vegan Friendly', NULL);
insert into Dish values(23, 5, 'butter', 5, 'Irish', NULL);
insert into Dish values(24, 78, 'spice', 3, 'Asian Fusion', NULL);
insert into Dish values(25, 4, 'sandwich', 14, 'Fast Food', NULL);
insert into Dish values(26, 127, 'salad', 29, 'Italian', NULL);
insert into Dish values(27, 42, 'olive', 33, 'Caribbean', NULL);
insert into Dish values(28, 36, 'oil', 28, 'Irish', NULL);
insert into Dish values(29, 25, 'pizza', 29, 'Spanish', NULL);
insert into Dish values(30, 61, 'yogurt', 26, 'Latin American', NULL);
insert into Dish values(31, 78, 'plate', 3, 'Breakfast', NULL);
insert into Dish values(32, 107, 'salsa', 11, 'Latin American', NULL);
insert into Dish values(33, 70, 'pastry', 17, 'Gluten-free', NULL);
insert into Dish values(34, 112, 'chocolate', 28, 'Fast Food', NULL);
insert into Dish values(35, 170, 'milk', 5, 'Soup & Salad', NULL);
insert into Dish values(36, 32, 'liquor', 7, 'Fine Dining', NULL);
insert into Dish values(37, 162, 'plate', 28, 'Pancakes', NULL);
insert into Dish values(38, 56, 'mousse', 10, 'Portuguese', NULL);
insert into Dish values(39, 110, 'margarine', 14, 'Family Fare', NULL);
insert into Dish values(40, 180, 'broth', 35, 'Family Fare', NULL);
insert into Dish values(41, 169, 'taquito', 11, 'Caribbean', NULL);
insert into Dish values(42, 193, 'meat', 30, 'Pancakes', NULL);
insert into Dish values(43, 84, 'muffin', 29, 'Polish', NULL);
insert into Dish values(44, 100, 'taquito', 8, 'Sushi', NULL);
insert into Dish values(45, 16, 'biscuit', 25, 'Barbeque', NULL);
insert into Dish values(46, 127, 'pasta', 15, 'Spanish', NULL);
insert into Dish values(47, 2, 'nut', 32, 'Barbeque', NULL);
insert into Dish values(48, 81, 'chili', 1, 'Seafood', NULL);
insert into Dish values(49, 157, 'aroma', 29, 'Bagels', NULL);
insert into Dish values(50, 1, 'soup', 26, 'Fine Dining', NULL);
insert into Dish values(51, 117, 'foie gras', 3, 'Asian Fusion', NULL);
insert into Dish values(52, 195, 'taquito', 20, 'Brazilian', NULL);
insert into Dish values(53, 63, 'vinegar', 19, 'Cafe', NULL);
insert into Dish values(54, 82, 'pastry', 31, 'Mexican', NULL);
insert into Dish values(55, 71, 'caviar', 28, 'Spanish', NULL);
insert into Dish values(56, 125, 'oil', 31, 'Live Entertainment', NULL);
insert into Dish values(57, 129, 'caviar', 31, 'Gluten-free', NULL);
insert into Dish values(58, 22, 'entree', 40, 'Brazilian', NULL);
insert into Dish values(59, 10, 'oil', 6, 'Gluten-free', NULL);
insert into Dish values(60, 125, 'crumble', 33, 'Mediterranean', NULL);
insert into Dish values(61, 144, 'hamburger', 27, 'Bar', NULL);
insert into Dish values(62, 162, 'liquor', 35, 'German', NULL);
insert into Dish values(63, 3, 'chocolate', 33, 'Soul Food', NULL);
insert into Dish values(64, 199, 'sandwich', 2, 'Italian', NULL);
insert into Dish values(65, 166, 'cuisine', 18, 'Tapas', NULL);
insert into Dish values(66, 48, 'marinade', 10, 'Country Food', NULL);
insert into Dish values(67, 116, 'mayonnaise', 22, 'Food Trucks', NULL);
insert into Dish values(68, 68, 'pudding', 14, 'Fast Food', NULL);
insert into Dish values(69, 113, 'lard', 13, 'Bar', NULL);
insert into Dish values(70, 13, 'pasta', 35, 'American', NULL);
insert into Dish values(71, 69, 'pot', 27, 'Cuban', NULL);
insert into Dish values(72, 127, 'paste', 38, 'Sandwiches', NULL);
insert into Dish values(73, 162, 'tartar', 11, 'Brazilian', NULL);
insert into Dish values(74, 130, 'sauce', 1, 'Ice Cream', NULL);
insert into Dish values(75, 108, 'noodle', 11, 'Food Trucks', NULL);
insert into Dish values(76, 47, 'pie', 9, 'Japanese', NULL);
insert into Dish values(77, 86, 'cobbler', 12, 'Food Trucks', NULL);
insert into Dish values(78, 199, 'soda', 5, 'Vegan Friendly', NULL);
insert into Dish values(79, 49, 'candy', 14, 'Barbeque', NULL);
insert into Dish values(80, 39, 'chili', 27, 'Caribbean', NULL);
insert into Dish values(81, 58, 'lard', 9, 'Hot Dogs', NULL);
insert into Dish values(82, 147, 'yeast', 20, 'Soul Food', NULL);
insert into Dish values(83, 175, 'liquor', 35, 'Waterfront', NULL);
insert into Dish values(84, 40, 'mayonnaise', 32, 'Thai', NULL);
insert into Dish values(85, 50, 'chili', 28, 'Gluten-free', NULL);
insert into Dish values(86, 197, 'water', 34, 'Italian', NULL);
insert into Dish values(87, 71, 'croissant', 3, 'Pizza', NULL);
insert into Dish values(88, 66, 'food', 36, 'Sushi', NULL);
insert into Dish values(89, 124, 'syrup', 18, 'Caribbean', NULL);
insert into Dish values(90, 171, 'lard', 38, 'British', NULL);
insert into Dish values(91, 89, 'ketchup', 10, 'Pancakes', NULL);
insert into Dish values(92, 27, 'juice', 27, 'Vegan Friendly', NULL);
insert into Dish values(93, 20, 'cake', 34, 'Sushi', NULL);
insert into Dish values(94, 156, 'soup', 16, 'Country Food', NULL);
insert into Dish values(95, 67, 'queso', 24, 'Steaks', NULL);
insert into Dish values(96, 149, 'burrito', 6, 'Bakery', NULL);
insert into Dish values(97, 144, 'candy', 24, 'French', NULL);
insert into Dish values(98, 23, 'butter', 11, 'Mexican', NULL);
insert into Dish values(99, 165, 'chimichanga', 34, 'Doughnuts', NULL);
insert into Dish values(100, 45, 'nut', 10, 'Happy Hour', NULL);
insert into Dish values(101, 114, 'waffle', 11, 'Country Food', NULL);
insert into Dish values(102, 130, 'glaze', 27, 'Polish', NULL);
insert into Dish values(103, 164, 'eggs', 9, 'Bakery', NULL);
insert into Dish values(104, 108, 'pizza', 10, 'Swedish', NULL);
insert into Dish values(105, 160, 'soy', 22, 'Cafe', NULL);
insert into Dish values(106, 70, 'grill', 2, 'Asian Fusion', NULL);
insert into Dish values(107, 74, 'oil', 16, 'Tapas', NULL);
insert into Dish values(108, 164, 'crumble', 28, 'Vegan Friendly', NULL);
insert into Dish values(109, 51, 'poutine', 23, 'Bakery', NULL);
insert into Dish values(110, 80, 'marinade', 17, 'Burgers', NULL);
insert into Dish values(111, 127, 'candy', 2, 'Brazilian', NULL);
insert into Dish values(112, 157, 'pizza', 17, 'Fast Food', NULL);
insert into Dish values(113, 134, 'queso', 36, 'Fine Dining', NULL);
insert into Dish values(114, 27, 'beer', 24, 'Mexican', NULL);
insert into Dish values(115, 158, 'pastry', 19, 'Mexican', NULL);
insert into Dish values(116, 164, 'candy', 21, 'Barbeque', NULL);
insert into Dish values(117, 47, 'meat', 36, 'Fine Dining', NULL);
insert into Dish values(118, 96, 'yeast', 35, 'Bar', NULL);
insert into Dish values(119, 46, 'cider', 37, 'Pancakes', NULL);
insert into Dish values(120, 193, 'burrito', 29, 'Creole', NULL);
insert into Dish values(121, 109, 'kitchen', 36, 'Polish', NULL);
insert into Dish values(122, 185, 'tea', 13, 'Food Trucks', NULL);
insert into Dish values(123, 3, 'butter', 39, 'Spanish', NULL);
insert into Dish values(124, 6, 'sandwich', 3, 'Burgers', NULL);
insert into Dish values(125, 9, 'raclette', 32, 'Cafe', NULL);
insert into Dish values(126, 185, 'cobbler', 24, 'Indian', NULL);
insert into Dish values(127, 54, 'juice', 4, 'Italian', NULL);
insert into Dish values(128, 42, 'foie gras', 2, 'Brazilian', NULL);
insert into Dish values(129, 44, 'vinegar', 34, 'Cafe', NULL);
insert into Dish values(130, 51, 'salad', 24, 'Country Food', NULL);
insert into Dish values(131, 11, 'broth', 40, 'Brunch', NULL);
insert into Dish values(132, 99, 'taste', 1, 'Bakery', NULL);
insert into Dish values(133, 47, 'entree', 11, 'Barbeque', NULL);
insert into Dish values(134, 148, 'taste', 21, 'Chinese', NULL);
insert into Dish values(135, 59, 'recipe', 8, 'Indian', NULL);
insert into Dish values(136, 77, 'curd', 37, 'Family Fare', NULL);
insert into Dish values(137, 28, 'nut', 11, 'Seafood', NULL);
insert into Dish values(138, 44, 'pot', 7, 'Live Entertainment', NULL);
insert into Dish values(139, 53, 'soup', 34, 'Spanish', NULL);
insert into Dish values(140, 66, 'rice', 9, 'Bagels', NULL);
insert into Dish values(141, 22, 'cake', 5, 'Waterfront', NULL);
insert into Dish values(142, 16, 'margarine', 35, 'Deli', NULL);
insert into Dish values(143, 78, 'butter', 26, 'Sandwiches', NULL);
insert into Dish values(144, 109, 'butter', 22, 'Ice Cream', NULL);
insert into Dish values(145, 61, 'kitchen', 11, 'Happy Hour', NULL);
insert into Dish values(146, 45, 'tartar', 21, 'Happy Hour', NULL);
insert into Dish values(147, 57, 'eggs', 36, 'Creole', NULL);
insert into Dish values(148, 129, 'croissant', 15, 'Portuguese', NULL);
insert into Dish values(149, 144, 'skillet', 37, 'Italian', NULL);
insert into Dish values(150, 86, 'paste', 30, 'Caribbean', NULL);
insert into Dish values(151, 198, 'seasoning', 38, 'Country Food', NULL);
insert into Dish values(152, 126, 'ketchup', 7, 'Cafe', NULL);
insert into Dish values(153, 69, 'salad', 2, 'Bar', NULL);
insert into Dish values(154, 104, 'biscuit', 37, 'Swedish', NULL);
insert into Dish values(155, 192, 'skillet', 21, 'Seafood', NULL);
insert into Dish values(156, 98, 'meat', 38, 'Chinese', NULL);
insert into Dish values(157, 69, 'toast', 17, 'Brazilian', NULL);
insert into Dish values(158, 107, 'margarine', 1, 'Asian Fusion', NULL);
insert into Dish values(159, 123, 'pasta', 34, 'Bakery', NULL);
insert into Dish values(160, 80, 'bread', 4, 'Soup & Salad', NULL);
insert into Dish values(161, 139, 'ketchup', 26, 'French', NULL);
insert into Dish values(162, 82, 'tartar', 37, 'Polish', NULL);
insert into Dish values(163, 94, 'drink', 36, 'Brazilian', NULL);
insert into Dish values(164, 22, 'grill', 8, 'Food Trucks', NULL);
insert into Dish values(165, 89, 'queso', 5, 'Soup & Salad', NULL);
insert into Dish values(166, 91, 'mayonnaise', 27, 'German', NULL);
insert into Dish values(167, 183, 'dish', 18, 'Waterfront', NULL);
insert into Dish values(168, 72, 'sandwich', 31, 'Asian Fusion', NULL);
insert into Dish values(169, 113, 'yogurt', 37, 'Sushi', NULL);
insert into Dish values(170, 26, 'spice', 11, 'Barbeque', NULL);
insert into Dish values(171, 146, 'sopapillas', 32, 'Cuban', NULL);
insert into Dish values(172, 10, 'crumble', 20, 'Thai', NULL);
insert into Dish values(173, 20, 'plate', 11, 'Bakery', NULL);
insert into Dish values(174, 96, 'sauce', 33, 'Fine Dining', NULL);
insert into Dish values(175, 75, 'batter', 16, 'Polish', NULL);
insert into Dish values(176, 46, 'paste', 6, 'Live Entertainment', NULL);
insert into Dish values(177, 187, 'food', 33, 'Pancakes', NULL);
insert into Dish values(178, 50, 'tostada', 15, 'Mexican', NULL);
insert into Dish values(179, 99, 'sandwich', 34, 'Breakfast', NULL);
insert into Dish values(180, 92, 'pizza', 40, 'Sandwiches', NULL);
insert into Dish values(181, 88, 'cuisine', 11, 'Creole', NULL);
insert into Dish values(182, 76, 'wine', 39, 'Polish', NULL);
insert into Dish values(183, 198, 'candy', 29, 'Indian', NULL);
insert into Dish values(184, 148, 'food', 21, 'Ice Cream', NULL);
insert into Dish values(185, 111, 'pasta', 23, 'Ice Cream', NULL);
insert into Dish values(186, 178, 'broth', 11, 'Family Fare', NULL);
insert into Dish values(187, 127, 'paste', 12, 'Waterfront', NULL);
insert into Dish values(188, 26, 'taquito', 27, 'Vegetarian', NULL);
insert into Dish values(189, 146, 'taste', 38, 'American', NULL);
insert into Dish values(190, 64, 'burrito', 8, 'Soul Food', NULL);
insert into Dish values(191, 66, 'pie', 40, 'Pancakes', NULL);
insert into Dish values(192, 160, 'caviar', 6, 'Ice Cream', NULL);
insert into Dish values(193, 31, 'omelette', 23, 'Barbeque', NULL);
insert into Dish values(194, 97, 'wheat', 27, 'Bagels', NULL);
insert into Dish values(195, 22, 'stew', 38, 'Hot Dogs', NULL);
insert into Dish values(196, 71, 'eggs', 40, 'Doughnuts', NULL);
insert into Dish values(197, 106, 'coffee', 33, 'Hot Dogs', NULL);
insert into Dish values(198, 199, 'glaze', 36, 'Family Fare', NULL);
insert into Dish values(199, 45, 'bread', 19, 'Happy Hour', NULL);
insert into Dish values(200, 131, 'sopapillas', 25, 'Hot Dogs', NULL);
insert into Dish values(201, 148, 'milk', 16, 'Seafood', NULL);
insert into Dish values(202, 25, 'food', 7, 'Seafood', NULL);
insert into Dish values(203, 163, 'pudding', 2, 'Soup & Salad', NULL);
insert into Dish values(204, 171, 'rice', 6, 'Portuguese', NULL);
insert into Dish values(205, 26, 'noodle', 26, 'Fast Food', NULL);
insert into Dish values(206, 69, 'sauce', 2, 'Sushi', NULL);
insert into Dish values(207, 113, 'salad', 8, 'Soup & Salad', NULL);
insert into Dish values(208, 77, 'mayo', 8, 'Gluten-free', NULL);
insert into Dish values(209, 167, 'grill', 1, 'Bagels', NULL);
insert into Dish values(210, 23, 'tostada', 27, 'Deli', NULL);
insert into Dish values(211, 198, 'plate', 13, 'Sushi', NULL);
insert into Dish values(212, 22, 'olive', 12, 'Irish', NULL);
insert into Dish values(213, 165, 'pastry', 10, 'Pizza', NULL);
insert into Dish values(214, 47, 'taquito', 1, 'Happy Hour', NULL);
insert into Dish values(215, 8, 'enchilada', 27, 'Creole', NULL);
insert into Dish values(216, 132, 'wheat', 28, 'Breakfast', NULL);
insert into Dish values(217, 35, 'lard', 29, 'Doughnuts', NULL);
insert into Dish values(218, 172, 'beer', 23, 'Polish', NULL);
insert into Dish values(219, 15, 'recipe', 1, 'Thai', NULL);
insert into Dish values(220, 36, 'oil', 8, 'Fast Food', NULL);
insert into Dish values(221, 76, 'caramel', 1, 'Vegetarian', NULL);
insert into Dish values(222, 106, 'croissant', 18, 'Indian', NULL);
insert into Dish values(223, 161, 'seasoning', 36, 'Swedish', NULL);
insert into Dish values(224, 72, 'taco', 10, 'Hot Dogs', NULL);
insert into Dish values(225, 42, 'pie', 11, 'German', NULL);
insert into Dish values(226, 5, 'foie gras', 39, 'Swedish', NULL);
insert into Dish values(227, 91, 'entree', 25, 'Family Fare', NULL);
insert into Dish values(228, 89, 'cheese', 26, 'Indian', NULL);
insert into Dish values(229, 87, 'yogurt', 17, 'Seafood', NULL);
insert into Dish values(230, 177, 'ketchup', 31, 'British', NULL);
insert into Dish values(231, 155, 'dish', 7, 'German', NULL);
insert into Dish values(232, 1, 'oil', 27, 'Gluten-free', NULL);
insert into Dish values(233, 51, 'mayonnaise', 2, 'Seafood', NULL);
insert into Dish values(234, 73, 'water', 4, 'Polish', NULL);
insert into Dish values(235, 69, 'toast', 13, 'Breakfast', NULL);
insert into Dish values(236, 7, 'wok', 23, 'Pizza', NULL);
insert into Dish values(237, 98, 'stew', 22, 'Vegetarian', NULL);
insert into Dish values(238, 136, 'yogurt', 6, 'Spanish', NULL);
insert into Dish values(239, 86, 'milk', 23, 'Country Food', NULL);
insert into Dish values(240, 22, 'tartar', 24, 'Gluten-free', NULL);
insert into Dish values(241, 26, 'yogurt', 38, 'Fast Food', NULL);
insert into Dish values(242, 139, 'food', 9, 'Brazilian', NULL);
insert into Dish values(243, 177, 'filet', 1, 'Italian', NULL);
insert into Dish values(244, 20, 'lard', 34, 'Hot Dogs', NULL);
insert into Dish values(245, 106, 'ketchup', 22, 'Brazilian', NULL);
insert into Dish values(246, 73, 'burrito', 10, 'Polish', NULL);
insert into Dish values(247, 164, 'taste', 7, 'Live Entertainment', NULL);
insert into Dish values(248, 154, 'salsa', 38, 'Family Fare', NULL);
insert into Dish values(249, 85, 'biscuit', 16, 'Steaks', NULL);
insert into Dish values(250, 82, 'caramel', 30, 'Live Entertainment', NULL);
insert into Dish values(251, 103, 'rice', 5, 'Ice Cream', NULL);
insert into Dish values(252, 12, 'soy', 22, 'Swedish', NULL);
insert into Dish values(253, 3, 'beans', 26, 'Live Entertainment', NULL);
insert into Dish values(254, 92, 'sopapillas', 16, 'Cuban', NULL);
insert into Dish values(255, 187, 'kitchen', 13, 'Sushi', NULL);
insert into Dish values(256, 74, 'curd', 38, 'Pizza', NULL);
insert into Dish values(257, 99, 'tostada', 26, 'Portuguese', NULL);
insert into Dish values(258, 196, 'tea', 19, 'Family Fare', NULL);
insert into Dish values(259, 152, 'caramel', 26, 'Country Food', NULL);
insert into Dish values(260, 67, 'burrito', 6, 'Deli', NULL);
insert into Dish values(261, 72, 'poutine', 38, 'Thai', NULL);
insert into Dish values(262, 49, 'chimichanga', 1, 'Mexican', NULL);
insert into Dish values(263, 96, 'curd', 5, 'Sandwiches', NULL);
insert into Dish values(264, 191, 'steak', 20, 'Mediterranean', NULL);
insert into Dish values(265, 144, 'glaze', 3, 'Pizza', NULL);
insert into Dish values(266, 95, 'muffin', 8, 'Vegetarian', NULL);
insert into Dish values(267, 49, 'olive', 32, 'Barbeque', NULL);
insert into Dish values(268, 82, 'sandwich', 27, 'Mediterranean', NULL);
insert into Dish values(269, 37, 'toast', 30, 'Happy Hour', NULL);
insert into Dish values(270, 187, 'tea', 28, 'Polish', NULL);
insert into Dish values(271, 34, 'drink', 25, 'Indian', NULL);
insert into Dish values(272, 20, 'beer', 7, 'Indian', NULL);
insert into Dish values(273, 84, 'flour', 35, 'Deli', NULL);
insert into Dish values(274, 173, 'liquor', 31, 'Sushi', NULL);
insert into Dish values(275, 75, 'sauce', 10, 'Cafe', NULL);
insert into Dish values(276, 176, 'kitchen', 17, 'Gluten-free', NULL);
insert into Dish values(277, 185, 'pot', 4, 'Cafe', NULL);
insert into Dish values(278, 90, 'taco', 11, 'Polish', NULL);
insert into Dish values(279, 1, 'curd', 6, 'Greek', NULL);
insert into Dish values(280, 162, 'marinade', 3, 'Brazilian', NULL);
insert into Dish values(281, 47, 'bread', 37, 'Barbeque', NULL);
insert into Dish values(282, 134, 'crumble', 9, 'Brunch', NULL);
insert into Dish values(283, 38, 'juice', 30, 'Sushi', NULL);
insert into Dish values(284, 43, 'candy', 34, 'Latin American', NULL);
insert into Dish values(285, 163, 'wheat', 2, 'Barbeque', NULL);
insert into Dish values(286, 133, 'dessert', 22, 'American', NULL);
insert into Dish values(287, 145, 'broth', 3, 'Food Trucks', NULL);
insert into Dish values(288, 102, 'croissant', 5, 'Bar', NULL);
insert into Dish values(289, 24, 'drink', 11, 'Ice Cream', NULL);
insert into Dish values(290, 139, 'wheat', 5, 'Waterfront', NULL);
insert into Dish values(291, 186, 'dessert', 13, 'German', NULL);
insert into Dish values(292, 177, 'cheese', 20, 'Chinese', NULL);
insert into Dish values(293, 83, 'aroma', 8, 'Bakery', NULL);
insert into Dish values(294, 104, 'lard', 25, 'Tapas', NULL);
insert into Dish values(295, 165, 'muffin', 2, 'Bakery', NULL);
insert into Dish values(296, 186, 'crumble', 28, 'Irish', NULL);
insert into Dish values(297, 125, 'glaze', 5, 'Soup & Salad', NULL);
insert into Dish values(298, 76, 'omelette', 35, 'British', NULL);
insert into Dish values(299, 58, 'hamburger', 33, 'Vegetarian', NULL);
insert into Dish values(300, 100, 'kitchen', 11, 'Live Entertainment', NULL);
insert into Dish values(301, 131, 'milk', 36, 'Latin American', NULL);
insert into Dish values(302, 2, 'salsa', 38, 'Sandwiches', NULL);
insert into Dish values(303, 177, 'wheat', 2, 'Family Fare', NULL);
insert into Dish values(304, 83, 'tostada', 9, 'Fine Dining', NULL);
insert into Dish values(305, 189, 'taste', 18, 'Chinese', NULL);
insert into Dish values(306, 79, 'ketchup', 30, 'Breakfast', NULL);
insert into Dish values(307, 196, 'marinade', 13, 'Country Food', NULL);
insert into Dish values(308, 68, 'candy', 16, 'Swedish', NULL);
insert into Dish values(309, 147, 'marinade', 22, 'Sports Bar', NULL);
insert into Dish values(310, 25, 'entree', 19, 'Seafood', NULL);
insert into Dish values(311, 12, 'enchilada', 14, 'Vegetarian', NULL);
insert into Dish values(312, 192, 'syrup', 16, 'Ice Cream', NULL);
insert into Dish values(313, 136, 'recipe', 3, 'Bar', NULL);
insert into Dish values(314, 167, 'plate', 9, 'Cafe', NULL);
insert into Dish values(315, 139, 'cream', 15, 'Deli', NULL);
insert into Dish values(316, 37, 'mayo', 30, 'Thai', NULL);
insert into Dish values(317, 91, 'chocolate', 9, 'Spanish', NULL);
insert into Dish values(318, 95, 'soy', 24, 'Soul Food', NULL);
insert into Dish values(319, 82, 'chili', 36, 'Sushi', NULL);
insert into Dish values(320, 91, 'pasta', 3, 'Creole', NULL);
insert into Dish values(321, 7, 'pastry', 19, 'Bagels', NULL);
insert into Dish values(322, 20, 'queso', 24, 'Mediterranean', NULL);
insert into Dish values(323, 41, 'croissant', 24, 'Cuban', NULL);
insert into Dish values(324, 114, 'meat', 9, 'Vegetarian', NULL);
insert into Dish values(325, 197, 'chocolate', 17, 'Creole', NULL);
insert into Dish values(326, 72, 'entree', 13, 'Fine Dining', NULL);
insert into Dish values(327, 76, 'raclette', 18, 'French', NULL);
insert into Dish values(328, 98, 'grill', 29, 'Caribbean', NULL);
insert into Dish values(329, 70, 'juice', 29, 'Barbeque', NULL);
insert into Dish values(330, 188, 'broth', 18, 'Cafe', NULL);
insert into Dish values(331, 22, 'muffin', 26, 'Waterfront', NULL);
insert into Dish values(332, 58, 'waffle', 36, 'Country Food', NULL);
insert into Dish values(333, 9, 'vinegar', 36, 'Country Food', NULL);
insert into Dish values(334, 114, 'seasoning', 12, 'Doughnuts', NULL);
insert into Dish values(335, 57, 'mousse', 15, 'Japanese', NULL);
insert into Dish values(336, 15, 'water', 6, 'Cafe', NULL);
insert into Dish values(337, 89, 'pizza', 22, 'Japanese', NULL);
insert into Dish values(338, 25, 'marinade', 13, 'Creole', NULL);
insert into Dish values(339, 140, 'bread', 9, 'Family Fare', NULL);
insert into Dish values(340, 5, 'sandwich', 15, 'Vegetarian', NULL);
insert into Dish values(341, 190, 'batter', 9, 'Brunch', NULL);
insert into Dish values(342, 149, 'ketchup', 33, 'Cafe', NULL);
insert into Dish values(343, 171, 'mushroom', 27, 'Bagels', NULL);
insert into Dish values(344, 11, 'lard', 35, 'Portuguese', NULL);
insert into Dish values(345, 81, 'chimichanga', 9, 'Latin American', NULL);
insert into Dish values(346, 15, 'entree', 7, 'Brunch', NULL);
insert into Dish values(347, 178, 'cocoa', 21, 'Fine Dining', NULL);
insert into Dish values(348, 199, 'cream', 12, 'Greek', NULL);
insert into Dish values(349, 181, 'beans', 26, 'German', NULL);
insert into Dish values(350, 171, 'yeast', 27, 'Tapas', NULL);
insert into Dish values(351, 59, 'dish', 15, 'Brunch', NULL);
insert into Dish values(352, 95, 'kitchen', 16, 'Polish', NULL);
insert into Dish values(353, 5, 'croissant', 30, 'Happy Hour', NULL);
insert into Dish values(354, 188, 'steak', 16, 'Bagels', NULL);
insert into Dish values(355, 69, 'food', 2, 'Vegan Friendly', NULL);
insert into Dish values(356, 48, 'wine', 2, 'Caribbean', NULL);
insert into Dish values(357, 125, 'empanada', 5, 'Asian Fusion', NULL);
insert into Dish values(358, 35, 'coffee', 25, 'Sports Bar', NULL);
insert into Dish values(359, 56, 'coffee', 7, 'Pizza', NULL);
insert into Dish values(360, 134, 'rice', 38, 'Country Food', NULL);
insert into Dish values(361, 108, 'eggs', 21, 'Live Entertainment', NULL);
insert into Dish values(362, 130, 'enchilada', 8, 'Swedish', NULL);
insert into Dish values(363, 95, 'ice', 15, 'Bagels', NULL);
insert into Dish values(364, 140, 'chocolate', 19, 'Fine Dining', NULL);
insert into Dish values(365, 66, 'grill', 37, 'German', NULL);
insert into Dish values(366, 126, 'coffee', 35, 'Food Trucks', NULL);
insert into Dish values(367, 34, 'wheat', 21, 'Portuguese', NULL);
insert into Dish values(368, 176, 'glaze', 12, 'Happy Hour', NULL);
insert into Dish values(369, 23, 'recipe', 10, 'Indian', NULL);
insert into Dish values(370, 33, 'stew', 24, 'Waterfront', NULL);
insert into Dish values(371, 94, 'syrup', 8, 'Deli', NULL);
insert into Dish values(372, 138, 'wine', 3, 'Happy Hour', NULL);
insert into Dish values(373, 23, 'beer', 35, 'Soup & Salad', NULL);
insert into Dish values(374, 133, 'taquito', 35, 'Waterfront', NULL);
insert into Dish values(375, 153, 'beans', 3, 'Bakery', NULL);
insert into Dish values(376, 96, 'cheese', 36, 'Portuguese', NULL);
insert into Dish values(377, 128, 'noodle', 25, 'Ice Cream', NULL);
insert into Dish values(378, 157, 'sandwich', 16, 'German', NULL);
insert into Dish values(379, 159, 'fish', 33, 'Seafood', NULL);
insert into Dish values(380, 106, 'entree', 28, 'Vegetarian', NULL);
insert into Dish values(381, 103, 'meat', 29, 'Cafe', NULL);
insert into Dish values(382, 8, 'spice', 12, 'Sushi', NULL);
insert into Dish values(383, 4, 'cider', 30, 'Fine Dining', NULL);
insert into Dish values(384, 126, 'taquito', 32, 'Burgers', NULL);
insert into Dish values(385, 80, 'seasoning', 14, 'Thai', NULL);
insert into Dish values(386, 107, 'taco', 39, 'Seafood', NULL);
insert into Dish values(387, 60, 'plate', 34, 'Italian', NULL);
insert into Dish values(388, 165, 'cider', 20, 'Food Trucks', NULL);
insert into Dish values(389, 145, 'recipe', 7, 'Caribbean', NULL);
insert into Dish values(390, 194, 'seasoning', 39, 'Latin American', NULL);
insert into Dish values(391, 41, 'cuisine', 3, 'Vegetarian', NULL);
insert into Dish values(392, 59, 'mousse', 35, 'Thai', NULL);
insert into Dish values(393, 69, 'sandwich', 6, 'Waterfront', NULL);
insert into Dish values(394, 87, 'taquito', 2, 'Tapas', NULL);
insert into Dish values(395, 97, 'pasta', 32, 'Deli', NULL);
insert into Dish values(396, 199, 'soup', 11, 'Italian', NULL);
insert into Dish values(397, 129, 'syrup', 38, 'Fast Food', NULL);
insert into Dish values(398, 161, 'chimichanga', 36, 'Pancakes', NULL);
insert into Dish values(399, 191, 'chili', 6, 'Live Entertainment', NULL);
insert into Dish values(400, 69, 'glaze', 14, 'Burgers', NULL);
insert into Dish values(401, 8, 'enchilada', 22, 'Steaks', NULL);
insert into Dish values(402, 28, 'burrito', 25, 'Swedish', NULL);
insert into Dish values(403, 11, 'meat', 39, 'Brazilian', NULL);
insert into Dish values(404, 198, 'curd', 3, 'Sandwiches', NULL);
insert into Dish values(405, 63, 'broth', 16, 'Brunch', NULL);
insert into Dish values(406, 140, 'skillet', 34, 'Indian', NULL);
insert into Dish values(407, 115, 'enchilada', 17, 'Vegan Friendly', NULL);
insert into Dish values(408, 139, 'aroma', 15, 'Pizza', NULL);
insert into Dish values(409, 30, 'juice', 31, 'Soul Food', NULL);
insert into Dish values(410, 41, 'crumble', 5, 'Cuban', NULL);
insert into Dish values(411, 139, 'waffle', 3, 'Spanish', NULL);
insert into Dish values(412, 178, 'tea', 32, 'British', NULL);
insert into Dish values(413, 194, 'pie', 5, 'Mediterranean', NULL);
insert into Dish values(414, 193, 'pan', 21, 'Vegetarian', NULL);
insert into Dish values(415, 94, 'flour', 6, 'Fast Food', NULL);
insert into Dish values(416, 36, 'tostada', 8, 'Bar', NULL);
insert into Dish values(417, 167, 'pudding', 4, 'Sushi', NULL);
insert into Dish values(418, 124, 'empanada', 14, 'Pancakes', NULL);
insert into Dish values(419, 9, 'caviar', 32, 'Vegetarian', NULL);
insert into Dish values(420, 67, 'water', 18, 'Barbeque', NULL);
insert into Dish values(421, 106, 'plate', 7, 'Cuban', NULL);
insert into Dish values(422, 172, 'glaze', 18, 'Thai', NULL);
insert into Dish values(423, 96, 'salad', 23, 'Live Entertainment', NULL);
insert into Dish values(424, 78, 'muffin', 27, 'Country Food', NULL);
insert into Dish values(425, 184, 'pizza', 18, 'Brazilian', NULL);
insert into Dish values(426, 32, 'cobbler', 12, 'Brunch', NULL);
insert into Dish values(427, 178, 'cream', 35, 'Spanish', NULL);
insert into Dish values(428, 59, 'margarine', 11, 'Steaks', NULL);
insert into Dish values(429, 40, 'beans', 17, 'Pizza', NULL);
insert into Dish values(430, 28, 'yogurt', 1, 'Deli', NULL);
insert into Dish values(431, 51, 'chimichanga', 12, 'Doughnuts', NULL);
insert into Dish values(432, 73, 'toast', 4, 'Sushi', NULL);
insert into Dish values(433, 160, 'aroma', 13, 'Breakfast', NULL);
insert into Dish values(434, 199, 'coffee', 25, 'Pizza', NULL);
insert into Dish values(435, 69, 'chocolate', 3, 'Caribbean', NULL);
insert into Dish values(436, 103, 'skillet', 31, 'Mexican', NULL);
insert into Dish values(437, 191, 'tostada', 7, 'Greek', NULL);
insert into Dish values(438, 102, 'liquor', 8, 'Caribbean', NULL);
insert into Dish values(439, 147, 'soy', 13, 'American', NULL);
insert into Dish values(440, 170, 'candy', 13, 'Burgers', NULL);
insert into Dish values(441, 141, 'soda', 37, 'Breakfast', NULL);
insert into Dish values(442, 108, 'noodle', 3, 'Sushi', NULL);
insert into Dish values(443, 32, 'caviar', 31, 'Asian Fusion', NULL);
insert into Dish values(444, 67, 'queso', 34, 'Irish', NULL);
insert into Dish values(445, 196, 'croissant', 31, 'Polish', NULL);
insert into Dish values(446, 9, 'bagel', 36, 'Hot Dogs', NULL);
insert into Dish values(447, 67, 'water', 7, 'Brazilian', NULL);
insert into Dish values(448, 112, 'yeast', 16, 'German', NULL);
insert into Dish values(449, 183, 'waffle', 16, 'Chinese', NULL);
insert into Dish values(450, 12, 'plate', 12, 'Brunch', NULL);
insert into Dish values(451, 130, 'wok', 30, 'Pizza', NULL);
insert into Dish values(452, 11, 'foie gras', 40, 'Food Trucks', NULL);
insert into Dish values(453, 57, 'raclette', 38, 'Japanese', NULL);
insert into Dish values(454, 88, 'fish', 36, 'Swedish', NULL);
insert into Dish values(455, 48, 'taco', 2, 'Caribbean', NULL);
insert into Dish values(456, 120, 'soda', 29, 'Brunch', NULL);
insert into Dish values(457, 139, 'chili', 2, 'Pizza', NULL);
insert into Dish values(458, 18, 'pot', 27, 'Waterfront', NULL);
insert into Dish values(459, 120, 'dish', 2, 'Chinese', NULL);
insert into Dish values(460, 10, 'recipe', 14, 'Spanish', NULL);
insert into Dish values(461, 94, 'recipe', 19, 'Cafe', NULL);
insert into Dish values(462, 72, 'mushroom', 23, 'Doughnuts', NULL);
insert into Dish values(463, 97, 'sauce', 30, 'Hot Dogs', NULL);
insert into Dish values(464, 147, 'syrup', 29, 'Country Food', NULL);
insert into Dish values(465, 25, 'ice', 9, 'Indian', NULL);
insert into Dish values(466, 9, 'raclette', 11, 'Pancakes', NULL);
insert into Dish values(467, 124, 'wok', 10, 'Soul Food', NULL);
insert into Dish values(468, 149, 'sopapillas', 33, 'Burgers', NULL);
insert into Dish values(469, 171, 'poutine', 17, 'Latin American', NULL);
insert into Dish values(470, 64, 'paste', 23, 'Family Fare', NULL);
insert into Dish values(471, 150, 'flour', 2, 'Bar', NULL);
insert into Dish values(472, 41, 'cobbler', 8, 'Mexican', NULL);
insert into Dish values(473, 181, 'salad', 8, 'Tapas', NULL);
insert into Dish values(474, 176, 'tostada', 40, 'Bakery', NULL);
insert into Dish values(475, 71, 'cocoa', 31, 'Hot Dogs', NULL);
insert into Dish values(476, 138, 'fish', 19, 'Breakfast', NULL);
insert into Dish values(477, 11, 'stew', 20, 'American', NULL);
insert into Dish values(478, 23, 'paste', 33, 'Creole', NULL);
insert into Dish values(479, 118, 'pasta', 31, 'Creole', NULL);
insert into Dish values(480, 184, 'muffin', 38, 'Hot Dogs', NULL);
insert into Dish values(481, 110, 'taste', 16, 'Brunch', NULL);
insert into Dish values(482, 67, 'grill', 6, 'Pancakes', NULL);
insert into Dish values(483, 0, 'yeast', 25, 'Swedish', NULL);
insert into Dish values(484, 197, 'hamburger', 34, 'Sandwiches', NULL);
insert into Dish values(485, 172, 'bagel', 3, 'Family Fare', NULL);
insert into Dish values(486, 15, 'lard', 11, 'Thai', NULL);
insert into Dish values(487, 72, 'dish', 2, 'Cafe', NULL);
insert into Dish values(488, 30, 'cocoa', 3, 'Chinese', NULL);
insert into Dish values(489, 91, 'cake', 20, 'Soup & Salad', NULL);
insert into Dish values(490, 176, 'taste', 16, 'Waterfront', NULL);
insert into Dish values(491, 59, 'queso', 35, 'German', NULL);
insert into Dish values(492, 83, 'nut', 31, 'Gluten-free', NULL);
insert into Dish values(493, 36, 'waffle', 16, 'Sandwiches', NULL);
insert into Dish values(494, 101, 'tostada', 8, 'Brunch', NULL);
insert into Dish values(495, 57, 'sauce', 11, 'Mexican', NULL);
insert into Dish values(496, 42, 'taste', 29, 'Vegetarian', NULL);
insert into Dish values(497, 99, 'beans', 22, 'American', NULL);
insert into Dish values(498, 119, 'muffin', 19, 'Caribbean', NULL);
insert into Dish values(499, 130, 'mayonnaise', 30, 'Steaks', NULL);


insert into Restaurant_owner values(0, 95, 43);
insert into Restaurant_owner values(1, 38, 42);
insert into Restaurant_owner values(2, 144, 3);
insert into Restaurant_owner values(3, 76, 41);
insert into Restaurant_owner values(4, 26, 46);
insert into Restaurant_owner values(5, 2, 25);
insert into Restaurant_owner values(6, 161, 1);
insert into Restaurant_owner values(7, 154, 49);
insert into Restaurant_owner values(8, 109, 10);
insert into Restaurant_owner values(9, 63, 49);
insert into Restaurant_owner values(10, 78, 18);
insert into Restaurant_owner values(11, 111, 9);
insert into Restaurant_owner values(12, 133, 32);
insert into Restaurant_owner values(13, 187, 51);
insert into Restaurant_owner values(14, 26, 15);
insert into Restaurant_owner values(15, 190, 16);
insert into Restaurant_owner values(16, 96, 15);
insert into Restaurant_owner values(17, 29, 14);
insert into Restaurant_owner values(18, 105, 38);
insert into Restaurant_owner values(19, 69, 25);
insert into Restaurant_owner values(20, 109, 11);
insert into Restaurant_owner values(21, 38, 34);
insert into Restaurant_owner values(22, 142, 42);
insert into Restaurant_owner values(23, 136, 12);
insert into Restaurant_owner values(24, 82, 11);
insert into Restaurant_owner values(25, 48, 1);
insert into Restaurant_owner values(26, 31, 54);
insert into Restaurant_owner values(27, 67, 36);
insert into Restaurant_owner values(28, 192, 22);
insert into Restaurant_owner values(29, 135, 43);
insert into Restaurant_owner values(30, 49, 10);
insert into Restaurant_owner values(31, 121, 31);
insert into Restaurant_owner values(32, 186, 11);
insert into Restaurant_owner values(33, 40, 13);
insert into Restaurant_owner values(34, 78, 20);
insert into Restaurant_owner values(35, 13, 50);
insert into Restaurant_owner values(36, 31, 17);
insert into Restaurant_owner values(37, 131, 23);
insert into Restaurant_owner values(38, 90, 14);
insert into Restaurant_owner values(39, 69, 21);
insert into Restaurant_owner values(40, 101, 9);
insert into Restaurant_owner values(41, 196, 16);
insert into Restaurant_owner values(42, 184, 57);
insert into Restaurant_owner values(43, 37, 31);
insert into Restaurant_owner values(44, 113, 34);
insert into Restaurant_owner values(45, 98, 59);
insert into Restaurant_owner values(46, 41, 28);
insert into Restaurant_owner values(47, 69, 42);
insert into Restaurant_owner values(48, 197, 2);
insert into Restaurant_owner values(49, 92, 30);
insert into Restaurant_owner values(50, 106, 35);
insert into Restaurant_owner values(51, 113, 26);
insert into Restaurant_owner values(52, 127, 8);
insert into Restaurant_owner values(53, 61, 11);
insert into Restaurant_owner values(54, 128, 46);
insert into Restaurant_owner values(55, 133, 40);
insert into Restaurant_owner values(56, 101, 26);
insert into Restaurant_owner values(57, 90, 34);
insert into Restaurant_owner values(58, 78, 43);
insert into Restaurant_owner values(59, 141, 9);

COMMIT;