PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;

DELETE FROM User;
DELETE FROM Restaurant;
DELETE FROM Review;
DELETE FROM Dish;
DELETE FROM Dish_order;
DELETE FROM Restaurant_owner;

insert into User values(0, 'Sally Richmond', 'mysteriousGlenn41@juno.com', 494886694, '390, Maple Drive - Port St. Lucie', 'doUUlFBbMi');
insert into User values(1, 'Francis Orr', 'pleasantKyle@facebook.com', 811592890, '575, Walnut Street - Duluth', 'CYxwvXBdwT');
insert into User values(2, 'Cornelius Roberson', 'lazyPedro@yahoo.de', 102918343, '495, Pheasant Lane - Green Bay', 's72lEIzR6F');
insert into User values(3, 'Teri Carlton', 'badCindy@free.fr', 297763795, '258, 4th Street West - Lexington', 'DA7KNJUS7s');
insert into User values(4, 'Genevieve Ferrell', 'nastyRaymond54@bigpond.net.au', 939525598, '943, Williams Street - Laredo', 'Gne3KBZlDx');
insert into User values(5, 'Trevor Blackwell', 'zealousAimee@centurytel.net', 963347376, '162, Cleveland Avenue - Oceanside', 'PqjczP2d8F');
insert into User values(6, 'Francisco Block', 'embarrassedKelli@terra.com.br', 382246748, '947, Springhouse Lane - Scottsdale', 'RYMuRVkI9Z');
insert into User values(7, 'David Wood', 'Lindsayembarrassed@rocketmail.com', 930125908, '54, Route 98 - Burbank', 'OCZDj813IC');
insert into User values(8, 'Warren Neal', 'Craigcautious@planet.nl', 187735661, '809, Bradley Street - Richland', '1ncc84Tdhu');
insert into User values(9, 'Traci Summers', 'jollyBrittany@bigpond.com', 936932776, '159, Sunset Lane - Leominster', 'vz5GTvc88v');
insert into User values(10, 'Damian Carson', 'putridCindy@yahoo.co.id', 181566883, '526, Lake Drive - Newark', '0EZBIzbhVO');
insert into User values(11, 'Daniela Byrd', 'fairBethany34@telenet.be', 759953556, '843, Durham Court - Pasadena', 'j6QXVY53Xz');
insert into User values(12, 'Barry Harrison', 'amusedDustin45@ig.com.br', 911470666, '105, Maple Avenue - Irving', 'xDrxd2NRTB');
insert into User values(13, 'Dennis Johnston', 'Susaneasy@live.com.au', 551584909, '941, Willow Court - Irving', 'Rpicm0YkWA');
insert into User values(14, 'Loren Olson', 'Jamieannoying@facebook.com', 127914925, '80, Overhill Road - Albuquerque', 'WgIGthE6YO');
insert into User values(15, 'Kathleen Ferrell', 'motionlessPaul41@me.com', 520848382, '242, Summer Street - Ogden', 'I4CEvNan0z');
insert into User values(16, 'Clifford Frost', 'hilariousAmy50@orange.fr', 662981635, '258, 4th Street South - Tempe', 'HA8kI8aJ9F');
insert into User values(17, 'Josephine McLamb', 'preciousAutumn98@earthlink.net', 766184101, '563, Cherry Street - Hickory', 'Yn4sSjsxAc');
insert into User values(18, 'Dallas Harvey', 'Clairewide-eyed@bellsouth.net', 539277784, '659, Cypress Court - Jackson', 'DupnJVvDXe');
insert into User values(19, 'Jade Armstrong', 'quaintJessie@tiscali.co.uk', 488107968, '831, Catherine Street - Myrtle Beach', 'SE0WVogduU');
insert into User values(20, 'Alisa Coates', 'disturbedArmando@yahoo.it', 122760520, '312, Beverly Road - Lancaster', '3LIATgwIVL');
insert into User values(21, 'Lori Crabtree', 'Dominicunsightly@rocketmail.com', 375352584, '796, Creamery Road - Inglewood', 'lE7U5iXSSS');
insert into User values(22, 'Elias Currie', 'inexpensiveDouglas66@neuf.fr', 851831932, '543, Kingsley Court - Simi Valley', 'wgeyVb8Wfi');
insert into User values(23, 'Celeste House', 'terribleKellie53@att.net', 951454673, '652, Blue Ridge Drive - Clearwater', 'coAnA5v60S');
insert into User values(24, 'Shelly Davidson', 'gloriousEdward65@live.it', 107812591, '822, Parkside Drive - Frederick', 'HSob9mFwsC');
insert into User values(25, 'Chelsie Bruce', 'scaryAlexander@me.com', 953905762, '65, 6th Street North - Santa Maria', 'SAD1EvB59H');
insert into User values(26, 'Israel Leonard', 'Georgemushy@yahoo.de', 983935405, '706, Fairfax Court - Mobile', 'AFYkFYQRha');
insert into User values(27, 'Laurel Spivey', 'elegantSamuel34@msn.com', 583481432, '428, 8th Avenue - St. Paul', 'Qbovl0M31N');
insert into User values(28, 'Dante Herndon', 'Rosetender@yahoo.com.br', 897739203, '478, Marshall Drive - Hollywood', 'SVd9YGcLZG');
insert into User values(29, 'Angel Mathews', 'pleasantKyle@facebook.com', 562386915, '9, Coolidge Avenue - Barnstable', '993byEljiN');

insert into Restaurant values(0, 'Massachusetts', 'German', '57, Pin Oak Drive - Waterbury', '3IA2EH9M6G');
insert into Restaurant values(1, 'Chef First', 'Waterfront', '941, Wesley Avenue - Roseville', 'BzueccvpcX');
insert into Restaurant values(2, 'PM Fish & Steak House', 'Swedish', '964, Applewood Drive - Inglewood', '0FVqnKILWP');
insert into Restaurant values(3, 'Ottawa', 'Fast Food', '61, Sheffield Drive - Santa Clara', 'gWeWvtu0v8');
insert into Restaurant values(4, 'Restaurant Gordon Ramsay', 'Japanese', '825, Grand Avenue - Fort Collins', 'q3xawmtxDX');
insert into Restaurant values(5, 'Craft', 'Portuguese', '131, Jennifer Lane - Bonita Springs', 'GJjkpqi2kM');
insert into Restaurant values(6, 'Nacho', 'Live Entertainment', '895, Church Street North - Oxnard', 'nQrMraNOMi');
insert into Restaurant values(7, 'Cafe Monarch', 'Vegetarian', '82, Washington Street West - Deltona', 'weMxTkxvDn');
insert into Restaurant values(8, 'Geronimo', 'Fine Dining', '413, Woodview Drive - Houma', '3IA2EH9M6G');
insert into Restaurant values(9, 'Chef Parade', 'Cafe', '377, Tanglewood Lane - Hollywood', 'i4NdiR3S0z');
insert into Restaurant values(10, 'Gary Danko', 'Sandwiches', '38, Aberdeen Drive - Topeka', 'fKYSHmE6rG');
insert into Restaurant values(11, 'Golden Ledge', 'Brazilian', '529, Heather Lane - Burbank', 'b9ncoSI95c');
insert into Restaurant values(12, 'Dragon', 'American', '0, Mockingbird Lane - Provo', 'Xfzdc9iZXD');
insert into Restaurant values(13, 'Crew Cafe', 'Japanese', '169, 5th Avenue - Santa Ana', 'kiEvrdYOXL');
insert into Restaurant values(14, 'Rose’s Luxury', 'Italian', '17, Dogwood Court - Elizabeth', 'aNbCsJO13s');
insert into Restaurant values(15, 'Amsterdam', 'Bagels', '150, 6th Street North - Knoxville', '1SgdovoWbB');
insert into Restaurant values(16, 'Homemade Bagels', 'Hot Dogs', '947, Laurel Lane - Memphis', 'qGjIIbnLuR');
insert into Restaurant values(17, 'Del Posto', 'Sandwiches', '799, Elm Avenue - Carrollton', 'KAmKDpmBmI');
insert into Restaurant values(18, 'Daniel', 'Bakery', '976, Cypress Drive - Virginia Beach', 'btu9fP0vIR');
insert into Restaurant values(19, 'Girl & The Goat', 'Tapas', '311, Cardinal Lane - Fort Collins', 'yLEQFJWtOd');
insert into Restaurant values(20, 'Spice Villa', 'Latin American', '934, Bank Street - Louisville', 'WP7NIknmSw');
insert into Restaurant values(21, 'Explore the', 'Deli', '759, Franklin Street - Durham', 'NZWUkIBaP0');
insert into Restaurant values(22, 'Explore the', 'Bagels', '32, Coventry Court - Newport News', 'Ek6X5jm99B');
insert into Restaurant values(23, 'Arrow Spoon', 'Spanish', '540, 1st Street West - Newburgh', '3jHPBMRfv2');
insert into Restaurant values(24, 'Sonic Drive-In', 'Doughnuts', '397, Maplewood Drive - Plano', 'KnMrlv5HxC');
insert into Restaurant values(25, 'Umami Burger', 'American', '410, Riverside Avenue - Marina', 'tvHu5ItGaI');
insert into Restaurant values(26, 'Project Juice', 'Cafe', '874, Valley View Road - Westminster', 'A7akdP5BVq');
insert into Restaurant values(27, 'Marea', 'Fast Food', '377, Skyline Drive - Glendale', '5Azd7zmMCq');
insert into Restaurant values(28, 'Vernick Food & Drink', 'Live Entertainment', '232, Devonshire Court - Seaside', 'r7ZdZR3QoE');
insert into Restaurant values(29, 'Ya', 'British', '322, Hilltop Drive - Gastonia', 'DFm0om67cL');

insert into Review values(0, 'Nam molestie, justo eu tincidunt posuere, lacus nibh facilisis nibh, sit amet consectetur sapien magna a purus. Vestibulum pretium nunc ac ullamcorper euismod. Nulla massa orci, blandit ac suscipit eu, viverra eget quam. Curabitur auctor, justo eget euismod consectetur, purus libero consequat ante, a pretium dolor nunc in nulla. Praesent finibus tellus justo, sit amet condimentum quam fringilla ut. Sed pulvinar risus eu euismod posuere. Nam molestie augue sed quam pellentesque malesuada. In pharetra faucibus volutpat.', 1, 11, 8);
insert into Review values(1, 'Pellentesque dignissim, velit semper venenatis rutrum, ligula justo commodo dolor, vitae convallis elit ante eu sapien. Aliquam eget augue convallis, consectetur ligula ac, maximus felis. Aenean rhoncus ac tellus eu condimentum. Curabitur eleifend velit ex, at mollis dolor eleifend ut. Duis molestie dapibus orci, sed blandit tortor. Nam nec rhoncus lectus. Nullam porttitor diam id finibus lobortis. Donec at euismod odio. In ac porta orci. Nunc ut metus a purus mattis facilisis eget ac nibh. Morbi erat odio, sodales in libero eu, mollis scelerisque nisi. Fusce sed finibus magna. Sed hendrerit mollis mollis. Integer congue risus posuere, fermentum augue et, elementum urna.', 2, 28, 18);
insert into Review values(2, 'Praesent convallis, justo quis volutpat aliquam, ligula risus bibendum lorem, vel convallis lacus ipsum ut purus. Integer lobortis metus eget est porta, sit amet viverra mi lacinia. Suspendisse ac metus porta, mollis velit eget, ultricies lectus. Sed sed pulvinar lorem. In hac habitasse platea dictumst. Nulla a porta nisi. Phasellus consequat, orci pharetra consectetur lobortis, erat dui ultricies quam, sed luctus mauris risus id massa. Donec at nibh vel enim mollis cursus. Sed consequat, augue vitae laoreet condimentum, justo diam finibus augue, sit amet bibendum elit turpis quis ex. Fusce gravida metus venenatis efficitur venenatis. Donec nec mi nibh. Suspendisse lobortis dolor dolor, in pellentesque velit posuere at. Maecenas mauris lacus, tincidunt vitae libero et, dictum dapibus erat. Curabitur elit orci, imperdiet ac turpis in, sodales aliquet sapien.', 8, 1, 1);
insert into Review values(3, 'Maecenas fermentum est vitae sapien dictum, sit amet viverra eros faucibus. Proin convallis augue lectus, at rutrum nisi bibendum vel. Duis id tincidunt dolor. Donec rutrum a arcu vel elementum. Proin mauris neque, accumsan commodo gravida ut, imperdiet at lectus. Donec eget mauris mauris. Donec nunc ex, venenatis vel arcu in, pretium accumsan urna. Maecenas venenatis pharetra sodales. Ut ultricies enim ut lectus posuere congue. Quisque a eleifend nunc. Mauris condimentum vehicula nisl sit amet posuere.', 2, 4, 6);
insert into Review values(4, 'Morbi neque mauris, aliquet vel purus vitae, tincidunt sodales lacus. Vestibulum egestas nisl fringilla dui gravida mollis. Sed sed tempor massa, ac blandit dui. Pellentesque sit amet ultrices mauris. Pellentesque consectetur ultricies volutpat. Nullam malesuada turpis quis ex suscipit tempus. In nec accumsan massa.', 2, 14, 26);
insert into Review values(5, 'In sed nunc varius, condimentum ligula ac, viverra neque. Proin eget tempor mi. Nulla auctor, leo eget mollis ultrices, odio quam pulvinar nibh, eget pellentesque erat quam ut justo. Nulla venenatis ante at arcu dignissim, sed aliquet ex interdum. Sed ornare purus nec lectus tempor, a cursus eros finibus. Praesent sed ornare ligula. Nam ac gravida turpis. Nunc sit amet nisi venenatis sapien rutrum lobortis. Aenean eget nisl euismod risus rhoncus convallis. Nunc nec lacus libero.', 1, 26, 2);
insert into Review values(6, 'In sed nunc varius, condimentum ligula ac, viverra neque. Proin eget tempor mi. Nulla auctor, leo eget mollis ultrices, odio quam pulvinar nibh, eget pellentesque erat quam ut justo. Nulla venenatis ante at arcu dignissim, sed aliquet ex interdum. Sed ornare purus nec lectus tempor, a cursus eros finibus. Praesent sed ornare ligula. Nam ac gravida turpis. Nunc sit amet nisi venenatis sapien rutrum lobortis. Aenean eget nisl euismod risus rhoncus convallis. Nunc nec lacus libero.', 9, 15, 11);
insert into Review values(7, 'Proin tincidunt lorem eget libero vulputate tincidunt. Suspendisse ullamcorper cursus metus. In eu erat eu nulla accumsan aliquet. Quisque vitae nulla quis magna venenatis vehicula. Nunc facilisis libero vel eleifend cursus. Nunc sodales, neque vel vestibulum euismod, nisi felis tincidunt purus, vel aliquam libero tellus a est. Pellentesque luctus nisl in lobortis gravida. Curabitur efficitur leo nunc, eget rutrum velit varius ut.', 7, 19, 19);
insert into Review values(8, 'Praesent convallis, justo quis volutpat aliquam, ligula risus bibendum lorem, vel convallis lacus ipsum ut purus. Integer lobortis metus eget est porta, sit amet viverra mi lacinia. Suspendisse ac metus porta, mollis velit eget, ultricies lectus. Sed sed pulvinar lorem. In hac habitasse platea dictumst. Nulla a porta nisi. Phasellus consequat, orci pharetra consectetur lobortis, erat dui ultricies quam, sed luctus mauris risus id massa. Donec at nibh vel enim mollis cursus. Sed consequat, augue vitae laoreet condimentum, justo diam finibus augue, sit amet bibendum elit turpis quis ex. Fusce gravida metus venenatis efficitur venenatis. Donec nec mi nibh. Suspendisse lobortis dolor dolor, in pellentesque velit posuere at. Maecenas mauris lacus, tincidunt vitae libero et, dictum dapibus erat. Curabitur elit orci, imperdiet ac turpis in, sodales aliquet sapien.', 2, 13, 13);
insert into Review values(9, 'Proin ultricies erat non enim commodo, eu vulputate lectus interdum. Aenean nunc est, imperdiet in sem vel, molestie posuere lorem. In vulputate risus maximus, pharetra nunc vel, dapibus purus. Donec venenatis, magna vitae pharetra facilisis, dolor metus auctor eros, id interdum risus mauris ac ante. Aliquam erat volutpat. Morbi imperdiet, augue quis elementum facilisis, nulla eros varius purus, ac eleifend orci quam sed urna. Suspendisse potenti. Vestibulum enim libero, molestie eget sollicitudin ultricies, volutpat non odio. Praesent ac elit ac purus consectetur ultricies. Vivamus eu mattis nibh.', 2, 4, 7);
insert into Review values(10, 'Phasellus quis quam nibh. Integer sit amet leo nulla. Aliquam erat volutpat. Nam nulla tortor, interdum vitae sem eget, eleifend aliquam est. Integer finibus lacus nec velit cursus mollis. Morbi pulvinar velit eros, et molestie est fermentum quis. Nunc quis ligula ut magna sagittis viverra. Etiam nec malesuada felis. Phasellus sed pretium lorem. Sed in dictum odio. Sed tempus porttitor congue.', 6, 3, 25);
insert into Review values(11, 'Maecenas placerat, nibh rutrum tincidunt euismod, nisl sem venenatis leo, at maximus elit neque quis dui. In metus felis, finibus eget mollis vel, varius ac lacus. Donec dapibus ornare auctor. Suspendisse ornare porttitor diam sit amet dignissim. Curabitur ultricies ligula id ipsum tempor tincidunt. Ut eu convallis ex. Nunc sodales ligula sed massa elementum malesuada. Praesent ipsum erat, fringilla ac sodales non, lacinia in libero. Aenean pretium tellus ac malesuada maximus. Aenean ultrices aliquet nibh, vel dictum tellus interdum molestie. Donec tempus sem ac maximus vestibulum.', 2, 13, 29);
insert into Review values(12, 'Morbi non venenatis est. Nam ullamcorper dolor nisl, quis sodales magna volutpat a. Nulla non sapien vel libero varius laoreet id id lorem. Donec a iaculis eros. Donec in sem consectetur, molestie purus in, feugiat eros. Maecenas tincidunt, lorem eget ultrices condimentum, leo sem condimentum erat, nec molestie neque orci pulvinar urna. Nam at ex ac est euismod faucibus vitae vitae augue. Praesent fermentum mi in odio porttitor imperdiet. Cras eu vehicula sapien. Donec nulla justo, aliquet sit amet mi sed, suscipit tristique urna.', 6, 13, 20);
insert into Review values(13, 'Morbi pellentesque magna ut risus rutrum ultricies. Phasellus vehicula pellentesque tempus. Nam vel felis sit amet nunc efficitur pretium. Nunc id aliquam mauris. Integer a erat quam. Phasellus dapibus est sed elit mattis malesuada. Nunc non justo justo. Vestibulum elit sapien, aliquet eu volutpat in, dapibus a nisl. Etiam purus erat, congue lacinia ante sodales, vestibulum rhoncus felis. Morbi quis sem ullamcorper ipsum suscipit varius. Nulla ultricies interdum finibus. Integer vel augue viverra, lacinia nunc nec, tristique massa. Phasellus tempor nunc a euismod porttitor.', 10, 18, 17);
insert into Review values(14, 'Phasellus laoreet metus augue, non consequat libero faucibus quis. Aenean at nisi leo. Sed in tristique nisl, quis iaculis orci. Aliquam elementum elementum lorem a mattis. In malesuada ex et velit bibendum viverra. Maecenas lacinia, urna eu imperdiet laoreet, mauris felis faucibus lacus, rhoncus pellentesque sem metus eget purus. Interdum et malesuada fames ac ante ipsum primis in faucibus.', 4, 20, 12);
insert into Review values(15, 'Mauris dui justo, molestie eu convallis id, maximus ut augue. Ut laoreet porttitor lacus, non commodo est venenatis faucibus. Phasellus sed tempor massa. Donec eu est lobortis, dapibus erat sed, maximus felis. Nunc vulputate congue orci nec aliquet. Curabitur quis felis malesuada, lacinia justo vitae, gravida augue. Nullam imperdiet placerat nisl, ac sollicitudin augue. Aenean auctor placerat nulla nec mollis. Curabitur volutpat metus ultrices, venenatis augue at, malesuada lorem. Sed tempus urna eget aliquam vulputate.', 3, 13, 11);
insert into Review values(16, 'Aliquam eleifend tincidunt purus et mollis. Donec mauris ligula, condimentum in urna at, vehicula porttitor est. Ut posuere id nibh blandit auctor. Ut viverra augue at lobortis auctor. Praesent sit amet bibendum enim. Etiam egestas urna nec condimentum sollicitudin. Fusce ut varius ligula. Aliquam eget sagittis massa. Aenean ut erat fringilla, cursus quam non, interdum enim. Cras non ligula ut orci ultricies sollicitudin et ut dolor. Integer auctor iaculis felis, ut pulvinar quam efficitur sit amet. Pellentesque eget sagittis nisl. Etiam placerat turpis id dolor finibus rutrum. Phasellus luctus id felis at bibendum.', 6, 21, 3);
insert into Review values(17, 'In in auctor velit. Vestibulum porta viverra tortor, a convallis dui aliquam non. Etiam ullamcorper mauris non pulvinar feugiat. Vivamus maximus rhoncus diam, et vehicula velit scelerisque sed. Aenean dapibus quis odio vitae blandit. Etiam a tellus ligula. Curabitur at aliquam ligula. Ut fermentum ante nec scelerisque sodales. Vivamus condimentum eget orci sit amet gravida. Cras sit amet finibus nisi. Sed viverra lectus sed dolor porttitor auctor at nec erat. Donec sit amet risus ultrices, placerat mi nec, sagittis erat. Fusce laoreet blandit justo, ut vestibulum quam luctus ac.', 8, 10, 25);
insert into Review values(18, 'In sed nunc varius, condimentum ligula ac, viverra neque. Proin eget tempor mi. Nulla auctor, leo eget mollis ultrices, odio quam pulvinar nibh, eget pellentesque erat quam ut justo. Nulla venenatis ante at arcu dignissim, sed aliquet ex interdum. Sed ornare purus nec lectus tempor, a cursus eros finibus. Praesent sed ornare ligula. Nam ac gravida turpis. Nunc sit amet nisi venenatis sapien rutrum lobortis. Aenean eget nisl euismod risus rhoncus convallis. Nunc nec lacus libero.', 4, 0, 7);
insert into Review values(19, 'Aenean dolor eros, tristique et urna quis, fringilla efficitur arcu. Nulla bibendum pharetra urna, sit amet congue arcu tempus eget. Nulla facilisi. Curabitur dignissim cursus nunc in pulvinar. Vivamus finibus molestie vulputate. Sed dictum, erat et aliquam euismod, est quam lobortis nisi, eu commodo sem ex iaculis nibh. Phasellus ut iaculis libero, a feugiat nulla. Duis aliquet cursus sem, eu pharetra nisl efficitur id. Duis scelerisque libero et turpis lobortis, nec lacinia sem venenatis. Duis finibus dolor vitae rutrum tristique.', 5, 27, 6);
insert into Review values(20, 'Maecenas fermentum est vitae sapien dictum, sit amet viverra eros faucibus. Proin convallis augue lectus, at rutrum nisi bibendum vel. Duis id tincidunt dolor. Donec rutrum a arcu vel elementum. Proin mauris neque, accumsan commodo gravida ut, imperdiet at lectus. Donec eget mauris mauris. Donec nunc ex, venenatis vel arcu in, pretium accumsan urna. Maecenas venenatis pharetra sodales. Ut ultricies enim ut lectus posuere congue. Quisque a eleifend nunc. Mauris condimentum vehicula nisl sit amet posuere.', 10, 29, 0);
insert into Review values(21, 'Maecenas luctus, velit id porta semper, mi leo rhoncus massa, vel ultricies neque nibh et diam. Integer vel elit risus. Pellentesque ut aliquam lectus. Ut et sollicitudin augue. Aliquam sollicitudin lacus lectus, in pellentesque augue laoreet sed. Nam ullamcorper, arcu et malesuada feugiat, elit erat tincidunt dui, quis dignissim dolor nisi sit amet eros. Phasellus vitae ligula interdum, auctor eros ut, malesuada nibh. Vestibulum sed congue velit, quis cursus felis.', 6, 18, 1);
insert into Review values(22, 'Pellentesque varius vel leo sed mollis. Curabitur dignissim porta pellentesque. Mauris ac tortor vel erat eleifend dictum. Vestibulum imperdiet ultricies consectetur. Aliquam ornare, ligula non sodales interdum, nisi nulla ullamcorper ante, fringilla sodales dolor turpis eget lacus. Nunc ac efficitur tellus. Integer semper ornare tortor, sed eleifend nibh vehicula quis. Etiam eu lacus et enim consequat tincidunt.', 9, 1, 5);
insert into Review values(23, 'In hac habitasse platea dictumst. Nam tristique dapibus dolor vel pellentesque. Duis venenatis pharetra dolor et aliquet. Maecenas nec finibus neque, non facilisis orci. Suspendisse malesuada imperdiet condimentum. Aenean nibh velit, aliquet in erat id, dictum luctus erat. Sed hendrerit massa dignissim tortor venenatis dapibus. Praesent pharetra euismod mi a pretium. Donec dignissim id odio vitae volutpat. Nullam finibus, leo a molestie volutpat, ipsum est vulputate urna, et luctus massa diam mattis massa. Aliquam iaculis malesuada dictum. Nullam at congue mi, ac accumsan mauris. Ut venenatis nec felis et maximus. Maecenas mattis libero eget nisi commodo malesuada. Curabitur tincidunt facilisis est ac suscipit. Curabitur dignissim massa a nisi posuere mattis.', 2, 18, 9);
insert into Review values(24, 'Donec vitae enim et leo efficitur mattis ut vitae neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla imperdiet sodales dictum. Nulla semper diam vitae nisi euismod, eget feugiat eros fermentum. Suspendisse vitae lacus malesuada nisi vehicula porta id eget quam. Nam et justo placerat, porta nisl in, blandit ipsum. In eget urna ac enim scelerisque aliquam id at erat. Nulla ac ipsum suscipit, lacinia purus sed, fringilla odio. Donec ultrices eros lacus, vel efficitur ex tristique eu. Fusce id cursus sapien.', 7, 10, 12);
insert into Review values(25, 'Pellentesque vehicula sit amet massa vitae lobortis. Aliquam eget sodales ligula, quis ullamcorper orci. Cras lectus lectus, efficitur sit amet sem eget, sodales tempor odio. Nam tincidunt, sapien nec condimentum ultricies, diam libero pellentesque sem, et lacinia diam erat et tellus. Ut tempus rhoncus mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque quis suscipit nisi. Aliquam quis facilisis nulla, sed posuere orci. Sed at facilisis erat. Donec facilisis ullamcorper euismod. Nulla eu maximus nulla. Morbi eget semper ante. Duis hendrerit sit amet felis vel feugiat. Donec sit amet ipsum pellentesque felis dignissim tincidunt commodo ac leo.', 5, 23, 9);
insert into Review values(26, 'In vel nunc non magna tristique vulputate quis vel mi. Fusce posuere egestas orci, at faucibus ex ullamcorper mattis. Donec luctus venenatis magna elementum pharetra. Proin vitae semper eros. Donec sagittis odio eget lectus ultricies, vitae molestie eros vulputate. Sed id tellus sed ante tincidunt faucibus quis nec odio. Sed felis sem, blandit vel molestie nec, tincidunt at dolor. Nullam ut nisi maximus, dictum mi et, porttitor sem. Nunc tristique nec augue ac tempus. Donec ullamcorper diam feugiat semper congue. Aliquam ut enim augue. Vestibulum et consectetur neque. Vivamus sodales id arcu sit amet aliquet.', 7, 14, 25);
insert into Review values(27, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce elementum neque justo, efficitur elementum nisl lobortis et. Etiam imperdiet mauris vel mauris sodales, sed aliquet sapien pulvinar. Pellentesque porttitor volutpat ex, in consequat ligula auctor non. Proin eu suscipit felis, eu cursus neque. Nullam bibendum sollicitudin quam, sed tempor ligula aliquam quis. Nullam in dolor ac nunc consectetur ornare. Vivamus quis sem neque.', 9, 18, 2);
insert into Review values(28, 'Proin tincidunt lorem eget libero vulputate tincidunt. Suspendisse ullamcorper cursus metus. In eu erat eu nulla accumsan aliquet. Quisque vitae nulla quis magna venenatis vehicula. Nunc facilisis libero vel eleifend cursus. Nunc sodales, neque vel vestibulum euismod, nisi felis tincidunt purus, vel aliquam libero tellus a est. Pellentesque luctus nisl in lobortis gravida. Curabitur efficitur leo nunc, eget rutrum velit varius ut.', 1, 16, 16);
insert into Review values(29, 'Pellentesque vehicula sit amet massa vitae lobortis. Aliquam eget sodales ligula, quis ullamcorper orci. Cras lectus lectus, efficitur sit amet sem eget, sodales tempor odio. Nam tincidunt, sapien nec condimentum ultricies, diam libero pellentesque sem, et lacinia diam erat et tellus. Ut tempus rhoncus mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque quis suscipit nisi. Aliquam quis facilisis nulla, sed posuere orci. Sed at facilisis erat. Donec facilisis ullamcorper euismod. Nulla eu maximus nulla. Morbi eget semper ante. Duis hendrerit sit amet felis vel feugiat. Donec sit amet ipsum pellentesque felis dignissim tincidunt commodo ac leo.', 7, 5, 15);

insert into Dish values(0, 25, 'burger', 30, 'fHObReSwa1', 'Tapas');
insert into Dish values(1, 22, 'chimichanga', 19, 'IiNQ41AEC2', 'Polish');
insert into Dish values(2, 8, 'wok', 5, 'Mbtzyplt8b', 'Asian Fusion');
insert into Dish values(3, 7, 'dessert', 11, 'ZA0eyD2Idk', 'Family Fare');
insert into Dish values(4, 15, 'ketchup', 36, 'Y7mbKK9szF', 'Mexican');
insert into Dish values(5, 9, 'skillet', 5, '7RztBZ9pWM', 'Burgers');
insert into Dish values(6, 21, 'bagel', 30, 'I4CEvNan0z', 'Breakfast');
insert into Dish values(7, 29, 'cheese', 28, 'BO2mixKM4P', 'Mediterranean');
insert into Dish values(8, 7, 'tartar', 25, 'OvcLcGPPul', 'Fast Food');
insert into Dish values(9, 17, 'juice', 27, 'fFCayi2fpC', 'Japanese');
insert into Dish values(10, 0, 'sopapillas', 11, 'elbaoXqF6F', 'Vegan Friendly');
insert into Dish values(11, 14, 'caviar', 21, 'seh6Hzrtv8', 'Swedish');
insert into Dish values(12, 0, 'water', 25, 'RySlhPRikF', 'Seafood');
insert into Dish values(13, 21, 'mushroom', 36, '23j0NB1DRS', 'Asian Fusion');
insert into Dish values(14, 18, 'tea', 9, 'l9X8NHCKO2', 'Caribbean');
insert into Dish values(15, 27, 'margarine', 11, 'KFZpMkK3gK', 'Country Food');
insert into Dish values(16, 24, 'muffin', 16, '6rknhYdKjF', 'Cafe');
insert into Dish values(17, 28, 'sauce', 23, 'fOu7guiv7m', 'Burgers');
insert into Dish values(18, 19, 'mayonnaise', 14, 'nzrv6L5Qhr', 'Seafood');
insert into Dish values(19, 21, 'dish', 32, 'o76n3s825b', 'Fast Food');
insert into Dish values(20, 12, 'pot', 23, 'sBxmfrO3od', 'British');
insert into Dish values(21, 25, 'spice', 3, 'FfwdcKr7Rt', 'Live Entertainment');
insert into Dish values(22, 13, 'tostada', 30, 'h7mor292wx', 'Live Entertainment');
insert into Dish values(23, 24, 'sandwich', 28, 'egMfQi1qoo', 'Doughnuts');
insert into Dish values(24, 0, 'burger', 16, '7RztBZ9pWM', 'Latin American');
insert into Dish values(25, 14, 'cocoa', 38, 'kiEvrdYOXL', 'Seafood');
insert into Dish values(26, 17, 'yogurt', 1, '788ZjLYdeq', 'Greek');
insert into Dish values(27, 12, 'crumble', 16, 'KHjMvZHJhu', 'Pancakes');
insert into Dish values(28, 8, 'vinegar', 21, 'KAmKDpmBmI', 'Fine Dining');
insert into Dish values(29, 18, 'seasoning', 26, 'l6EkcSm7HT', 'Live Entertainment');
insert into Dish values(30, 24, 'wok', 36, '2HFKSNDrOs', 'Deli');
insert into Dish values(31, 0, 'toast', 24, 'LeIxGywJls', 'American');
insert into Dish values(32, 27, 'coffee', 27, 'rMdAjkjbnk', 'Bakery');
insert into Dish values(33, 20, 'liquor', 26, 'FQ8EX5RBwT', 'Gluten-free');
insert into Dish values(34, 9, 'foie gras', 22, 'YPtiqAMhHy', 'Latin American');
insert into Dish values(35, 20, 'caviar', 28, 'XXqZ9rpGfX', 'Deli');
insert into Dish values(36, 1, 'entree', 17, 'yLEQFJWtOd', 'Soup & Salad');
insert into Dish values(37, 15, 'juice', 2, '2D5ITtrzJh', 'Mediterranean');
insert into Dish values(38, 2, 'cocoa', 23, 'aEUZvKrV0U', 'Brazilian');
insert into Dish values(39, 6, 'yeast', 18, 'puxo7L9yRO', 'Vegetarian');
insert into Dish values(40, 26, 'pudding', 28, 'QBxXu8WEYy', 'Waterfront');
insert into Dish values(41, 4, 'cuisine', 2, '3LsT11kfiz', 'Cafe');
insert into Dish values(42, 8, 'yogurt', 20, 'Ek6X5jm99B', 'French');
insert into Dish values(43, 26, 'candy', 23, 'FfwdcKr7Rt', 'Bagels');
insert into Dish values(44, 13, 'taquito', 4, 'Ghede0UZnZ', 'Steaks');
insert into Dish values(45, 2, 'marinade', 6, 'LL65ZP6zfX', 'Swedish');
insert into Dish values(46, 18, 'mushroom', 3, 'UjIwkWL2qa', 'Mexican');
insert into Dish values(47, 21, 'curd', 14, 'OxMrQiq7x7', 'Bagels');
insert into Dish values(48, 12, 'ketchup', 24, '6wbiuXXiyo', 'British');
insert into Dish values(49, 20, 'soy', 3, 'C6sr6rTbmO', 'Japanese');
insert into Dish values(50, 1, 'batter', 5, 'elbaoXqF6F', 'Vegetarian');
insert into Dish values(51, 2, 'recipe', 26, 'v41NCI72rD', 'Asian Fusion');
insert into Dish values(52, 0, 'cake', 10, 'qWl61gx3Sf', 'Burgers');
insert into Dish values(53, 22, 'cookie', 15, 'dXkaOiBpLy', 'Pizza');
insert into Dish values(54, 12, 'entree', 29, '2HFKSNDrOs', 'Spanish');
insert into Dish values(55, 29, 'soy', 22, 'Z2QrIjb5Dr', 'Barbeque');
insert into Dish values(56, 4, 'foie gras', 29, 't4chpXuOBJ', 'Vegetarian');
insert into Dish values(57, 11, 'queso', 25, 'sgR6BTNqtz', 'Bagels');
insert into Dish values(58, 8, 'soy', 36, 'cYqVfN2s7q', 'Bar');
insert into Dish values(59, 2, 'olive', 2, '1xSTR2m24c', 'Bagels');

insert into Dish_order values(0, 41, 15, 'delivering');
insert into Dish_order values(1, 45, 28, 'delivering');
insert into Dish_order values(2, 21, 12, 'delivering');
insert into Dish_order values(3, 21, 4, 'waiting to deliver');
insert into Dish_order values(4, 9, 27, 'waiting to deliver');
insert into Dish_order values(5, 32, 19, 'processing');
insert into Dish_order values(6, 32, 28, 'delivering');
insert into Dish_order values(7, 54, 16, 'preparing');
insert into Dish_order values(8, 49, 3, 'delivered');
insert into Dish_order values(9, 44, 13, 'delivered');
insert into Dish_order values(10, 6, 17, 'processing');
insert into Dish_order values(11, 20, 6, 'processing');
insert into Dish_order values(12, 10, 17, 'delivering');
insert into Dish_order values(13, 45, 3, 'preparing');
insert into Dish_order values(14, 10, 24, 'preparing');
insert into Dish_order values(15, 2, 7, 'preparing');
insert into Dish_order values(16, 10, 14, 'delivering');
insert into Dish_order values(17, 50, 15, 'preparing');
insert into Dish_order values(18, 21, 19, 'delivering');
insert into Dish_order values(19, 46, 1, 'delivered');
insert into Dish_order values(20, 31, 1, 'processing');
insert into Dish_order values(21, 38, 12, 'delivering');
insert into Dish_order values(22, 56, 8, 'preparing');
insert into Dish_order values(23, 17, 26, 'delivered');
insert into Dish_order values(24, 50, 0, 'waiting to deliver');
insert into Dish_order values(25, 32, 10, 'delivered');
insert into Dish_order values(26, 40, 24, 'delivered');
insert into Dish_order values(27, 51, 28, 'waiting to deliver');
insert into Dish_order values(28, 22, 0, 'delivered');
insert into Dish_order values(29, 57, 7, 'waiting to deliver');

insert into Restaurant_owner values(0, 5, 21);
insert into Restaurant_owner values(1, 19, 4);
insert into Restaurant_owner values(2, 27, 4);
insert into Restaurant_owner values(3, 16, 0);
insert into Restaurant_owner values(4, 9, 26);
insert into Restaurant_owner values(5, 11, 6);
insert into Restaurant_owner values(6, 18, 21);
insert into Restaurant_owner values(7, 8, 25);
insert into Restaurant_owner values(8, 27, 7);
insert into Restaurant_owner values(9, 8, 24);
insert into Restaurant_owner values(10, 26, 22);
insert into Restaurant_owner values(11, 26, 18);
insert into Restaurant_owner values(12, 27, 27);
insert into Restaurant_owner values(13, 4, 27);
insert into Restaurant_owner values(14, 10, 16);
insert into Restaurant_owner values(15, 28, 19);
insert into Restaurant_owner values(16, 25, 0);
insert into Restaurant_owner values(17, 14, 23);
insert into Restaurant_owner values(18, 4, 22);
insert into Restaurant_owner values(19, 29, 13);
insert into Restaurant_owner values(20, 5, 14);
insert into Restaurant_owner values(21, 4, 10);
insert into Restaurant_owner values(22, 21, 14);
insert into Restaurant_owner values(23, 0, 17);
insert into Restaurant_owner values(24, 25, 14);
insert into Restaurant_owner values(25, 11, 15);
insert into Restaurant_owner values(26, 28, 27);
insert into Restaurant_owner values(27, 15, 25);
insert into Restaurant_owner values(28, 25, 28);
insert into Restaurant_owner values(29, 28, 4);

COMMIT;